// BYOP ("Bring Your Own Pollen") auth. Documented fragment flow (not PKCE):
// the user authorizes on enter.pollinations.ai and returns with the key in
// the URL fragment (#api_key=sk_...). The fragment never hits server logs.
// client_id is optional - without it the consent screen falls back to the
// redirect hostname, so the flow works on any deployment origin.
// The key lives in sessionStorage only and is never logged or exported.
// The OAuth-style state value is generated per attempt, stored, and
// validated on return so unsolicited fragments cannot replace the account.

const STORAGE_KEY = "pi-web:pollinations-key";
const STATE_KEY = "pi-web:oauth-state";

// Pure parser, unit-tested with synthetic fragments.
export function parseAuthFragment(hash) {
    if (!hash || hash.length < 2) return null;
    const params = new URLSearchParams(hash.slice(1));
    const error = params.get("error");
    const state = params.get("state");
    if (error) return { error, state };
    const key = params.get("api_key");
    if (!key) return null;
    if (!key.startsWith("sk_")) return { error: "malformed_key", state };
    return { key, state };
}

export function authorizeUrl(redirectUri, state) {
    const params = new URLSearchParams({ redirect_uri: redirectUri });
    if (state) params.set("state", state);
    return `https://enter.pollinations.ai/authorize?${params.toString()}`;
}

export class AuthStore {
    constructor(storage) {
        this.storage = storage;
        this.keyGen = 0;
    }
    getKey() {
        return this.storage.getItem(STORAGE_KEY);
    }
    getKeyGen() {
        return this.keyGen;
    }
    setKey(key) {
        this.storage.setItem(STORAGE_KEY, key);
        this.keyGen += 1;
    }
    clear() {
        this.storage.removeItem(STORAGE_KEY);
        this.keyGen += 1;
    }
    beginAuthorize() {
        const state = crypto.randomUUID();
        this.storage.setItem(STATE_KEY, state);
        return state;
    }
    // Reads, validates and scrubs the fragment. Returns { connected, error }.
    consumeFragment(hash, replaceState) {
        const parsed = parseAuthFragment(hash);
        if (!parsed) return { connected: false, error: null };
        replaceState();
        const expected = this.storage.getItem(STATE_KEY);
        this.storage.removeItem(STATE_KEY);
        // Fail closed: a fragment is only accepted as the answer to an
        // authorize attempt we initiated (state generated by beginAuthorize).
        // Unsolicited fragments (no pending state) are rejected so an
        // attacker cannot swap the connected account via a crafted link.
        // Explicit key entry goes through the paste flow (setKey), not here.
        if (!expected || parsed.state !== expected)
            return { connected: false, error: "state_mismatch" };
        if (parsed.error) return { connected: false, error: parsed.error };
        this.setKey(parsed.key);
        return { connected: true, error: null };
    }
}
