/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --env-interface CloudflareBindings worker-bindings.d.ts` (hash: 73a7caf9fdcdf426ccba319592a6489d)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "PollenRateLimiter";
	}
	interface Env {
		KV: KVNamespace;
		ENVIRONMENT: "development" | "local" | "staging" | "test";
		LOG_LEVEL: "trace" | "debug";
		ALLOW_ANONYMOUS_USAGE: false | true;
		POLAR_SUCCESS_URL: "http://localhost:3000" | "https://enter.pollinations.ai";
		POLAR_SERVER: "sandbox";
		TINYBIRD_INGEST_URL: "http://localhost:7181/v0/events?name=generation_event" | "https://api.europe-west2.gcp.tinybird.co/v0/events?name=generation_event";
		POLAR_PRODUCT_ID_SEED: "82ee54e1-5b69-447b-82aa-3c76bccae193" | "19c3291a-e1fa-4a03-a08a-3de9ab84af5d" | "polar_product_id_seed";
		POLAR_PRODUCT_ID_FLOWER: "2bfbe9e0-8395-489f-a7a1-6821d835cc08" | "c675a78a-d954-4739-bfad-c0c8aa3e5576" | "polar_product_id_flower";
		POLAR_PRODUCT_ID_NECTAR: "d67b2a25-c4d7-47fa-9d64-4b2a27f0908f" | "dfe978ca-8e07-41fa-992a-ae19ab96e66c" | "polar_product_id_nectar";
		IMAGE_SERVICE_URL: "http://ec2-3-80-56-235.compute-1.amazonaws.com:16384" | "http://localhost:16384";
		TEXT_SERVICE_URL: "http://ec2-3-80-56-235.compute-1.amazonaws.com:16385" | "http://localhost:16385";
		POLLEN_BUCKET_CAPACITY: 0.1;
		POLLEN_REFILL_PER_HOUR: 1.0;
		BETTER_AUTH_SECRET: string;
		POLAR_ACCESS_TOKEN: string;
		GITHUB_CLIENT_ID: string;
		GITHUB_CLIENT_SECRET: string;
		TINYBIRD_ACCESS_TOKEN: string;
		TESTING_REFERRER: string;
		ENTER_TOKEN: string;
		POLLEN_RATE_LIMITER: DurableObjectNamespace /* PollenRateLimiter from pollinations-enter */;
		DB: D1Database;
	}
}
interface CloudflareBindings extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ENVIRONMENT" | "LOG_LEVEL" | "ALLOW_ANONYMOUS_USAGE" | "POLAR_SUCCESS_URL" | "POLAR_SERVER" | "TINYBIRD_INGEST_URL" | "POLAR_PRODUCT_ID_SEED" | "POLAR_PRODUCT_ID_FLOWER" | "POLAR_PRODUCT_ID_NECTAR" | "IMAGE_SERVICE_URL" | "TEXT_SERVICE_URL" | "POLLEN_BUCKET_CAPACITY" | "POLLEN_REFILL_PER_MINUTE" | "BETTER_AUTH_SECRET" | "POLAR_ACCESS_TOKEN" | "GITHUB_CLIENT_ID" | "GITHUB_CLIENT_SECRET" | "TINYBIRD_ACCESS_TOKEN" | "TESTING_REFERRER" | "ENTER_TOKEN">> {}
}
