/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --env-interface CloudflareBindings worker-bindings.d.ts` (hash: abd814bb474a4277546b789b394e6817)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "PollenRateLimiter";
	}
	interface Env {
		KV: KVNamespace;
		ENVIRONMENT: "development" | "local" | "production" | "staging" | "test";
		LOG_LEVEL: "trace" | "debug";
		ALLOW_ANONYMOUS_USAGE: false | true;
		POLAR_SUCCESS_URL: "http://localhost:3000" | "https://enter.pollinations.ai" | "https://staging.enter.pollinations.ai";
		POLAR_SERVER: "sandbox" | "production";
		TINYBIRD_INGEST_URL: "http://localhost:7181/v0/events?name=generation_event" | "https://api.europe-west2.gcp.tinybird.co/v0/events?name=generation_event";
		POLAR_PRODUCT_TIER_SEED: "c6f94c1b-c119-4e59-9f18-59391c8afee3" | "fe32ee28-c7c4-4e7a-87fa-6ffc062e3658" | "polar_product_id_seed";
		POLAR_PRODUCT_TIER_FLOWER: "18bdd5c4-dcb3-4a15-8ca6-1c0b45f76b84" | "dfb4c4f6-2004-4205-a358-b1f7bb3b310e" | "polar_product_id_flower";
		POLAR_PRODUCT_TIER_NECTAR: "a438764a-c486-4ff4-8f85-e66199c6b26f" | "066f91a4-8ed1-4329-b5f7-3f71e992ed28" | "polar_product_id_nectar";
		POLAR_PRODUCT_TIER_ROUTER: "9256189e-ad01-4608-8102-4ebfc4b506e0" | "0286ea62-540f-4b19-954f-b8edb9095c43";
		POLAR_PRODUCT_TIER_SPORE: "19fa1660-a90c-453d-8132-4d228cc7db39" | "01a31c1a-7af7-4958-9b73-c10e2fac5f70" | "polar_product_id_spore";
		POLAR_PRODUCT_PACK_5X2: "a34a0c8d-fc8f-4dd2-b53a-ddd91428d3cb" | "bcdde7f7-129e-4ec1-abc3-d4e0c852fa68" | "polar_product_id_5x2";
		POLAR_PRODUCT_PACK_10X2: "164ad1b8-6c4a-414e-9096-c9ca8608dfe3" | "cebeb680-4ac3-4f73-9ce7-6bc06a5f21e1" | "polar_product_id_10x2";
		POLAR_PRODUCT_PACK_20X2: "97cddb45-634f-4384-9e41-2fabca3c4fbf" | "8164c20f-8429-437e-b1a2-616ae89f114e" | "polar_product_id_20x2";
		POLAR_PRODUCT_PACK_50X2: "c7f8d94c-d55d-4744-85bf-8d3a7ffca92f" | "2cb5ca34-d505-450d-a1d4-94e3bb0c1f68" | "polar_product_id_50x2";
		IMAGE_SERVICE_URL: "http://ec2-3-80-56-235.compute-1.amazonaws.com:16384" | "http://localhost:16384" | "http://ec2-44-222-254-250.compute-1.amazonaws.com:16384";
		TEXT_SERVICE_URL: "http://ec2-3-80-56-235.compute-1.amazonaws.com:16385" | "http://localhost:16385" | "http://ec2-44-222-254-250.compute-1.amazonaws.com:16385";
		POLLEN_REFILL_PER_HOUR: 1;
		BETTER_AUTH_SECRET: string;
		GITHUB_CLIENT_ID: string;
		GITHUB_CLIENT_SECRET: string;
		TINYBIRD_ACCESS_TOKEN: string;
		TESTING_REFERRER: string;
		ENTER_TOKEN: string;
		POLAR_ACCESS_TOKEN: string;
		POLLEN_RATE_LIMITER: DurableObjectNamespace /* PollenRateLimiter from pollinations-enter */;
		IMAGE_BUCKET: R2Bucket;
		TEXT_BUCKET: R2Bucket;
		DB: D1Database;
	}
}
interface CloudflareBindings extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ENVIRONMENT" | "LOG_LEVEL" | "ALLOW_ANONYMOUS_USAGE" | "POLAR_SUCCESS_URL" | "POLAR_SERVER" | "TINYBIRD_INGEST_URL" | "POLAR_PRODUCT_TIER_SEED" | "POLAR_PRODUCT_TIER_FLOWER" | "POLAR_PRODUCT_TIER_NECTAR" | "POLAR_PRODUCT_TIER_ROUTER" | "POLAR_PRODUCT_TIER_SPORE" | "POLAR_PRODUCT_PACK_5X2" | "POLAR_PRODUCT_PACK_10X2" | "POLAR_PRODUCT_PACK_20X2" | "POLAR_PRODUCT_PACK_50X2" | "IMAGE_SERVICE_URL" | "TEXT_SERVICE_URL" | "POLLEN_REFILL_PER_HOUR" | "BETTER_AUTH_SECRET" | "GITHUB_CLIENT_ID" | "GITHUB_CLIENT_SECRET" | "TINYBIRD_ACCESS_TOKEN" | "TESTING_REFERRER" | "ENTER_TOKEN" | "POLAR_ACCESS_TOKEN">> {}
}
