/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --env-interface CloudflareBindings worker-bindings.d.ts` (hash: 46f41a650788564f6d319afc624c4595)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "PollenRateLimiter";
	}
	interface Env {
		KV: KVNamespace;
		ENVIRONMENT: "development" | "local" | "production" | "staging" | "test";
		LOG_LEVEL: "trace" | "debug";
		ALLOW_ANONYMOUS_USAGE: false | true;
		POLAR_SUCCESS_URL: "http://localhost:3000" | "https://enter.pollinations.ai" | "https://staging.enter.pollinations.ai";
		POLAR_SERVER: "production";
		TINYBIRD_INGEST_URL: "http://localhost:7181/v0/events?name=generation_event" | "https://api.europe-west2.gcp.tinybird.co/v0/events?name=generation_event";
		POLAR_PRODUCT_TIER_SEED: "fe32ee28-c7c4-4e7a-87fa-6ffc062e3658" | "5cbd2495-dba1-4840-8465-46afd9b16679" | "polar_product_id_seed";
		POLAR_PRODUCT_TIER_FLOWER: "dfb4c4f6-2004-4205-a358-b1f7bb3b310e" | "ea33ef88-67ff-45d8-906e-bb9357dd549a" | "polar_product_id_flower";
		POLAR_PRODUCT_TIER_NECTAR: "066f91a4-8ed1-4329-b5f7-3f71e992ed28" | "10167875-38e1-459f-8241-106aafc3062c" | "polar_product_id_nectar";
		POLAR_PRODUCT_TIER_ROUTER: "0286ea62-540f-4b19-954f-b8edb9095c43";
		POLAR_PRODUCT_PACK_5X2: "bcdde7f7-129e-4ec1-abc3-d4e0c852fa68";
		POLAR_PRODUCT_PACK_10X2: "cebeb680-4ac3-4f73-9ce7-6bc06a5f21e1";
		POLAR_PRODUCT_PACK_20X2: "8164c20f-8429-437e-b1a2-616ae89f114e";
		POLAR_PRODUCT_PACK_50X2: "2cb5ca34-d505-450d-a1d4-94e3bb0c1f68";
		IMAGE_SERVICE_URL: "http://ec2-3-80-56-235.compute-1.amazonaws.com:16384" | "http://localhost:16384";
		TEXT_SERVICE_URL: "http://ec2-3-80-56-235.compute-1.amazonaws.com:16385" | "http://localhost:16385";
		BETTER_AUTH_SECRET: string;
		POLAR_ACCESS_TOKEN: string;
		GITHUB_CLIENT_ID: string;
		GITHUB_CLIENT_SECRET: string;
		TINYBIRD_ACCESS_TOKEN: string;
		TESTING_REFERRER: string;
		ENTER_TOKEN: string;
		POLLEN_RATE_LIMITER: DurableObjectNamespace /* PollenRateLimiter from pollinations-enter */;
		IMAGE_BUCKET: R2Bucket;
		DB: D1Database;
		EDGE_RATE_LIMITER: RateLimit;
	}
}
interface CloudflareBindings extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ENVIRONMENT" | "LOG_LEVEL" | "ALLOW_ANONYMOUS_USAGE" | "POLAR_SUCCESS_URL" | "POLAR_SERVER" | "TINYBIRD_INGEST_URL" | "POLAR_PRODUCT_TIER_SEED" | "POLAR_PRODUCT_TIER_FLOWER" | "POLAR_PRODUCT_TIER_NECTAR" | "POLAR_PRODUCT_TIER_ROUTER" | "POLAR_PRODUCT_PACK_5X2" | "POLAR_PRODUCT_PACK_10X2" | "POLAR_PRODUCT_PACK_20X2" | "POLAR_PRODUCT_PACK_50X2" | "IMAGE_SERVICE_URL" | "TEXT_SERVICE_URL" | "BETTER_AUTH_SECRET" | "POLAR_ACCESS_TOKEN" | "GITHUB_CLIENT_ID" | "GITHUB_CLIENT_SECRET" | "TINYBIRD_ACCESS_TOKEN" | "TESTING_REFERRER" | "ENTER_TOKEN">> {}
}
