# GitHub Sponsors for pollinations.ai
# pollinations.ai offers production-ready text and image APIs with daily pollen grants for developers.
# With over 60 million pieces of media generated monthly our platform is trusted by users around the globe and integrated by 300+ projects.
# Join us in sustaining and expanding these services.
github: [pollinations]

# Support via Open Collective
# Show your support with one-time or recurring contributions to help sustain our pollen-based platform.
open_collective: pollinationsai

# Support via Ko-fi
# Show your support with one-time or recurring contributions to help sustain our pollen-based platform.
ko_fi: pollinationsai
