# GitHub Sponsors for Pollinations.AI
# Pollinations.AI offers production-ready text and image APIs that are free to use with no sign-ups or API keys.
# With over 60 million pieces of media generated monthly our platform is trusted by users around the globe and integrated by 300+ projects.
# Join us in sustaining and expanding these services.
github: [pollinations]

# Support via Open Collective
# Show your support with one-time or recurring contributions to help sustain our free service.
open_collective: pollinationsai

# Support via Ko-fi
# Show your support with one-time or recurring contributions to help sustain our free service.
ko_fi: pollinationsai
