/**
 * Canonical IDs that will be promoted by the canonical-model rename.
 *
 * Until that rename deploys, these IDs are forward-compatible aliases for the
 * current registry keys. Keep this map byte-for-byte aligned with the rename
 * migration so both deployments recognize both sides of every rename.
 */
export const CANONICAL_MODEL_PROMOTIONS = {
    "openai/gpt-5.4-nano": "openai",
    "openai/gpt-5-nano": "openai-fast",
    "openai/gpt-oss-20b": "gpt-oss",
    "openai/gpt-5.4": "gpt-5.4",
    "openai/gpt-5.4-mini": "gpt-5.4-mini",
    "openai/gpt-5.5": "openai-large",
    "openai/gpt-5.6-sol": "gpt-5.6-sol",
    "openai/gpt-5.6-terra": "gpt-5.6-terra",
    "openai/gpt-5.6-luna": "gpt-5.6-luna",
    "inception/mercury-2": "mercury",
    "command-a-plus-05-2026": "command-a-plus",
    "qwen/qwen3-coder-30b-a3b-instruct": "qwen-coder",
    "mistralai/mistral-small-3.2-24b-instruct": "mistral-small-3.2",
    "mistralai/mistral-small-2603": "mistral",
    "openai/gpt-audio-mini": "openai-audio",
    "openai/gpt-audio-1.5": "openai-audio-large",
    "google/gemini-3-flash-preview": "gemini-3-flash",
    "google/gemini-3.6-flash": "gemini",
    "google/gemini-3.5-flash-lite": "gemini-flash-lite-3.5",
    "google/gemini-2.5-flash-lite": "gemini-fast",
    "deepseek/deepseek-v4-flash-0731": "deepseek",
    "google/gemma-4-26b-a4b-it": "gemma",
    "google/gemma-4-31b-it": "gemma-4-31b",
    "deepseek/deepseek-v4-pro": "deepseek-pro",
    "x-ai/grok-4.3": "grok-large",
    "x-ai/grok-4.5": "grok-4.5",
    "anthropic/claude-haiku-4.5": "claude-fast",
    "anthropic/claude-sonnet-4.6": "claude",
    "anthropic/claude-sonnet-5": "claude-sonnet-5",
    "anthropic/claude-opus-4.6": "claude-opus-4.6",
    "anthropic/claude-opus-4.7": "claude-opus-4.7",
    "anthropic/claude-opus-5": "claude-large",
    "anthropic/claude-fable-5": "claude-fable-5",
    "perplexity/sonar-pro": "perplexity",
    "perplexity/sonar-reasoning-pro": "perplexity-reasoning",
    "moonshotai/kimi-k2.6": "kimi",
    "moonshotai/kimi-k2.7-code": "kimi-code",
    "moonshotai/kimi-k3": "kimi-k3",
    "poolside/laguna-s-2.1": "laguna",
    "meituan/longcat-2.0": "longcat",
    "thinkingmachines/inkling-small": "inkling",
    "nvidia/nemotron-3-ultra-550b-a55b": "nemotron",
    "xiaomi/mimo-v2.5": "mimo-v2.5",
    "xiaomi/mimo-v2.5-pro": "mimo-v2.5-pro",
    "google/gemini-3.1-pro-preview": "gemini-large",
    "amazon/nova-micro-v1": "nova-fast",
    "amazon/nova-2-lite-v1": "nova",
    "z-ai/glm-5.2": "glm",
    "meta-llama/llama-3.3-70b-instruct": "llama",
    "meta-llama/llama-4-maverick": "llama-maverick",
    "meta-llama/llama-4-scout": "llama-scout",
    "minimax/minimax-m2.7": "minimax-m2.7",
    "minimax/minimax-m3": "minimax",
    "meta/muse-spark-1.1": "muse-spark-1.1",
    "mistralai/mistral-large-2512": "mistral-large",
    "qwen/qwen3-coder-next": "qwen-coder-large",
    "qwen/qwen3.7-plus": "qwen-large",
    "qwen/qwen3.7-max": "qwen3.7-max",
    "qwen/qwen3.8-max": "qwen3.8-max",
    "qwen/qwen3.7-flash": "qwen3.7-flash",
    "qwen/qwen3-vl-30b-a3b-instruct": "qwen-vision",
    "qwen/qwen3-vl-235b-a22b-thinking": "qwen-vision-pro",
    "stepfun/step-3.7-flash": "step-flash",
    "stepfun/step-3.5-flash": "step-3.5-flash",
    "qwen/qwen3guard-gen-8b": "qwen-safety",
    "krea/krea-2-medium": "krea",
    "black-forest-labs/flux.1-kontext-pro": "kontext",
    "google/gemini-2.5-flash-image": "nanobanana",
    "google/gemini-3.1-flash-image": "nanobanana-2",
    "google/gemini-3.1-flash-lite-image": "nanobanana-2-lite",
    "google/gemini-3-pro-image": "nanobanana-pro",
    "bytedance/seedream-5-lite": "seedream5",
    "bytedance/seedream-5-pro": "seedream5-pro",
    "bytedance/seedream-4": "seedream",
    "bytedance-seed/seedream-4.5": "seedream-pro",
    "ideogram-ai/ideogram-v4-turbo": "ideogram-v4-turbo",
    "ideogram-ai/ideogram-v4-balanced": "ideogram-v4-balanced",
    "ideogram-ai/ideogram-v4-quality": "ideogram-v4-quality",
    "openai/gpt-image-1-mini": "gptimage",
    "openai/gpt-image-1.5": "gptimage-large",
    "openai/gpt-image-2": "gpt-image-2",
    "black-forest-labs/FLUX.1-schnell": "flux",
    "Tongyi-MAI/Z-Image-Turbo": "zimage",
    "google/veo-3.1-fast": "veo",
    "bytedance/seedance-1-pro-fast": "seedance-pro",
    "bytedance/seedance-2.0": "seedance-2.0",
    "alibaba/wan-2.6": "wan",
    "wan-video/wan-2.2-fast": "wan-fast",
    "alibaba/wan-2.7": "wan-pro",
    "wan-video/wan-2.7-image": "wan-image",
    "wan-video/wan-2.7-image-pro": "wan-image-pro",
    "qwen/qwen-image": "qwen-image",
    "x-ai/grok-imagine-image": "grok-imagine",
    "x-ai/grok-imagine-image-quality": "grok-imagine-pro",
    "recraft/recraft-v4.1-vector": "recraft-v4.1-vector",
    "x-ai/grok-imagine-video": "grok-video-pro",
    "x-ai/grok-imagine-video-1.5": "grok-imagine-video-1.5",
    "alibaba/happyhorse-1.1": "happyhorse-1.1",
    "black-forest-labs/flux.2-klein-4b": "klein",
    "PrunaAI/p-image": "p-image",
    "PrunaAI/p-image-Edit": "p-image-edit",
    "prunaai/p-video": "p-video",
    "amazon.nova-canvas-v1:0": "nova-canvas",
    "amazon.nova-reel-v1:1": "nova-reel",
    "elevenlabs/eleven-v3": "elevenlabs",
    "elevenlabs/eleven-flash-v2.5": "elevenflash",
    "elevenlabs/eleven-multilingual-v2": "eleven-multilingual-v2",
    "elevenlabs/music-v2": "elevenmusic",
    "google/lyria-3-clip-preview": "lyria-3-clip",
    "elevenlabs/eleven-text-to-sound-v2": "eleven-sfx",
    "openai/whisper-large-v3": "whisper",
    "elevenlabs/scribe-v2": "scribe",
    "assemblyai/universal-2": "universal-2",
    "assemblyai/universal-3.5-pro": "universal-3.5-pro",
    "fal-ai/stable-audio-3/medium": "stable-audio-3-medium",
    "stable-audio-3": "stable-audio-3-large",
    "qwen/qwen3-tts-flash": "qwen-tts",
    "qwen/qwen3-tts-instruct-flash": "qwen-tts-instruct",
    "sesame/csm-1b": "csm-1b",
    "hexgrad/kokoro-82m": "kokoro",
    "google/gemini-embedding-2": "gemini-2",
    "openai/text-embedding-3-small": "openai-3-small",
    "openai/text-embedding-3-large": "openai-3-large",
    "embed-v4.0": "cohere-embed-v4",
    "qwen/qwen3-embedding-8b": "qwen3-embedding-8b",
    "openai/gpt-realtime-2.1": "gpt-realtime-2.1",
    "openai/gpt-realtime-2.1-mini": "gpt-realtime-2.1-mini",
    "openai/gpt-realtime-2": "gpt-realtime-2",
} as const;

const promotionAliasesByCurrent = new Map<string, string[]>();
for (const [futureCanonical, currentCanonical] of Object.entries(
    CANONICAL_MODEL_PROMOTIONS,
)) {
    const aliases = promotionAliasesByCurrent.get(currentCanonical) ?? [];
    aliases.push(futureCanonical);
    promotionAliasesByCurrent.set(currentCanonical, aliases);
}

export function getCanonicalPromotionAliases(
    currentCanonical: string,
): readonly string[] {
    return promotionAliasesByCurrent.get(currentCanonical) ?? [];
}
