import type { ModelDefinition } from "./registry";

export const DEFAULT_IMAGE_MODEL = "zimage" as const;

export type ImageModelName = keyof typeof IMAGE_SERVICES;

export const IMAGE_SERVICES = {
    "kontext": {
        brand: "Black Forest Labs",
        provider: "azure",
        model: "flux.1-kontext",
        aliases: [],
        description: "Image generation and editing from text and image input.",
        category: "image",
        inputModalities: ["text", "image"],
        outputModalities: ["image"],
        introducedAt: 1753999200000,
        cost: {
            completionImageTokens: 0.04,
        },
    },
    "nanobanana": {
        brand: "Google",
        provider: "google",
        model: "gemini-2.5-flash-image",
        aliases: [],
        description: "Image generation and editing from text and image input.",
        category: "image",
        profile: "fast",
        inputModalities: ["text", "image"],
        outputModalities: ["image"],
        paidOnly: true,
        introducedAt: 1753999200000,
        cost: {
            promptTextTokens: 0.0000003,
            promptImageTokens: 0.0000003,
            completionImageTokens: 0.00003,
        },
    },
    "nanobanana-2": {
        brand: "Google",
        provider: "google",
        model: "gemini-3.1-flash-image",
        aliases: ["nanobanana2"],
        description: "Image generation and editing from text and image input.",
        category: "image",
        profile: "fast",
        inputModalities: ["text", "image"],
        outputModalities: ["image"],
        paidOnly: true,
        introducedAt: 1753999200000,
        cost: {
            promptTextTokens: 0.0000005,
            promptImageTokens: 0.0000005,
            completionImageTokens: 0.00006,
        },
    },
    "nanobanana-pro": {
        brand: "Google",
        provider: "google",
        model: "gemini-3-pro-image",
        aliases: [],
        description: "Image generation and editing from text and image input.",
        category: "image",
        profile: "pro",
        inputModalities: ["text", "image"],
        outputModalities: ["image"],
        paidOnly: true,
        introducedAt: 1753999200000,
        cost: {
            promptTextTokens: 0.00000125,
            promptImageTokens: 0.00000125,
            completionImageTokens: 0.00012,
        },
    },
    "seedream5": {
        brand: "ByteDance",
        provider: "bytedance",
        model: "seedream-5.0-lite",
        aliases: [],
        description: "Image generation and editing from text and image input.",
        category: "image",
        profile: "fast",
        inputModalities: ["text", "image"],
        outputModalities: ["image"],
        paidOnly: true,
        introducedAt: 1753999200000,
        cost: {
            completionImageTokens: 0.035,
        },
        price: {
            completionImageTokens: 0.0525,
        },
    },
    "seedream": {
        brand: "ByteDance",
        provider: "bytedance",
        model: "seedream-4.0",
        aliases: [],
        description: "Image generation and editing from text and image input.",
        category: "image",
        inputModalities: ["text", "image"],
        outputModalities: ["image"],
        hidden: true,
        paidOnly: true,
        introducedAt: 1753999200000,
        cost: {
            completionImageTokens: 0.03,
        },
        price: {
            completionImageTokens: 0.045,
        },
    },
    "seedream-pro": {
        brand: "ByteDance",
        provider: "bytedance",
        model: "seedream-4.5-pro",
        aliases: [],
        description: "Image generation and editing from text and image input.",
        category: "image",
        profile: "pro",
        inputModalities: ["text", "image"],
        outputModalities: ["image"],
        hidden: true,
        paidOnly: true,
        introducedAt: 1753999200000,
        cost: {
            completionImageTokens: 0.04,
        },
        price: {
            completionImageTokens: 0.06,
        },
    },
    "gptimage": {
        brand: "OpenAI",
        provider: "azure",
        model: "gpt-image-1-mini",
        aliases: ["gpt-image", "gpt-image-1-mini"],
        description: "Image generation and editing from text and image input.",
        category: "image",
        profile: "fast",
        inputModalities: ["text", "image"],
        outputModalities: ["image"],
        introducedAt: 1753999200000,
        cost: {
            promptTextTokens: 0.000002,
            promptCachedTokens: 0.0000002,
            promptImageTokens: 0.0000025,
            completionImageTokens: 0.000008,
        },
    },
    "gptimage-large": {
        brand: "OpenAI",
        provider: "azure",
        model: "gpt-image-1.5",
        aliases: ["gpt-image-1.5", "gpt-image-large"],
        description: "Image generation and editing from text and image input.",
        category: "image",
        profile: "pro",
        inputModalities: ["text", "image"],
        outputModalities: ["image"],
        introducedAt: 1753999200000,
        cost: {
            promptTextTokens: 0.000005,
            promptCachedTokens: 0.00000125,
            promptImageTokens: 0.000008,
            completionImageTokens: 0.000032,
        },
    },
    "gpt-image-2": {
        brand: "OpenAI",
        provider: "azure",
        model: "gpt-image-2",
        aliases: [],
        description: "Image generation and editing from text and image input.",
        category: "image",
        profile: "pro",
        inputModalities: ["text", "image"],
        outputModalities: ["image"],
        introducedAt: new Date("2026-04-22").getTime(),
        cost: {
            promptTextTokens: 0.000005,
            promptCachedTokens: 0.00000125,
            promptImageTokens: 0.000008,
            completionImageTokens: 0.00003,
        },
    },
    "flux": {
        brand: "Black Forest Labs",
        provider: "runpod",
        model: "flux-schnell",
        aliases: [],
        description: "Image generation from text prompts.",
        category: "image",
        inputModalities: ["text"],
        outputModalities: ["image"],
        introducedAt: 1753999200000,
        cost: {
            completionImageTokens: 0.001,
        },
    },
    "zimage": {
        brand: "Pollinations",
        provider: "runpod",
        model: "z-image-turbo",
        aliases: ["z-image", "z-image-turbo"],
        description: "Image generation from text prompts.",
        category: "image",
        inputModalities: ["text"],
        outputModalities: ["image"],
        introducedAt: 1753999200000,
        cost: {
            completionImageTokens: 0.002,
        },
    },
    "veo": {
        brand: "Google",
        provider: "google",
        model: "veo-3.1-fast",
        version: "preview",
        aliases: ["veo-3.1-fast", "video"],
        description: "Video generation from text and image input.",
        category: "video",
        profile: "fast",
        inputModalities: ["text", "image"],
        outputModalities: ["video"],
        paidOnly: true,
        introducedAt: 1753999200000,
        cost: {
            completionVideoSeconds: 0.15,
        },
    },
    "seedance": {
        brand: "ByteDance",
        provider: "bytedance",
        model: "seedance-lite",
        aliases: [],
        description: "Video generation from text and image input.",
        category: "video",
        profile: "fast",
        inputModalities: ["text", "image"],
        outputModalities: ["video"],
        paidOnly: true,
        introducedAt: 1753999200000,
        cost: {
            completionVideoTokens: 0.0000018,
        },
        price: {
            completionVideoTokens: 0.0000027,
        },
    },
    "seedance-pro": {
        brand: "ByteDance",
        provider: "bytedance",
        model: "seedance-pro-fast",
        aliases: [],
        description: "Video generation from text and image input.",
        category: "video",
        profile: "pro",
        inputModalities: ["text", "image"],
        outputModalities: ["video"],
        paidOnly: true,
        introducedAt: 1753999200000,
        cost: {
            completionVideoTokens: 0.000001,
        },
        price: {
            completionVideoTokens: 0.0000015,
        },
    },
    "wan": {
        brand: "Alibaba",
        provider: "alibaba",
        model: "wan-2.6",
        aliases: ["wan2.6", "wan-i2v"],
        description: "Video generation from text and image input.",
        category: "video",
        inputModalities: ["text", "image"],
        outputModalities: ["video"],
        paidOnly: true,
        introducedAt: 1771545600000,
        cost: {
            completionAudioSeconds: 0.05,
            completionVideoSeconds: 0.05,
        },
        price: {
            completionAudioSeconds: 0.075,
            completionVideoSeconds: 0.075,
        },
    },
    "wan-fast": {
        brand: "Alibaba",
        provider: "alibaba",
        model: "wan-2.2",
        aliases: ["wan2.2", "wan-2.2"],
        description: "Video generation from text and image input.",
        category: "video",
        profile: "fast",
        inputModalities: ["text", "image"],
        outputModalities: ["video"],
        paidOnly: true,
        introducedAt: 1774224000000,
        cost: {
            completionAudioSeconds: 0.01,
            completionVideoSeconds: 0.01,
        },
        price: {
            completionAudioSeconds: 0.015,
            completionVideoSeconds: 0.015,
        },
    },
    "wan-image": {
        brand: "Alibaba",
        provider: "alibaba",
        model: "wan-2.7-image",
        aliases: ["wan2.7-image", "wan-img"],
        description: "Image generation and editing from text and image input.",
        category: "image",
        inputModalities: ["text", "image"],
        outputModalities: ["image"],
        introducedAt: 1775088000000,
        cost: {
            completionImageTokens: 0.035,
        },
        price: {
            completionImageTokens: 0.0525,
        },
    },
    "wan-image-pro": {
        brand: "Alibaba",
        provider: "alibaba",
        model: "wan-2.7-image-pro",
        aliases: ["wan2.7-image-pro", "wan-img-pro"],
        description: "Image generation and editing from text and image input.",
        category: "image",
        profile: "pro",
        inputModalities: ["text", "image"],
        outputModalities: ["image"],
        paidOnly: true,
        introducedAt: 1775088000000,
        cost: {
            completionImageTokens: 0.075,
        },
        price: {
            completionImageTokens: 0.1125,
        },
    },
    "qwen-image": {
        brand: "Qwen",
        provider: "alibaba",
        model: "qwen-image-plus",
        aliases: [
            "qwen-image-plus",
            "qwen-image-2512",
            "qwen-image-edit",
            "qwen-image-edit-plus",
        ],
        description: "Image generation and editing from text and image input.",
        category: "image",
        inputModalities: ["text", "image"],
        outputModalities: ["image"],
        introducedAt: 1774137600000,
        cost: {
            completionImageTokens: 0.03,
        },
        price: {
            completionImageTokens: 0.045,
        },
    },
    "grok-imagine": {
        brand: "xAI",
        provider: "xai",
        model: "grok-imagine",
        aliases: ["grok-imagine-image"],
        description: "Image generation from text prompts.",
        category: "image",
        inputModalities: ["text"],
        outputModalities: ["image"],
        paidOnly: true,
        introducedAt: 1774137600000,
        cost: {
            completionImageTokens: 0.02,
        },
        price: {
            completionImageTokens: 0.03,
        },
    },
    "grok-imagine-pro": {
        brand: "xAI",
        provider: "xai",
        model: "grok-imagine-pro",
        aliases: ["grok-aurora", "aurora", "grok-imagine-image-pro"],
        description: "Image generation from text prompts.",
        category: "image",
        profile: "pro",
        inputModalities: ["text"],
        outputModalities: ["image"],
        paidOnly: true,
        introducedAt: 1774137600000,
        cost: {
            completionImageTokens: 0.07,
        },
        price: {
            completionImageTokens: 0.105,
        },
    },
    "grok-video-pro": {
        brand: "xAI",
        provider: "xai",
        model: "grok-video-pro",
        aliases: ["grok-imagine-video"],
        description: "Video generation from text and image input.",
        category: "video",
        profile: "pro",
        inputModalities: ["text", "image"],
        outputModalities: ["video"],
        paidOnly: true,
        introducedAt: 1774137600000,
        cost: {
            completionVideoSeconds: 0.05,
        },
        price: {
            completionVideoSeconds: 0.075,
        },
    },
    "klein": {
        brand: "Black Forest Labs",
        provider: "runpod",
        model: "flux.2-klein-4b",
        aliases: ["flux-klein"],
        description: "Image generation and editing from text and image input.",
        category: "image",
        inputModalities: ["text", "image"],
        outputModalities: ["image"],
        alpha: true,
        introducedAt: 1768953600000,
        cost: {
            completionImageTokens: 0.01,
        },
    },
    "ltx-2": {
        brand: "Lightricks",
        provider: "lambda",
        model: "ltx-video-2.3",
        aliases: ["ltx2", "ltx-2.3", "ltxvideo", "ltx-video"],
        description: "Video generation from text prompts.",
        category: "video",
        inputModalities: ["text"],
        outputModalities: ["video"],
        alpha: true,
        introducedAt: 1774224000000,
        cost: {
            completionVideoSeconds: 0.005,
        },
    },
    "p-image": {
        brand: "Pruna",
        provider: "pruna",
        model: "p-image",
        aliases: ["pruna-image", "pruna"],
        description: "Image generation from text prompts.",
        category: "image",
        inputModalities: ["text"],
        outputModalities: ["image"],
        paidOnly: true,
        introducedAt: 1773360000000,
        cost: {
            completionImageTokens: 0.005,
        },
        price: {
            completionImageTokens: 0.0075,
        },
    },
    "p-image-edit": {
        brand: "Pruna",
        provider: "pruna",
        model: "p-image-edit",
        aliases: ["pruna-edit", "pruna-image-edit"],
        description: "Image generation and editing from text and image input.",
        category: "image",
        inputModalities: ["text", "image"],
        outputModalities: ["image"],
        paidOnly: true,
        introducedAt: 1773360000000,
        cost: {
            completionImageTokens: 0.01,
        },
        price: {
            completionImageTokens: 0.015,
        },
    },
    "p-video": {
        brand: "Pruna",
        provider: "pruna",
        model: "p-video",
        aliases: ["pruna-video"],
        description: "Video generation from text and image input.",
        category: "video",
        inputModalities: ["text", "image"],
        outputModalities: ["video"],
        paidOnly: true,
        introducedAt: 1773360000000,
        cost: {
            completionVideoSeconds: 0.024,
        },
        price: {
            completionVideoSeconds: 0.036,
        },
    },
    "nova-canvas": {
        brand: "Amazon",
        provider: "aws",
        model: "nova-canvas",
        aliases: ["amazon-nova-canvas"],
        description: "Image generation and editing from text and image input.",
        category: "image",
        inputModalities: ["text", "image"],
        outputModalities: ["image"],
        paidOnly: true,
        introducedAt: 1753999200000,
        cost: {
            completionImageTokens: 0.04,
        },
    },
    "nova-reel": {
        brand: "Amazon",
        provider: "aws",
        model: "nova-reel",
        aliases: ["amazon-nova-reel"],
        description: "Video generation from text and image input.",
        category: "video",
        inputModalities: ["text", "image"],
        outputModalities: ["video"],
        introducedAt: 1753999200000,
        cost: {
            completionVideoSeconds: 0.08,
        },
    },
} as const satisfies Record<string, ModelDefinition>;
