import type { ModelDefinition } from "./registry";

export const DEFAULT_IMAGE_MODEL = "z-image-turbo" as const;

export type ImageModelName = keyof typeof IMAGE_SERVICES;

export const IMAGE_SERVICES = {
    "flux-1-kontext": {
        brand: "Black Forest Labs",
        provider: "azure",
        model: "flux.1-kontext",
        aliases: ["kontext"],
        description: "Image generation and editing from text and image input.",
        category: "image",
        inputModalities: ["text", "image"],
        outputModalities: ["image"],
        introducedAt: 1753999200000,
        cost: {
            completionImageTokens: 0.04,
        },
    },
    "nanobanana-2.5": {
        brand: "Google",
        provider: "google",
        model: "gemini-2.5-flash-image",
        aliases: ["nanobanana"],
        description: "Image generation and editing from text and image input.",
        category: "image",
        profile: "fast",
        inputModalities: ["text", "image"],
        outputModalities: ["image"],
        paidOnly: true,
        introducedAt: 1753999200000,
        cost: {
            promptTextTokens: 0.0000003,
            promptImageTokens: 0.0000003,
            completionImageTokens: 0.00003,
        },
    },
    "nanobanana-3.1": {
        brand: "Google",
        provider: "google",
        model: "gemini-3.1-flash-image",
        aliases: ["nanobanana-2", "nanobanana2"],
        description: "Image generation and editing from text and image input.",
        category: "image",
        profile: "fast",
        inputModalities: ["text", "image"],
        outputModalities: ["image"],
        paidOnly: true,
        introducedAt: 1753999200000,
        cost: {
            promptTextTokens: 0.0000005,
            promptImageTokens: 0.0000005,
            completionImageTokens: 0.00006,
        },
    },
    "nanobanana-pro-3": {
        brand: "Google",
        provider: "google",
        model: "gemini-3-pro-image",
        aliases: ["nanobanana-pro"],
        description: "Image generation and editing from text and image input.",
        category: "image",
        profile: "pro",
        inputModalities: ["text", "image"],
        outputModalities: ["image"],
        paidOnly: true,
        introducedAt: 1753999200000,
        cost: {
            promptTextTokens: 0.00000125,
            promptImageTokens: 0.00000125,
            completionImageTokens: 0.00012,
        },
    },
    "seedream-5-lite": {
        brand: "ByteDance",
        provider: "bytedance",
        model: "seedream-5.0-lite",
        aliases: ["seedream5"],
        description: "Image generation and editing from text and image input.",
        category: "image",
        profile: "fast",
        inputModalities: ["text", "image"],
        outputModalities: ["image"],
        paidOnly: true,
        introducedAt: 1753999200000,
        cost: {
            completionImageTokens: 0.035,
        },
        price: {
            completionImageTokens: 0.0525,
        },
    },
    "seedream-4": {
        brand: "ByteDance",
        provider: "bytedance",
        model: "seedream-4.0",
        aliases: ["seedream"],
        description: "Image generation and editing from text and image input.",
        category: "image",
        inputModalities: ["text", "image"],
        outputModalities: ["image"],
        hidden: true,
        paidOnly: true,
        introducedAt: 1753999200000,
        cost: {
            completionImageTokens: 0.03,
        },
        price: {
            completionImageTokens: 0.045,
        },
    },
    "seedream-4.5-pro": {
        brand: "ByteDance",
        provider: "bytedance",
        model: "seedream-4.5-pro",
        aliases: ["seedream-pro"],
        description: "Image generation and editing from text and image input.",
        category: "image",
        profile: "pro",
        inputModalities: ["text", "image"],
        outputModalities: ["image"],
        hidden: true,
        paidOnly: true,
        introducedAt: 1753999200000,
        cost: {
            completionImageTokens: 0.04,
        },
        price: {
            completionImageTokens: 0.06,
        },
    },
    "gpt-image-1-mini": {
        brand: "OpenAI",
        provider: "azure",
        model: "gpt-image-1-mini",
        aliases: ["gptimage", "gpt-image"],
        description: "Image generation and editing from text and image input.",
        category: "image",
        profile: "fast",
        inputModalities: ["text", "image"],
        outputModalities: ["image"],
        introducedAt: 1753999200000,
        cost: {
            promptTextTokens: 0.000002,
            promptCachedTokens: 0.0000002,
            promptImageTokens: 0.0000025,
            completionImageTokens: 0.000008,
        },
    },
    "gpt-image-1.5": {
        brand: "OpenAI",
        provider: "azure",
        model: "gpt-image-1.5",
        aliases: ["gptimage-large", "gpt-image-large"],
        description: "Image generation and editing from text and image input.",
        category: "image",
        profile: "pro",
        inputModalities: ["text", "image"],
        outputModalities: ["image"],
        introducedAt: 1753999200000,
        cost: {
            promptTextTokens: 0.000005,
            promptCachedTokens: 0.00000125,
            promptImageTokens: 0.000008,
            completionImageTokens: 0.000032,
        },
    },
    "gpt-image-2": {
        brand: "OpenAI",
        provider: "azure",
        model: "gpt-image-2",
        aliases: [],
        description: "Image generation and editing from text and image input.",
        category: "image",
        profile: "pro",
        inputModalities: ["text", "image"],
        outputModalities: ["image"],
        introducedAt: new Date("2026-04-22").getTime(),
        cost: {
            promptTextTokens: 0.000005,
            promptCachedTokens: 0.00000125,
            promptImageTokens: 0.000008,
            completionImageTokens: 0.00003,
        },
    },
    "flux-1-schnell": {
        brand: "Black Forest Labs",
        provider: "runpod",
        model: "flux-schnell",
        aliases: ["flux", "flux-schnell"],
        description: "Image generation from text prompts.",
        category: "image",
        inputModalities: ["text"],
        outputModalities: ["image"],
        introducedAt: 1753999200000,
        cost: {
            completionImageTokens: 0.001,
        },
    },
    "z-image-turbo": {
        brand: "Alibaba",
        provider: "runpod",
        model: "z-image-turbo",
        aliases: ["zimage", "z-image"],
        description: "Image generation from text prompts.",
        category: "image",
        inputModalities: ["text"],
        outputModalities: ["image"],
        introducedAt: 1753999200000,
        cost: {
            completionImageTokens: 0.002,
        },
    },
    "veo-3.1-fast": {
        brand: "Google",
        provider: "google",
        model: "veo-3.1-fast",
        version: "preview",
        aliases: ["veo", "video"],
        description: "Video generation from text and image input.",
        category: "video",
        profile: "fast",
        inputModalities: ["text", "image"],
        outputModalities: ["video"],
        paidOnly: true,
        introducedAt: 1753999200000,
        cost: {
            completionVideoSeconds: 0.15,
        },
    },
    "seedance-lite": {
        brand: "ByteDance",
        provider: "bytedance",
        model: "seedance-lite",
        aliases: ["seedance"],
        description: "Video generation from text and image input.",
        category: "video",
        profile: "fast",
        inputModalities: ["text", "image"],
        outputModalities: ["video"],
        paidOnly: true,
        introducedAt: 1753999200000,
        cost: {
            completionVideoTokens: 0.0000018,
        },
        price: {
            completionVideoTokens: 0.0000027,
        },
    },
    "seedance-pro": {
        brand: "ByteDance",
        provider: "bytedance",
        model: "seedance-pro-fast",
        aliases: [],
        description: "Video generation from text and image input.",
        category: "video",
        profile: "pro",
        inputModalities: ["text", "image"],
        outputModalities: ["video"],
        paidOnly: true,
        introducedAt: 1753999200000,
        cost: {
            completionVideoTokens: 0.000001,
        },
        price: {
            completionVideoTokens: 0.0000015,
        },
    },
    "wan-2.6": {
        brand: "Alibaba",
        provider: "alibaba",
        model: "wan-2.6",
        aliases: ["wan", "wan2.6", "wan-i2v"],
        description: "Video generation from text and image input.",
        category: "video",
        inputModalities: ["text", "image"],
        outputModalities: ["video"],
        paidOnly: true,
        introducedAt: 1771545600000,
        cost: {
            completionAudioSeconds: 0.05,
            completionVideoSeconds: 0.05,
        },
        price: {
            completionAudioSeconds: 0.075,
            completionVideoSeconds: 0.075,
        },
    },
    "wan-2.2": {
        brand: "Alibaba",
        provider: "alibaba",
        model: "wan-2.2",
        aliases: ["wan-fast", "wan2.2"],
        description: "Video generation from text and image input.",
        category: "video",
        profile: "fast",
        inputModalities: ["text", "image"],
        outputModalities: ["video"],
        paidOnly: true,
        introducedAt: 1774224000000,
        cost: {
            completionAudioSeconds: 0.01,
            completionVideoSeconds: 0.01,
        },
        price: {
            completionAudioSeconds: 0.015,
            completionVideoSeconds: 0.015,
        },
    },
    "wan-2.7-image": {
        brand: "Alibaba",
        provider: "alibaba",
        model: "wan-2.7-image",
        aliases: ["wan-image", "wan2.7-image", "wan-img"],
        description: "Image generation and editing from text and image input.",
        category: "image",
        inputModalities: ["text", "image"],
        outputModalities: ["image"],
        introducedAt: 1775088000000,
        cost: {
            completionImageTokens: 0.035,
        },
        price: {
            completionImageTokens: 0.0525,
        },
    },
    "wan-2.7-image-pro": {
        brand: "Alibaba",
        provider: "alibaba",
        model: "wan-2.7-image-pro",
        aliases: ["wan-image-pro", "wan2.7-image-pro", "wan-img-pro"],
        description: "Image generation and editing from text and image input.",
        category: "image",
        profile: "pro",
        inputModalities: ["text", "image"],
        outputModalities: ["image"],
        paidOnly: true,
        introducedAt: 1775088000000,
        cost: {
            completionImageTokens: 0.075,
        },
        price: {
            completionImageTokens: 0.1125,
        },
    },
    "qwen-image-plus": {
        brand: "Qwen",
        provider: "alibaba",
        model: "qwen-image-plus",
        aliases: [
            "qwen-image",
            "qwen-image-2512",
            "qwen-image-edit",
            "qwen-image-edit-plus",
        ],
        description: "Image generation and editing from text and image input.",
        category: "image",
        inputModalities: ["text", "image"],
        outputModalities: ["image"],
        introducedAt: 1774137600000,
        cost: {
            completionImageTokens: 0.03,
        },
        price: {
            completionImageTokens: 0.045,
        },
    },
    "grok-imagine": {
        brand: "xAI",
        provider: "xai",
        model: "grok-imagine",
        aliases: ["grok-imagine-image"],
        description: "Image generation from text prompts.",
        category: "image",
        inputModalities: ["text"],
        outputModalities: ["image"],
        paidOnly: true,
        introducedAt: 1774137600000,
        cost: {
            completionImageTokens: 0.02,
        },
        price: {
            completionImageTokens: 0.03,
        },
    },
    "grok-imagine-pro": {
        brand: "xAI",
        provider: "xai",
        model: "grok-imagine-pro",
        aliases: ["grok-aurora", "aurora", "grok-imagine-image-pro"],
        description: "Image generation from text prompts.",
        category: "image",
        profile: "pro",
        inputModalities: ["text"],
        outputModalities: ["image"],
        paidOnly: true,
        introducedAt: 1774137600000,
        cost: {
            completionImageTokens: 0.07,
        },
        price: {
            completionImageTokens: 0.105,
        },
    },
    "grok-video-pro": {
        brand: "xAI",
        provider: "xai",
        model: "grok-video-pro",
        aliases: ["grok-imagine-video"],
        description: "Video generation from text and image input.",
        category: "video",
        profile: "pro",
        inputModalities: ["text", "image"],
        outputModalities: ["video"],
        paidOnly: true,
        introducedAt: 1774137600000,
        cost: {
            completionVideoSeconds: 0.05,
        },
        price: {
            completionVideoSeconds: 0.075,
        },
    },
    "flux-2-klein-4b": {
        brand: "Black Forest Labs",
        provider: "runpod",
        model: "flux.2-klein-4b",
        aliases: ["klein", "flux-klein"],
        description: "Image generation and editing from text and image input.",
        category: "image",
        inputModalities: ["text", "image"],
        outputModalities: ["image"],
        alpha: true,
        introducedAt: 1768953600000,
        cost: {
            completionImageTokens: 0.01,
        },
    },
    "ltx-video-2.3": {
        brand: "Lightricks",
        provider: "lambda",
        model: "ltx-video-2.3",
        aliases: ["ltx-2", "ltx2", "ltx-2.3", "ltxvideo", "ltx-video"],
        description: "Video generation from text prompts.",
        category: "video",
        inputModalities: ["text"],
        outputModalities: ["video"],
        alpha: true,
        introducedAt: 1774224000000,
        cost: {
            completionVideoSeconds: 0.005,
        },
    },
    "pruna-image": {
        brand: "Pruna",
        provider: "pruna",
        model: "p-image",
        aliases: ["p-image", "pruna"],
        description: "Image generation from text prompts.",
        category: "image",
        inputModalities: ["text"],
        outputModalities: ["image"],
        paidOnly: true,
        introducedAt: 1773360000000,
        cost: {
            completionImageTokens: 0.005,
        },
        price: {
            completionImageTokens: 0.0075,
        },
    },
    "pruna-image-edit": {
        brand: "Pruna",
        provider: "pruna",
        model: "p-image-edit",
        aliases: ["p-image-edit", "pruna-edit"],
        description: "Image generation and editing from text and image input.",
        category: "image",
        inputModalities: ["text", "image"],
        outputModalities: ["image"],
        paidOnly: true,
        introducedAt: 1773360000000,
        cost: {
            completionImageTokens: 0.01,
        },
        price: {
            completionImageTokens: 0.015,
        },
    },
    "pruna-video": {
        brand: "Pruna",
        provider: "pruna",
        model: "p-video",
        aliases: ["p-video"],
        description: "Video generation from text and image input.",
        category: "video",
        inputModalities: ["text", "image"],
        outputModalities: ["video"],
        paidOnly: true,
        introducedAt: 1773360000000,
        cost: {
            completionVideoSeconds: 0.024,
        },
        price: {
            completionVideoSeconds: 0.036,
        },
    },
    "nova-canvas": {
        brand: "Amazon",
        provider: "aws",
        model: "nova-canvas",
        aliases: ["amazon-nova-canvas"],
        description: "Image generation and editing from text and image input.",
        category: "image",
        inputModalities: ["text", "image"],
        outputModalities: ["image"],
        paidOnly: true,
        introducedAt: 1753999200000,
        cost: {
            completionImageTokens: 0.04,
        },
    },
    "nova-reel": {
        brand: "Amazon",
        provider: "aws",
        model: "nova-reel",
        aliases: ["amazon-nova-reel"],
        description: "Video generation from text and image input.",
        category: "video",
        inputModalities: ["text", "image"],
        outputModalities: ["video"],
        introducedAt: 1753999200000,
        cost: {
            completionVideoSeconds: 0.08,
        },
    },
} as const satisfies Record<string, ModelDefinition>;
