import type {
    ModelRegistry,
    ServiceRegistry,
    UsageConversionDefinition,
} from "./registry";
import { PRICING_START_DATE, perMillion } from "./price-helpers";

export const DEFAULT_TEXT_MODEL = "openai" as const;

export const TEXT_COSTS = {
    "gpt-5-mini-2025-08-07": [
        {
            date: PRICING_START_DATE,
            provider: "azure-openai",
            promptTextTokens: perMillion(0.25),
            promptCachedTokens: perMillion(0.025),
            completionTextTokens: perMillion(2.0),
        },
    ],
    "gpt-5-nano-2025-08-07": [
        {
            date: PRICING_START_DATE,
            provider: "azure-openai",
            promptTextTokens: perMillion(0.05),
            promptCachedTokens: perMillion(0.005),
            completionTextTokens: perMillion(0.4),
        },
    ],
    "gpt-5-chat-latest": [
        {
            date: PRICING_START_DATE,
            provider: "azure-openai",
            promptTextTokens: perMillion(1.25),
            promptCachedTokens: perMillion(0.13),
            completionTextTokens: perMillion(10.0),
        },
    ],
    "gpt-4.1-nano-2025-04-14": [
        {
            date: PRICING_START_DATE,
            provider: "azure-openai",
            promptTextTokens: perMillion(0.11),
            promptCachedTokens: perMillion(0.03),
            completionTextTokens: perMillion(0.44),
        },
    ],
    "gpt-4.1-2025-04-14": [
        {
            date: PRICING_START_DATE,
            provider: "azure-openai",
            promptTextTokens: perMillion(2.2),
            promptCachedTokens: perMillion(0.55),
            completionTextTokens: perMillion(8.8),
        },
    ],
    "gpt-4o-mini-audio-preview-2024-12-17": [
        {
            date: PRICING_START_DATE,
            provider: "azure-openai",
            promptTextTokens: perMillion(0.165),
            completionTextTokens: perMillion(0.66),
            promptAudioTokens: perMillion(11.0),
            completionAudioTokens: perMillion(22.0),
        },
    ],
    "qwen2.5-coder-32b-instruct": [
        {
            date: PRICING_START_DATE,
            provider: "scaleway",
            promptTextTokens: perMillion(0.9),
            completionTextTokens: perMillion(0.9),
        },
    ],
    "mistral-small-3.1-24b-instruct-2503": [
        {
            date: PRICING_START_DATE,
            provider: "scaleway",
            promptTextTokens: perMillion(0.15),
            completionTextTokens: perMillion(0.35),
        },
    ],
    "mistral-small-3.2-24b-instruct-2506": [
        {
            date: PRICING_START_DATE,
            provider: "scaleway",
            promptTextTokens: perMillion(0.15),
            completionTextTokens: perMillion(0.35),
        },
    ],
    "mistral-nemo-instruct-2407": [
        {
            date: PRICING_START_DATE,
            provider: "scaleway",
            promptTextTokens: perMillion(0.14),
            completionTextTokens: perMillion(0.42),
        },
    ],
    "us.meta.llama3-1-8b-instruct-v1:0": [
        {
            date: PRICING_START_DATE,
            provider: "aws-bedrock",
            promptTextTokens: perMillion(0.22),
            completionTextTokens: perMillion(0.22),
        },
    ],
    "us.anthropic.claude-3-5-haiku-20241022-v1:0": [
        {
            date: PRICING_START_DATE,
            provider: "aws-bedrock",
            promptTextTokens: perMillion(0.8),
            completionTextTokens: perMillion(4.0),
        },
    ],
    "openai/o4-mini": [
        {
            date: PRICING_START_DATE,
            provider: "api-navy",
            promptTextTokens: perMillion(1.21),
            promptCachedTokens: perMillion(0.31),
            completionTextTokens: perMillion(4.84),
        },
    ],
    "gemini-2.5-flash-lite": [
        {
            date: PRICING_START_DATE,
            provider: "vertex-ai",
            promptTextTokens: perMillion(0.1),
            promptCachedTokens: perMillion(0.01),
            completionTextTokens: perMillion(0.4),
        },
    ],
    "myceli-deepseek-v3.1": [
        {
            date: PRICING_START_DATE,
            provider: "azure",
            promptTextTokens: perMillion(1.25),
            completionTextTokens: perMillion(5.0),
        },
    ],
    "us.anthropic.claude-haiku-4-5-20251001-v1:0": [
        {
            date: PRICING_START_DATE,
            provider: "aws-bedrock",
            promptTextTokens: perMillion(1.0),
            completionTextTokens: perMillion(5.0),
        },
    ],
    "global.anthropic.claude-haiku-4-5-20251001-v1:0": [
        {
            date: PRICING_START_DATE,
            provider: "aws-bedrock",
            promptTextTokens: perMillion(1.0),
            completionTextTokens: perMillion(5.0),
        },
    ],
    "us.anthropic.claude-sonnet-4-5-20250929-v1:0": [
        {
            date: PRICING_START_DATE,
            provider: "aws-bedrock",
            promptTextTokens: perMillion(3.0),
            completionTextTokens: perMillion(15.0),
        },
    ],
    "myceli-grok-4-fast": [
        {
            date: PRICING_START_DATE,
            provider: "azure",
            promptTextTokens: perMillion(0.2),
            completionTextTokens: perMillion(0.5),
        },
    ],
    "sonar": [
        {
            date: PRICING_START_DATE,
            provider: "perplexity",
            promptTextTokens: perMillion(1.0),
            completionTextTokens: perMillion(1.0),
        },
    ],
    "sonar-reasoning": [
        {
            date: PRICING_START_DATE,
            provider: "perplexity",
            promptTextTokens: perMillion(1.0),
            completionTextTokens: perMillion(5.0),
        },
    ],
} as const satisfies ModelRegistry;
export const TEXT_SERVICES = {
    "openai": {
        aliases: ["gpt-5-mini"],
        modelId: "gpt-5-mini-2025-08-07",
        description: "OpenAI GPT-5 Nano",
        input_modalities: ["text", "image"],
        output_modalities: ["text"],
        tools: true,
        vision: true,
        community: false,
    },
    "openai-fast": {
        aliases: ["gpt-5-nano"],
        modelId: "gpt-5-nano-2025-08-07",
        description: "OpenAI GPT-5 Nano",
        input_modalities: ["text", "image"],
        output_modalities: ["text"],
        tools: true,
        vision: true,
        community: false,
    },
    "openai-large": {
        aliases: ["gpt-5-chat"],
        modelId: "gpt-5-chat-latest",
        description: "OpenAI GPT-4.1",
        input_modalities: ["text", "image"],
        output_modalities: ["text"],
        tools: true,
        vision: true,
        community: false,
    },
    "qwen-coder": {
        aliases: ["qwen2.5-coder-32b-instruct"],
        modelId: "qwen2.5-coder-32b-instruct",
        description: "Qwen 2.5 Coder 32B",
        input_modalities: ["text"],
        output_modalities: ["text"],
        tools: true,
        community: false,
    },
    "mistral": {
        aliases: ["mistral-small"],
        modelId: "mistral-small-3.2-24b-instruct-2506",
        description: "Mistral Small 3.2 24B",
        input_modalities: ["text"],
        output_modalities: ["text"],
        tools: true,
        community: false,
    },
    "mistral-fast": {
        aliases: ["llama-3.1-8b", "llama-fast"],
        modelId: "us.meta.llama3-1-8b-instruct-v1:0",
        description: "Llama 3.1 8B (Fast)",
        input_modalities: ["text"],
        output_modalities: ["text"],
        tools: true,
        community: false,
    },
    // Temporarily disabled
    // "naughty": {
    //     aliases: ["mistral-naughty", "mistral-romance", "mistral-nemo-instruct-2407-romance", "mistral-roblox"],
    //     modelId: "mistral-nemo-instruct-2407",
    //     provider: "scaleway",
    // },
    "openai-audio": {
        aliases: ["gpt-4o-mini-audio-preview"],
        modelId: "gpt-4o-mini-audio-preview-2024-12-17",
        description: "OpenAI GPT-4o Mini Audio Preview",
        voices: [
            "alloy",
            "echo",
            "fable",
            "onyx",
            "nova",
            "shimmer",
            "coral",
            "verse",
            "ballad",
            "ash",
            "sage",
            "amuch",
            "dan",
        ],
        input_modalities: ["text", "image", "audio"],
        output_modalities: ["audio", "text"],
        tools: true,
        audio: true,
        vision: true,
        community: false,
    },
    "openai-reasoning": {
        aliases: ["o4-mini"],
        modelId: "openai/o4-mini",
        description: "OpenAI o4 Mini",
        input_modalities: ["text", "image"],
        output_modalities: ["text"],
        tools: true,
        reasoning: true,
        vision: true,
        community: false,
    },
    "gemini": {
        aliases: ["gemini-2.5-flash-lite"],
        modelId: "gemini-2.5-flash-lite",
        description: "Gemini 2.5 Flash Lite",
        input_modalities: ["text", "image"],
        output_modalities: ["text"],
        tools: true,
        vision: true,
        community: false,
    },
    "deepseek": {
        aliases: [
            "deepseek-v3",
            "deepseek-v3.1",
            "deepseek-reasoning",
            "deepseek-r1-0528",
        ],
        modelId: "myceli-deepseek-v3.1",
        description: "DeepSeek V3.1",
        input_modalities: ["text"],
        output_modalities: ["text"],
        tools: true,
        reasoning: true,
        community: false,
    },
    "grok": {
        aliases: ["grok-fast", "grok-4", "grok-4-fast"],
        modelId: "myceli-grok-4-fast",
        description: "Grok 4 Fast",
        input_modalities: ["text"],
        output_modalities: ["text"],
        tools: true,
        community: false,
    },
    "gemini-search": {
        aliases: ["searchgpt", "geminisearch"],
        modelId: "gemini-2.5-flash-lite",
        description: "Gemini 2.5 Flash Lite with Google Search",
        input_modalities: ["text", "image"],
        output_modalities: ["text"],
        tools: true,
        vision: true,
        community: false,
    },
    "chickytutor": {
        aliases: [],
        modelId: "us.anthropic.claude-3-5-haiku-20241022-v1:0",
        description: "ChickyTutor AI Language Tutor - (chickytutor.com)",
        input_modalities: ["text"],
        output_modalities: ["text"],
        tools: true,
        community: true,
    },
    "midijourney": {
        aliases: [],
        modelId: "gpt-4.1-2025-04-14",
        description: "MIDIjourney",
        input_modalities: ["text"],
        output_modalities: ["text"],
        tools: true,
        community: true,
    },
    // Temporarily disabled
    // "evil": {
    //     aliases: [],
    //     modelId: "mistral-small-3.1-24b-instruct-2503",
    //     provider: "scaleway",
    // },
    "claude": {
        aliases: ["claudyclaude"],
        modelId: "us.anthropic.claude-haiku-4-5-20251001-v1:0",
        description: "Claude Haiku 4.5",
        input_modalities: ["text", "image"],
        output_modalities: ["text"],
        tools: true,
        vision: true,
    },
    "claude-large": {
        aliases: ["sonnet", "claude-4.5", "claude-sonnet-4.5", "claude-sonnet"],
        modelId: "us.anthropic.claude-sonnet-4-5-20250929-v1:0",
        description: "Claude Sonnet 4.5",
        input_modalities: ["text", "image"],
        output_modalities: ["text"],
        tools: true,
        vision: true,
        community: false,
    },
    "perplexity-fast": {
        aliases: ["sonar"],
        modelId: "sonar",
        description: "Perplexity Sonar - Fast & Affordable",
        input_modalities: ["text"],
        output_modalities: ["text"],
        tools: true,
        community: false,
    },
    "perplexity-reasoning": {
        aliases: ["sonar-reasoning"],
        modelId: "sonar-reasoning",
        description: "Perplexity Sonar Reasoning - Advanced Reasoning",
        input_modalities: ["text"],
        output_modalities: ["text"],
        tools: true,
        reasoning: true,
        community: false,
    },
} as const satisfies ServiceRegistry<typeof TEXT_COSTS>;
