// Reviewed 2026-09-10 against Gen transforms, gateway 639928b0 and provider docs.
// Static /v1/chat/completions metadata, not a request filter or provider defaults.
// Routes choose their own sets: a fallback need not honor its primary's controls.
// https://learn.microsoft.com/en-us/azure/foundry/openai/how-to/reasoning
// https://docs.aws.amazon.com/bedrock/latest/userguide/model-parameters.html
// https://openrouter.ai/docs/api-reference/parameters
// https://docs.fireworks.ai/api-reference/post-chatcompletions
// https://deepinfra.com/docs/openai_api
// https://www.alibabacloud.com/help/en/model-studio/qwen-api-reference/
// https://oai.endpoints.kepler.ai.cloud.ovh.net/doc/gpt-oss-20b/openapi.json

const CHAT = ["max_tokens", "max_completion_tokens", "stream"];
const SAMPLING = ["temperature", "top_p"];
const TOOLS = ["tools", "tool_choice"];
const PENALTIES = ["frequency_penalty", "presence_penalty"];
const LOGPROBS = ["logprobs", "top_logprobs"];
const OPENROUTER_REASONING = ["reasoning", "include_reasoning"];
const TOOL_CHAT = [...CHAT, ...TOOLS, "response_format"];
const SAMPLED_CHAT = [...TOOL_CHAT, ...SAMPLING, "stop"];
const EXTENDED_CHAT = [
    ...SAMPLED_CHAT,
    ...PENALTIES,
    ...LOGPROBS,
    "seed",
    "top_k",
];

export const CHAT_PARAMETERS = {
    // Gen intentionally removes GPT sampling. Azure mini has no parallel-tools flag.
    azureGpt: [
        ...TOOL_CHAT,
        "reasoning_effort",
        "parallel_tool_calls",
        "verbosity",
    ],
    azureGptMini: [...TOOL_CHAT, "reasoning_effort", "verbosity"],
    azureGpt54: [
        ...TOOL_CHAT,
        ...LOGPROBS,
        "reasoning_effort",
        "parallel_tool_calls",
        "verbosity",
    ],
    // Chat-to-Responses conversion does not forward top-level verbosity.
    azureResponses: [...TOOL_CHAT, "reasoning_effort", "parallel_tool_calls"],
    ovhGptOss: [
        ...SAMPLED_CHAT,
        ...PENALTIES,
        ...LOGPROBS,
        "seed",
        "reasoning_effort",
        "parallel_tool_calls",
        "logit_bias",
        "n",
    ],
    // Requires audio input or output; cap and mini streaming verified live.
    azureAudio: [...CHAT, "tools", "audio", "modalities"],
    azureGrokReasoning: [
        ...CHAT,
        "reasoning_effort",
        "response_format",
        "tools",
        "parallel_tool_calls",
    ],
    openRouterGrok420: [
        ...TOOL_CHAT,
        ...SAMPLING,
        ...LOGPROBS,
        ...OPENROUTER_REASONING,
        "seed",
        "parallel_tool_calls",
    ],
    openRouterGrok43: [
        ...TOOL_CHAT,
        ...SAMPLING,
        ...LOGPROBS,
        ...OPENROUTER_REASONING,
        "seed",
        "parallel_tool_calls",
        "reasoning_effort",
    ],
    azureGrok46: [
        ...CHAT,
        ...SAMPLING,
        "seed",
        "reasoning_effort",
        "response_format",
        "tools",
        "parallel_tool_calls",
    ],
    // Haiku 4.5 / Sonnet & Opus 4.6: sampling only without thinking; JSON schema only.
    bedrockClaudeSampling: [...SAMPLED_CHAT, "top_k", "reasoning_effort"],
    bedrockClaudeNoSampling: [...CHAT, ...TOOLS, "reasoning_effort", "stop"],
    // Fable 5.1 rejects forced tool choice; auto alone is not an adjustable control.
    bedrockFable51: [...CHAT, "reasoning_effort", "tools", "stop"],
    openRouterHaiku: [
        ...CHAT,
        ...SAMPLING,
        ...TOOLS,
        ...OPENROUTER_REASONING,
        "top_k",
        "stop",
    ],
    openRouterOpus: [
        ...TOOL_CHAT,
        ...OPENROUTER_REASONING,
        "stop",
        "verbosity",
    ],
    gemini25: [...SAMPLED_CHAT, ...OPENROUTER_REASONING, "seed"],
    gemini3: [
        ...SAMPLED_CHAT,
        ...OPENROUTER_REASONING,
        "seed",
        "reasoning_effort",
    ],
    gemini3AiStudio: [
        ...TOOL_CHAT,
        ...SAMPLING,
        ...OPENROUTER_REASONING,
        "seed",
        "reasoning_effort",
    ],
    // Newer Gemini ignores sampling. The AI Studio routes do not declare stop.
    gemini35: [
        ...TOOL_CHAT,
        ...OPENROUTER_REASONING,
        "seed",
        "reasoning_effort",
        "stop",
    ],
    gemini35AiStudio: [
        ...TOOL_CHAT,
        ...OPENROUTER_REASONING,
        "seed",
        "reasoning_effort",
    ],
    vertexGeminiSearch: [...SAMPLED_CHAT, "seed", "reasoning_effort"],
    nova: [...CHAT, ...SAMPLING, ...TOOLS, "stop"],
    mercury: [...TOOL_CHAT, ...OPENROUTER_REASONING, "temperature", "stop"],
    mercury25: [
        ...TOOL_CHAT,
        ...OPENROUTER_REASONING,
        "temperature",
        "reasoning_effort",
        "stop",
    ],
    azureOpenModels: [...CHAT, ...SAMPLING, ...PENALTIES, "seed", "stop"],
    // Exact OVH model OpenAPI confirms these; top_k is rejected, not honored.
    ovhQwenCoder: [...TOOL_CHAT, ...SAMPLING, ...LOGPROBS, "seed"],
    openRouterMistralSmall32: [
        ...SAMPLED_CHAT,
        ...PENALTIES,
        "top_k",
        "min_p",
        "repetition_penalty",
        "seed",
        "logit_bias",
    ],
    deepinfra: [...EXTENDED_CHAT, "n"],
    mistralSmall4: [
        ...SAMPLED_CHAT,
        ...PENALTIES,
        ...OPENROUTER_REASONING,
        "seed",
        "reasoning_effort",
    ],
    fireworksReasoning: [
        ...EXTENDED_CHAT,
        "reasoning_effort",
        "parallel_tool_calls",
        "logit_bias",
        "n",
        "prediction",
    ],
    deepinfraReasoning: [...EXTENDED_CHAT, "reasoning_effort", "n"],
    openRouterGemma: [
        ...EXTENDED_CHAT,
        ...OPENROUTER_REASONING,
        "repetition_penalty",
    ],
    sonar: [
        ...CHAT,
        ...SAMPLING,
        "response_format",
        "web_search_options",
        "search_domain_filter",
        "search_recency_filter",
    ],
    openRouterSonar: [
        ...CHAT,
        ...SAMPLING,
        ...PENALTIES,
        "top_k",
        "web_search_options",
    ],
    openRouterSonarReasoning: [
        ...CHAT,
        ...SAMPLING,
        ...PENALTIES,
        ...OPENROUTER_REASONING,
        "top_k",
        "web_search_options",
    ],
    laguna: [...CHAT, ...TOOLS, ...OPENROUTER_REASONING, "temperature"],
    longcat: [
        ...CHAT,
        ...SAMPLING,
        ...TOOLS,
        ...PENALTIES,
        ...OPENROUTER_REASONING,
        "top_k",
        "min_p",
        "repetition_penalty",
        "seed",
        "stop",
        "logit_bias",
    ],
    inklingSmall: [
        ...CHAT,
        ...SAMPLING,
        ...TOOLS,
        ...PENALTIES,
        ...LOGPROBS,
        ...OPENROUTER_REASONING,
        "top_k",
        "min_p",
        "repetition_penalty",
        "reasoning_effort",
        "stop",
        "logit_bias",
    ],
    openRouterNemotron: [
        ...CHAT,
        ...SAMPLING,
        ...PENALTIES,
        ...LOGPROBS,
        ...OPENROUTER_REASONING,
        "top_k",
        "repetition_penalty",
        "seed",
        "response_format",
        "stop",
    ],
    mimo: [...SAMPLED_CHAT, ...PENALTIES, ...OPENROUTER_REASONING],
    openRouterGlm53: [
        ...SAMPLED_CHAT,
        ...PENALTIES,
        ...OPENROUTER_REASONING,
        "top_k",
        "min_p",
        "repetition_penalty",
        "seed",
        "reasoning_effort",
    ],
    openRouterLlamaScout: [...SAMPLED_CHAT, ...PENALTIES, "top_k", "seed"],
    openRouterMinimax27: [
        ...SAMPLED_CHAT,
        ...PENALTIES,
        ...OPENROUTER_REASONING,
        "top_k",
        "min_p",
        "repetition_penalty",
        "seed",
        "logit_bias",
    ],
    openRouterMuseGlimmer: [
        ...SAMPLED_CHAT,
        ...PENALTIES,
        ...OPENROUTER_REASONING,
        "top_k",
        "min_p",
        "repetition_penalty",
        "seed",
        "reasoning_effort",
        "logit_bias",
    ],
    openRouterDeepseekV41Flash: [
        ...CHAT,
        ...SAMPLING,
        ...TOOLS,
        ...PENALTIES,
        ...LOGPROBS,
        ...OPENROUTER_REASONING,
        "logit_bias",
        "min_p",
        "repetition_penalty",
        "seed",
        "stop",
        "structured_outputs",
        "top_k",
    ],
    museSpark: [...CHAT, "temperature", "tools"],
    openRouterMistralLarge: [...SAMPLED_CHAT, ...PENALTIES, "seed"],
    // OpenRouter azure/openai tags only (2026-09-12); azure/swedencentral is
    // excluded via provider.order + allow_fallbacks:false so pricing stays
    // fixed. Neither pinned tag reports max_completion_tokens as supported.
    openRouterGpt4oMini: [
        "max_tokens",
        "stream",
        ...TOOLS,
        "response_format",
        "structured_outputs",
        ...SAMPLING,
        "stop",
        ...PENALTIES,
        ...LOGPROBS,
        "seed",
        "logit_bias",
        "prediction",
        "web_search_options",
    ],
    qwenCoderNext: [...EXTENDED_CHAT, "repetition_penalty", "logit_bias"],
    openRouterQwenCoderNext: [...SAMPLED_CHAT, "presence_penalty"],
    qwen37: [...EXTENDED_CHAT, ...OPENROUTER_REASONING],
    qwen38: [
        ...SAMPLED_CHAT,
        ...PENALTIES,
        ...OPENROUTER_REASONING,
        "top_k",
        "repetition_penalty",
        "seed",
        "reasoning_effort",
    ],
    qwen38Akash: [
        ...EXTENDED_CHAT,
        ...OPENROUTER_REASONING,
        "repetition_penalty",
        "reasoning_effort",
    ],
    qwen38Max: [...EXTENDED_CHAT, ...OPENROUTER_REASONING, "reasoning_effort"],
    alibabaQwenReasoning: [
        ...SAMPLED_CHAT,
        "top_k",
        "presence_penalty",
        "repetition_penalty",
        "seed",
        "reasoning_effort",
        "parallel_tool_calls",
    ],
    openRouterQwen37Flash: [
        ...TOOL_CHAT,
        ...SAMPLING,
        ...LOGPROBS,
        ...OPENROUTER_REASONING,
        "presence_penalty",
        "seed",
    ],
    alibabaQwen: [
        ...SAMPLED_CHAT,
        "top_k",
        "presence_penalty",
        "repetition_penalty",
        "seed",
        "parallel_tool_calls",
    ],
    qwenVl: [...EXTENDED_CHAT],
    alibabaQwenVl: [
        ...CHAT,
        ...SAMPLING,
        ...TOOLS,
        "top_k",
        "presence_penalty",
        "repetition_penalty",
        "seed",
        "parallel_tool_calls",
        "stop",
    ],
    openRouterQwenVl: [
        ...CHAT,
        ...SAMPLING,
        ...TOOLS,
        ...PENALTIES,
        ...LOGPROBS,
        ...OPENROUTER_REASONING,
        "top_k",
        "repetition_penalty",
        "seed",
        "stop",
    ],
    step35: [
        ...CHAT,
        ...SAMPLING,
        ...TOOLS,
        ...OPENROUTER_REASONING,
        "top_k",
        "frequency_penalty",
    ],
    qwenGuard: [...CHAT, ...SAMPLING, ...LOGPROBS, "seed"],
} satisfies Record<string, string[]>;
