version: 0.5

processes:

  text:
    working_dir: "text.pollinations.ai"
    command: npm run dev
    availability:
      restart: "always"

  image:
    working_dir: "image.pollinations.ai"
    command: npm run dev
    availability:
      restart: "always"

  enter:
    working_dir: "enter.pollinations.ai"
    command: "CLOUDFLARE_ENV=local npm run dev" 
    availability:
      restart: "always"
    environment:
      - "IMAGE_SERVICE_URL=http://localhost:16384"
      - "TEXT_SERVICE_URL=http://localhost:16385"
