# https://taskfile.dev

version: '3'

concurrency: 4

tasks:

  install-enter:
    desc: Install dependencies enter.pollinations.ai
    cmds:
      - cd enter.pollinations.ai && npm install

  install-text:
    desc: Install dependencies text.pollinations.ai
    cmds:
      - cd text.pollinations.ai && npm install

  install-image:
    desc: Install dependencies image.pollinations.ai
    cmds:
      - cd image.pollinations.ai && npm install

  install:
    desc: Install dependencies for enter, text and image services
    deps: [install-enter, install-text, install-image]


  test-enter:
    desc: Run tests for enter.pollinations.ai
    cmds:
      - cd enter.pollinations.ai && npm run test

  test-text:
    desc: Run tests for text.pollinations.ai
    cmds:
      - cd text.pollinations.ai && npm run test

  test-image:
    desc: Run tests for image.pollinations.ai
    cmds:
      - cd image.pollinations.ai && npm run test

  test:
    desc: Run tests for enter, text and image services
    deps: [test-enter, test-text, test-image]


  dev:
    desc: Starts a dev server for enter, text and image services
    cmds:
      - process-compose

