import type { ReactNode } from "react";

/**
 * The design's own signature, taken from the mockup rather than approximated.
 *
 * packages/ui's Button is a rounded-full pill that brightens on hover — right
 * for the dashboard, wrong here. This design uses a 12px rectangle with a hard
 * offset shadow that *grows* on hover, so the control appears to lift off the
 * page. Colours still come from `--polli-*`; only the geometry is local.
 */
const ACTION_BASE =
    "inline-flex items-center justify-center rounded-xl px-7 py-3.5 text-base font-semibold " +
    "transition-shadow duration-150 motion-reduce:transition-none";

const ACTION_TONE = {
    /** Primary: amber fill. */
    accent:
        "bg-theme-bg-active text-theme-text-strong " +
        "shadow-[3px_3px_0_rgba(17,5,24,0.22)] hover:shadow-[5px_5px_0_rgba(17,5,24,0.28)]",
    /** Secondary: white fill, lighter shadow. */
    plain:
        "bg-surface-opaque text-theme-text-strong " +
        "shadow-[3px_3px_0_rgba(17,5,24,0.12)] hover:shadow-[5px_5px_0_rgba(17,5,24,0.18)]",
    /** For use on the amber CTA panel, where white and amber both disappear. */
    dark:
        "bg-brand-dark text-theme-bg-active " +
        "shadow-[3px_3px_0_rgba(17,5,24,0.25)] hover:shadow-[5px_5px_0_rgba(17,5,24,0.32)]",
} as const;

export function ActionButton({
    href,
    tone = "accent",
    className = "",
    children,
}: {
    href: string;
    tone?: keyof typeof ACTION_TONE;
    className?: string;
    children: ReactNode;
}) {
    return (
        <a
            href={href}
            className={`${ACTION_BASE} ${ACTION_TONE[tone]} ${className}`}
        >
            {children}
        </a>
    );
}

/**
 * Cards throw a hard amber shadow on hover — the same lift as the buttons,
 * which is what makes the page feel responsive rather than static.
 */
export const HOVER_LIFT =
    "transition-shadow duration-150 hover:shadow-[4px_4px_0_var(--polli-color-bg-active)] motion-reduce:transition-none";

/**
 * Terminal panel: dark, elevated, with three little squares and the filename
 * in the pixel face. The squares are 2px-radius, not circles — a small thing
 * that keeps it from looking like a generic macOS window.
 */
export function CodeBlock({
    filename,
    children,
}: {
    filename: string;
    children: ReactNode;
}) {
    return (
        <div className="dark flex flex-col overflow-hidden rounded-2xl bg-brand-dark shadow-[0_12px_26px_-12px_rgba(17,5,24,0.45)]">
            {/* Tokens, not `white` — app.css starts with `--color-*: initial`,
                so bg-white/6 silently renders nothing. Inside `dark` these
                resolve to their on-dark values. */}
            <div className="flex items-center gap-2 bg-theme-bg-subtle px-4 py-3">
                <span className="size-2 rounded-[2px] bg-theme-bg-active" />
                <span className="size-2 rounded-[2px] bg-theme-text-muted/50" />
                <span className="size-2 rounded-[2px] bg-theme-text-muted/50" />
                <span className="ml-1 font-pixel text-xs text-theme-text-muted">
                    {filename}
                </span>
            </div>
            <pre className="overflow-x-auto px-4 py-3 text-[11.5px] leading-relaxed whitespace-pre-wrap text-theme-text-base">
                <code>{children}</code>
            </pre>
        </div>
    );
}

/**
 * Placeholder artwork, generated by the API the site is selling. The mockup
 * used the same trick — pixel-art thumbnails at a fixed seed so they're
 * stable between loads.
 */
export function appArtwork(prompt: string, seed: number): string {
    return `https://image.pollinations.ai/prompt/${encodeURIComponent(
        `${prompt}, crisp pixels, flat`,
    )}?width=420&height=225&nologo=true&seed=${seed}`;
}
