import { Link } from "@tanstack/react-router";
import { useMemo } from "react";
import { isBuzz, sortApps, useAppDirectory } from "../../data/publicStats";
import { ArrowLink, Card, CardGrid, SectionHeader } from "../site/kit";

/**
 * Three, with artwork — the mockup's proportion. Six text-only cards read as
 * another list; three with images read as a shelf, and they're the only
 * pictures on the page.
 *
 * The thumbnails are generated by the API the site is selling, at fixed seeds
 * so they don't change between loads. Placeholders until apps carry their own
 * screenshots.
 */
const ARTWORK = [
    "pixel art playful control room with knobs and screens, honey yellow cream palette",
    "pixel art chat workspace window with speech bubbles, lavender cream palette",
    "pixel art arcade cabinet glowing in a dark room, warm amber palette",
];

function artworkUrl(prompt: string, seed: number): string {
    return `https://image.pollinations.ai/prompt/${encodeURIComponent(
        `${prompt}, crisp pixels, flat`,
    )}?width=420&height=225&nologo=true&seed=${seed}`;
}

export function LiveApps() {
    const { data: apps, loading } = useAppDirectory();

    const featured = useMemo(
        () =>
            apps
                .filter((app) => isBuzz(app) && Boolean(app.description))
                .slice()
                .sort(sortApps)
                .slice(0, 3),
        [apps],
    );

    if (!loading && featured.length === 0) return null;

    return (
        <section className="flex flex-col gap-5">
            <SectionHeader
                eyebrow="Built on Pollinations"
                title={
                    loading
                        ? "Apps are already live."
                        : `${apps.length} apps are already live.`
                }
                action={
                    <ArrowLink as={Link} to="/apps">
                        Browse the ecosystem
                    </ArrowLink>
                }
            />
            <CardGrid gap="gap-4">
                {featured.map((app, index) => (
                    <Card
                        key={app.name}
                        as="a"
                        href={app.web_url || app.github_repository_url}
                        className="overflow-hidden rounded-2xl p-0"
                    >
                        <img
                            src={artworkUrl(ARTWORK[index], 101 + index)}
                            alt=""
                            aria-hidden="true"
                            loading="lazy"
                            width={420}
                            height={225}
                            className="block h-[150px] w-full bg-theme-bg-subtle object-cover"
                        />
                        <div className="flex flex-col gap-1.5 px-5 py-4">
                            <span className="font-subheading text-lg text-theme-text-strong">
                                {app.emoji} {app.name}
                            </span>
                            <p className="line-clamp-2 text-sm leading-relaxed text-theme-text-base">
                                {app.description}
                            </p>
                        </div>
                    </Card>
                ))}
            </CardGrid>
        </section>
    );
}
