CREATE TABLE `account` (
	`id` text PRIMARY KEY NOT NULL,
	`account_id` text NOT NULL,
	`provider_id` text NOT NULL,
	`user_id` text NOT NULL,
	`access_token` text,
	`refresh_token` text,
	`id_token` text,
	`access_token_expires_at` integer,
	`refresh_token_expires_at` integer,
	`scope` text,
	`password` text,
	`created_at` integer NOT NULL,
	`updated_at` integer NOT NULL,
	FOREIGN KEY (`user_id`) REFERENCES `user`(`id`) ON UPDATE no action ON DELETE cascade
);
--> statement-breakpoint
CREATE TABLE `apikey` (
	`id` text PRIMARY KEY NOT NULL,
	`name` text,
	`start` text,
	`prefix` text,
	`key` text NOT NULL,
	`user_id` text NOT NULL,
	`refill_interval` integer,
	`refill_amount` integer,
	`last_refill_at` integer,
	`enabled` integer DEFAULT true,
	`rate_limit_enabled` integer DEFAULT true,
	`rate_limit_time_window` integer DEFAULT 86400000,
	`rate_limit_max` integer DEFAULT 10,
	`request_count` integer,
	`remaining` integer,
	`last_request` integer,
	`expires_at` integer,
	`created_at` integer NOT NULL,
	`updated_at` integer NOT NULL,
	`permissions` text,
	`metadata` text,
	FOREIGN KEY (`user_id`) REFERENCES `user`(`id`) ON UPDATE no action ON DELETE cascade
);
--> statement-breakpoint
CREATE TABLE `session` (
	`id` text PRIMARY KEY NOT NULL,
	`expires_at` integer NOT NULL,
	`token` text NOT NULL,
	`created_at` integer NOT NULL,
	`updated_at` integer NOT NULL,
	`ip_address` text,
	`user_agent` text,
	`user_id` text NOT NULL,
	`impersonated_by` text,
	FOREIGN KEY (`user_id`) REFERENCES `user`(`id`) ON UPDATE no action ON DELETE cascade
);
--> statement-breakpoint
CREATE UNIQUE INDEX `session_token_unique` ON `session` (`token`);--> statement-breakpoint
CREATE TABLE `user` (
	`id` text PRIMARY KEY NOT NULL,
	`name` text NOT NULL,
	`email` text NOT NULL,
	`email_verified` integer NOT NULL,
	`image` text,
	`created_at` integer NOT NULL,
	`updated_at` integer NOT NULL,
	`role` text,
	`banned` integer,
	`ban_reason` text,
	`ban_expires` integer
);
--> statement-breakpoint
CREATE UNIQUE INDEX `user_email_unique` ON `user` (`email`);--> statement-breakpoint
CREATE TABLE `verification` (
	`id` text PRIMARY KEY NOT NULL,
	`identifier` text NOT NULL,
	`value` text NOT NULL,
	`expires_at` integer NOT NULL,
	`created_at` integer,
	`updated_at` integer
);
--> statement-breakpoint
CREATE TABLE `event` (
	`id` text PRIMARY KEY NOT NULL,
	`request_id` text NOT NULL,
	`start_time` integer NOT NULL,
	`end_time` integer NOT NULL,
	`response_time` real,
	`response_status` integer,
	`environment` text,
	`event_type` text NOT NULL,
	`event_processing_id` text,
	`event_status` text DEFAULT 'pending' NOT NULL,
	`polar_delivery_attempts` integer DEFAULT 0 NOT NULL,
	`polar_delivered_at` integer,
	`tinybird_delivery_attempts` integer DEFAULT 0 NOT NULL,
	`tinybird_delivered_at` integer,
	`created_at` integer NOT NULL,
	`updated_at` integer NOT NULL,
	`user_id` text,
	`user_tier` text,
	`referrer_domain` text,
	`referrer_url` text,
	`model_requested` text,
	`model_used` text,
	`is_billed_usage` integer NOT NULL,
	`token_price_prompt_text` real NOT NULL,
	`token_price_prompt_cached` real NOT NULL,
	`token_price_prompt_audio` real NOT NULL,
	`token_price_prompt_image` real NOT NULL,
	`token_price_completion_text` real NOT NULL,
	`token_price_completion_reasoning` real NOT NULL,
	`token_price_completion_audio` real NOT NULL,
	`token_price_completion_image` real NOT NULL,
	`token_count_prompt_text` integer NOT NULL,
	`token_count_prompt_audio` integer NOT NULL,
	`token_count_prompt_cached` integer NOT NULL,
	`token_count_prompt_image` integer NOT NULL,
	`token_count_completion_text` integer NOT NULL,
	`token_count_completion_reasoning` integer NOT NULL,
	`token_count_completion_audio` integer NOT NULL,
	`token_count_completion_image` integer NOT NULL,
	`total_cost` real NOT NULL,
	`total_price` real NOT NULL,
	`moderation_hate_severity` text,
	`moderation_self_harm_severity` text,
	`moderation_sexual_severity` text,
	`moderation_violence_severity` text,
	`moderation_protected_material_code_detected` integer,
	`moderation_protected_material_text_detected` integer,
	`cache_hit` integer,
	`cache_type` text,
	`cache_semantic_similarity` real,
	`cache_semantic_threshold` real,
	`cache_key` text
);
