PRAGMA foreign_keys=OFF;--> statement-breakpoint
CREATE TABLE `__new_event` (
	`id` text PRIMARY KEY NOT NULL,
	`event_processing_id` text,
	`event_status` text DEFAULT 'pending' NOT NULL,
	`polar_delivery_attempts` integer DEFAULT 0 NOT NULL,
	`polar_delivered_at` integer,
	`tinybird_delivery_attempts` integer DEFAULT 0 NOT NULL,
	`tinybird_delivered_at` integer,
	`created_at` integer NOT NULL,
	`updated_at` integer NOT NULL,
	`request_id` text NOT NULL,
	`request_path` text,
	`start_time` integer NOT NULL,
	`end_time` integer NOT NULL,
	`response_time` real,
	`response_status` integer,
	`environment` text,
	`event_type` text NOT NULL,
	`user_id` text,
	`user_tier` text,
	`user_github_id` text,
	`user_github_username` text,
	`api_key_id` text,
	`api_key_name` text,
	`api_key_type` text,
	`selected_meter_id` text,
	`selected_meter_slug` text,
	`balances` text,
	`referrer_url` text,
	`referrer_domain` text,
	`model_requested` text,
	`resolved_model_requested` text,
	`model_used` text,
	`model_provider_used` text,
	`is_billed_usage` integer NOT NULL,
	`token_price_prompt_text` real NOT NULL,
	`token_price_prompt_cached` real NOT NULL,
	`token_price_prompt_audio` real NOT NULL,
	`token_price_prompt_image` real NOT NULL,
	`token_price_completion_text` real NOT NULL,
	`token_price_completion_reasoning` real NOT NULL,
	`token_price_completion_audio` real NOT NULL,
	`token_price_completion_image` real NOT NULL,
	`token_price_completion_video_seconds` real DEFAULT 0 NOT NULL,
	`token_price_completion_video_tokens` real DEFAULT 0 NOT NULL,
	`token_count_prompt_text` integer NOT NULL,
	`token_count_prompt_audio` integer NOT NULL,
	`token_count_prompt_cached` integer NOT NULL,
	`token_count_prompt_image` integer NOT NULL,
	`token_count_completion_text` integer NOT NULL,
	`token_count_completion_reasoning` integer NOT NULL,
	`token_count_completion_audio` integer NOT NULL,
	`token_count_completion_image` integer NOT NULL,
	`token_count_completion_video_seconds` integer DEFAULT 0 NOT NULL,
	`token_count_completion_video_tokens` integer DEFAULT 0 NOT NULL,
	`total_cost` real NOT NULL,
	`total_price` real NOT NULL,
	`moderation_prompt_hate_severity` text,
	`moderation_prompt_self_harm_severity` text,
	`moderation_prompt_sexual_severity` text,
	`moderation_prompt_violence_severity` text,
	`moderation_prompt_jailbreak_detected` integer,
	`moderation_completion_hate_severity` text,
	`moderation_completion_self_harm_severity` text,
	`moderation_completion_sexual_severity` text,
	`moderation_completion_violence_severity` text,
	`moderation_completion_protected_material_code_detected` integer,
	`moderation_completion_protected_material_text_detected` integer,
	`cache_hit` integer,
	`cache_type` text,
	`cache_semantic_similarity` real,
	`cache_semantic_threshold` real,
	`cache_key` text,
	`error_response_code` text,
	`error_source` text,
	`error_message` text
);
--> statement-breakpoint
INSERT INTO `__new_event`("id", "event_processing_id", "event_status", "polar_delivery_attempts", "polar_delivered_at", "tinybird_delivery_attempts", "tinybird_delivered_at", "created_at", "updated_at", "request_id", "request_path", "start_time", "end_time", "response_time", "response_status", "environment", "event_type", "user_id", "user_tier", "user_github_id", "user_github_username", "api_key_id", "api_key_name", "api_key_type", "selected_meter_id", "selected_meter_slug", "balances", "referrer_url", "referrer_domain", "model_requested", "resolved_model_requested", "model_used", "model_provider_used", "is_billed_usage", "token_price_prompt_text", "token_price_prompt_cached", "token_price_prompt_audio", "token_price_prompt_image", "token_price_completion_text", "token_price_completion_reasoning", "token_price_completion_audio", "token_price_completion_image", "token_price_completion_video_seconds", "token_price_completion_video_tokens", "token_count_prompt_text", "token_count_prompt_audio", "token_count_prompt_cached", "token_count_prompt_image", "token_count_completion_text", "token_count_completion_reasoning", "token_count_completion_audio", "token_count_completion_image", "token_count_completion_video_seconds", "token_count_completion_video_tokens", "total_cost", "total_price", "moderation_prompt_hate_severity", "moderation_prompt_self_harm_severity", "moderation_prompt_sexual_severity", "moderation_prompt_violence_severity", "moderation_prompt_jailbreak_detected", "moderation_completion_hate_severity", "moderation_completion_self_harm_severity", "moderation_completion_sexual_severity", "moderation_completion_violence_severity", "moderation_completion_protected_material_code_detected", "moderation_completion_protected_material_text_detected", "cache_hit", "cache_type", "cache_semantic_similarity", "cache_semantic_threshold", "cache_key", "error_response_code", "error_source", "error_message") SELECT "id", "event_processing_id", "event_status", "polar_delivery_attempts", "polar_delivered_at", "tinybird_delivery_attempts", "tinybird_delivered_at", "created_at", "updated_at", "request_id", "request_path", "start_time", "end_time", "response_time", "response_status", "environment", "event_type", "user_id", "user_tier", "user_github_id", "user_github_username", "api_key_id", "api_key_name", "api_key_type", "selected_meter_id", "selected_meter_slug", "balances", "referrer_url", "referrer_domain", "model_requested", "resolved_model_requested", "model_used", "model_provider_used", "is_billed_usage", "token_price_prompt_text", "token_price_prompt_cached", "token_price_prompt_audio", "token_price_prompt_image", "token_price_completion_text", "token_price_completion_reasoning", "token_price_completion_audio", "token_price_completion_image", "token_price_completion_video_seconds", "token_price_completion_video_tokens", "token_count_prompt_text", "token_count_prompt_audio", "token_count_prompt_cached", "token_count_prompt_image", "token_count_completion_text", "token_count_completion_reasoning", "token_count_completion_audio", "token_count_completion_image", "token_count_completion_video_seconds", "token_count_completion_video_tokens", "total_cost", "total_price", "moderation_prompt_hate_severity", "moderation_prompt_self_harm_severity", "moderation_prompt_sexual_severity", "moderation_prompt_violence_severity", "moderation_prompt_jailbreak_detected", "moderation_completion_hate_severity", "moderation_completion_self_harm_severity", "moderation_completion_sexual_severity", "moderation_completion_violence_severity", "moderation_completion_protected_material_code_detected", "moderation_completion_protected_material_text_detected", "cache_hit", "cache_type", "cache_semantic_similarity", "cache_semantic_threshold", "cache_key", "error_response_code", "error_source", "error_message" FROM `event`;--> statement-breakpoint
DROP TABLE `event`;--> statement-breakpoint
ALTER TABLE `__new_event` RENAME TO `event`;--> statement-breakpoint
PRAGMA foreign_keys=ON;