ALTER TABLE `community_endpoint` ADD `title` text DEFAULT '' NOT NULL;--> statement-breakpoint
UPDATE `community_endpoint` SET `title` = substr(`name`, 1, 42);--> statement-breakpoint
UPDATE `community_endpoint` SET `title` = 'GEMMA 4 31B', `description` = NULL WHERE `name` = 'gemma-4-31b-it' AND `description` = 'GEMMA 4 31B';--> statement-breakpoint
UPDATE `community_endpoint` SET `title` = 'Agnes 1.5 Flash', `description` = NULL WHERE `name` = 'agnes-1.5-flash' AND `description` = 'Agnes 1.5 flash';--> statement-breakpoint
UPDATE `community_endpoint` SET `title` = 'Agnes 2.0 Flash', `description` = NULL WHERE `name` = 'agnes-2.0-flash' AND `description` = 'Agnes 2.0 flash';--> statement-breakpoint
UPDATE `community_endpoint` SET `title` = 'Agnes Image 2.0 Flash', `description` = NULL WHERE `name` = 'agnes-image-2.0-flash' AND `description` = 'Agnes image 2.0 flash';--> statement-breakpoint
UPDATE `community_endpoint` SET `title` = 'Agnes Image 2.1 Flash', `description` = NULL WHERE `name` = 'agnes-image-2.1-flash' AND `description` = 'Agnes image 2.1 flash';--> statement-breakpoint
UPDATE `community_endpoint` SET `title` = 'Auto Router 1', `description` = NULL WHERE `name` = 'auto-router-1' AND `description` = 'Auto router 1';--> statement-breakpoint
UPDATE `community_endpoint` SET `title` = 'Claude Sonnet 4.6', `description` = NULL WHERE `name` = 'claude-sonnet-4.6' AND `description` = 'Claude Sonnet 4.6';--> statement-breakpoint
UPDATE `community_endpoint` SET `title` = 'DeepSeek V4 Flash', `description` = NULL WHERE `name` = 'deepseek-v4-flash' AND `description` = 'Deepseek v4 flash';--> statement-breakpoint
UPDATE `community_endpoint` SET `title` = 'Gemini 3.6 Flash', `description` = NULL WHERE `name` = 'gemini-3.6-flash' AND `description` = 'Gemini 3.6 flash';--> statement-breakpoint
UPDATE `community_endpoint` SET `title` = 'Gemma 4 31B', `description` = NULL WHERE `name` = 'gemma-4-31b' AND `description` = 'Gemma 4 31b';--> statement-breakpoint
UPDATE `community_endpoint` SET `title` = 'GLM 4.7', `description` = NULL WHERE `name` = 'glm-4.7' AND `description` = 'Glm 4.7';--> statement-breakpoint
UPDATE `community_endpoint` SET `title` = 'GLM 4.7 Flash', `description` = NULL WHERE `name` = 'glm-4.7-flash' AND `description` = 'Glm 4.7 flash';--> statement-breakpoint
UPDATE `community_endpoint` SET `title` = 'GPT-OSS 120B', `description` = NULL WHERE `name` = 'gpt-oss-120b' AND `description` = 'Gpt oss 120b';--> statement-breakpoint
UPDATE `community_endpoint` SET `title` = 'OpenAI Fast', `description` = NULL WHERE `name` = 'openai-fast' AND `description` = 'Openai fast';--> statement-breakpoint
UPDATE `community_endpoint` SET `title` = 'Qwen Image 3.0 Pro', `description` = NULL WHERE `name` = 'qwen-image-3.0-pro' AND `description` = 'Qwen image 3.0 pro';--> statement-breakpoint
UPDATE `community_endpoint` SET `title` = 'Elixpo Router v2.6', `description` = 'Supports function calling.' WHERE `name` = 'lixsearch' AND `description` = 'elixpo-routerv2.6 function calling';--> statement-breakpoint
UPDATE `community_endpoint` SET `title` = 'AffordaClaude', `description` = 'Lower-cost access to Claude Haiku 4.5.' WHERE `name` = 'afforda-claude-haiku-4.5' AND `description` = 'AffordaClaude (Claude Haiku 4.5 Cheap)';--> statement-breakpoint
UPDATE `community_endpoint` SET `title` = 'Agnes 2.0 Flash', `description` = 'A really cool model from a growing Singapore-based company.' WHERE `name` = 'agnes-2.0-flash' AND `description` = 'Agnes 2.0 Flash - Really cool model from a company based in singapore, thats on its way up!';--> statement-breakpoint
UPDATE `community_endpoint` SET `title` = 'Agnes Image 2.1 Flash 1K', `description` = 'Returns an image URL.' WHERE `name` = 'agnes-image-2.1-flash-1k' AND `description` = 'Agnes Image 2.1 Flash 1k (responds with url)';--> statement-breakpoint
UPDATE `community_endpoint` SET `title` = 'Agnes Image 2.1 Flash 2K', `description` = 'Returns a media.polli URL.' WHERE `name` = 'agnes-image-2.1-flash-2k' AND `description` = 'Agnes Image 2.1 Flash 2k res (Responds with a media.polli url)';--> statement-breakpoint
UPDATE `community_endpoint` SET `title` = 'Agnes Video 2.0', `description` = 'Returns a task URL.' WHERE `name` = 'agnes-video-v2.0' AND `description` = 'Agnes Video 2.0 (Responds with a task url)';--> statement-breakpoint
UPDATE `community_endpoint` SET `title` = 'Grok 4.5', `description` = NULL WHERE `name` = 'grok-4.5' AND `description` = 'Grok 4.5';--> statement-breakpoint
UPDATE `community_endpoint` SET `title` = 'DeepSeek V4 Flash', `description` = 'Available through JankRouter.' WHERE `name` = 'deepseek-v4-flash' AND `description` = 'DeepSeek V4 Flash via JankRouter';--> statement-breakpoint
UPDATE `community_endpoint` SET `title` = 'Gemini 2.5 Flash Lite', `description` = 'Available through JankRouter.' WHERE `name` = 'gemini-2.5-flash-lite' AND `description` = 'Gemini 2.5 Flash Lite via JankRouter';--> statement-breakpoint
UPDATE `community_endpoint` SET `title` = 'Gemini 3 Flash', `description` = 'Available through JankRouter.' WHERE `name` = 'gemini-3-flash-preview' AND `description` = 'Gemini 3 Flash via JankRouter';--> statement-breakpoint
UPDATE `community_endpoint` SET `title` = 'Gemini 3.1 Flash Lite', `description` = 'Available through JankRouter.' WHERE `name` = 'gemini-3.1-flash-lite' AND `description` = 'Gemini 3.1 Flash Lite via JankRouter';--> statement-breakpoint
UPDATE `community_endpoint` SET `title` = 'Gemma 3 27B', `description` = 'Available through JankRouter.' WHERE `name` = 'gemma-3-27b' AND `description` = 'Gemma 3 27B via JankRouter';--> statement-breakpoint
UPDATE `community_endpoint` SET `title` = 'Gemma 4 31B', `description` = 'Available through JankRouter.' WHERE `name` = 'gemma-4-31b' AND `description` = 'Gemma 4 31B via JankRouter';--> statement-breakpoint
UPDATE `community_endpoint` SET `title` = 'GLM 4.6V Flash', `description` = 'Available through JankRouter.' WHERE `name` = 'glm-4.6v-flash' AND `description` = 'GLM 4.6V Flash via JankRouter';--> statement-breakpoint
UPDATE `community_endpoint` SET `title` = 'GLM 5.2', `description` = 'Available through JankRouter.' WHERE `name` = 'glm-5.2' AND `description` = 'GLM 5.2 via JankRouter';--> statement-breakpoint
UPDATE `community_endpoint` SET `title` = 'MiMo V2.5', `description` = 'Available through JankRouter.' WHERE `name` = 'mimo-v2.5' AND `description` = 'MiMo V2.5 via JankRouter';--> statement-breakpoint
UPDATE `community_endpoint` SET `title` = 'MiniMax M3', `description` = 'Available through JankRouter.' WHERE `name` = 'minimax-m3' AND `description` = 'MiniMax M3 via JankRouter';--> statement-breakpoint
UPDATE `community_endpoint` SET `title` = 'North Mini Code', `description` = 'Available through JankRouter.' WHERE `name` = 'north-mini-code' AND `description` = 'North Mini Code via JankRouter';--> statement-breakpoint
UPDATE `community_endpoint` SET `title` = 'DeepSeek V3.2', `description` = NULL WHERE `name` = 'deepseek-v3.2' AND `description` = 'deepseek-v3.2';--> statement-breakpoint
UPDATE `community_endpoint` SET `title` = 'DeepSeek V4 Flash', `description` = NULL WHERE `name` = 'deepseek-v4-flash' AND `description` = 'deepseek-v4-flash';--> statement-breakpoint
UPDATE `community_endpoint` SET `title` = 'Gemini 3.1 Pro Preview', `description` = NULL WHERE `name` = 'gemini-3.1-pro-preview' AND `description` = 'gemini-3.1-pro-preview';--> statement-breakpoint
UPDATE `community_endpoint` SET `title` = 'Gemini 3.5 Flash', `description` = NULL WHERE `name` = 'gemini-3.5-flash' AND `description` = 'gemini-3.5-flash';--> statement-breakpoint
UPDATE `community_endpoint` SET `title` = 'Gemma 4 31B IT (No Thinking)', `description` = NULL WHERE `name` = 'gemma-4-31B-it' AND `description` = 'Gemma-4-31B-it-no-thinking';--> statement-breakpoint
UPDATE `community_endpoint` SET `title` = 'DiffusionGemma 26B A4B', `description` = 'Diffusion-based 26B parameter LLM with parallel token generation for real-time text apps.' WHERE `name` = 'diffusiongemma-26b-a4b-it:free' AND `description` = 'DiffusionGemma 26b A4b (Diffusion-based 26B parameter LLM enabling parallel token generation for real-time text apps)';--> statement-breakpoint
UPDATE `community_endpoint` SET `title` = 'Laguna S 2.1', `description` = 'Frontier-class reasoning at mid-size cost. Optimized for quality, speed, and efficiency. 118B params / 8B active / 1M context.' WHERE `name` = 'laguna-s-2.1:free' AND `description` = 'Laguna S 2.1 Frontier-class reasoning at mid-size cost. Optimized for quality, speed, and efficiency. 118B params / 8B active / 1M context';--> statement-breakpoint
UPDATE `community_endpoint` SET `title` = 'Laguna XS 2.1', `description` = 'Efficient 33B MoE for local, long-horizon agentic coding and terminal tasks.' WHERE `name` = 'laguna-xs-2.1:free' AND `description` = 'Laguna XS 2.1 (Efficient 33B MoE for local, long-horizon agentic coding and terminal tasks)';--> statement-breakpoint
UPDATE `community_endpoint` SET `title` = 'Llama 3.1 8B Instant', `description` = '550+ tok/s.' WHERE `name` = 'llama-3.1-8b-instant:free' AND `description` = 'Llama 3.1 8b Instant (550+ tok/s)';--> statement-breakpoint
UPDATE `community_endpoint` SET `title` = 'Mistral Ministral 3 14B', `description` = NULL WHERE `name` = 'ministral-3' AND `description` = 'Mistral Ministral 3 14B';--> statement-breakpoint
UPDATE `community_endpoint` SET `title` = 'Mercury 2', `description` = 'Cheap.' WHERE `name` = 'mercury-cheap' AND `description` = 'Mercury 2 (cheap)';--> statement-breakpoint
UPDATE `community_endpoint` SET `title` = 'Mistral Le Chaton Fat', `description` = NULL WHERE `name` = 'mistral-fat' AND `description` = 'Mistral Le Chaton Fat';--> statement-breakpoint
UPDATE `community_endpoint` SET `title` = 'Codestral 25.08', `description` = NULL WHERE `name` = 'inferenceport-ai-codestral-2508' AND `description` = 'Codestral 25.08';--> statement-breakpoint
UPDATE `community_endpoint` SET `title` = 'Cohere Command R+', `description` = NULL WHERE `name` = 'inferenceport-ai-command-r-plus' AND `description` = 'Cohere Command R+';--> statement-breakpoint
UPDATE `community_endpoint` SET `title` = 'Gemini 2.5 Flash', `description` = NULL WHERE `name` = 'inferenceport-ai-gemini-2.5-flash' AND `description` = 'Gemini 2.5 Flash';--> statement-breakpoint
UPDATE `community_endpoint` SET `title` = 'OpenAI GPT-4.1', `description` = NULL WHERE `name` = 'inferenceport-ai-gpt-4.1' AND `description` = 'OpenAI GPT-4.1';--> statement-breakpoint
UPDATE `community_endpoint` SET `title` = 'Kimi K2.5', `description` = NULL WHERE `name` = 'inferenceport-ai-kimi-k2.5' AND `description` = 'Kimi k2.5';--> statement-breakpoint
UPDATE `community_endpoint` SET `title` = 'Kimi K2.7 Code', `description` = NULL WHERE `name` = 'inferenceport-ai-kimi-k2.7-code' AND `description` = 'Kimi k2.7 Code';--> statement-breakpoint
UPDATE `community_endpoint` SET `title` = 'InferencePort AI Lightning-Image Turbo', `description` = NULL WHERE `name` = 'inferenceport-ai-lightning-image-turbo' AND `description` = 'InferencePort AI Lightning-Image Turbo';--> statement-breakpoint
UPDATE `community_endpoint` SET `title` = 'InferencePort AI Lightning Text v2', `description` = 'Router.' WHERE `name` = 'inferenceport-ai-lightning-text-v2' AND `description` = 'InferencePort AI Lightning Text v2 (Router)';--> statement-breakpoint
UPDATE `community_endpoint` SET `title` = 'MiMo V2.5', `description` = NULL WHERE `name` = 'inferenceport-ai-mimo-v2.5' AND `description` = 'Mimo v2.5';--> statement-breakpoint
UPDATE `community_endpoint` SET `title` = 'MiniMax M3', `description` = NULL WHERE `name` = 'inferenceport-ai-minimax-m3' AND `description` = 'MiniMax M3';--> statement-breakpoint
UPDATE `community_endpoint` SET `title` = 'Qwen 3.6 27B', `description` = NULL WHERE `name` = 'inferenceport-ai-qwen-3.6-27b' AND `description` = 'Qwen 3.6 27b';--> statement-breakpoint
UPDATE `community_endpoint` SET `title` = 'OpenAI GPT-5 Chat Latest', `description` = NULL WHERE `name` = 'inferenceport.ai-gpt-5-chat-latest' AND `description` = 'OpenAI GPT-5 Chat Latest';--> statement-breakpoint
UPDATE `community_endpoint` SET `title` = 'GPT-OSS 20B', `description` = NULL WHERE `name` = 'inferenceport.ai-gpt-oss-20b' AND `description` = 'GPT-OSS 20b';--> statement-breakpoint
UPDATE `community_endpoint` SET `title` = 'Falcon H1 Tiny 90M Instruct', `description` = NULL WHERE `name` = 'falcon-h1-tiny' AND `description` = 'Falcon H1 Tiny 90M Instruct';--> statement-breakpoint
UPDATE `community_endpoint` SET `title` = 'GLM-5.2', `description` = 'Very cheap.' WHERE `name` = 'glm-5.2-cheap' AND `description` = 'GLM-5.2 (Very Cheap)';--> statement-breakpoint
UPDATE `community_endpoint` SET `title` = 'Tencent HY3', `description` = NULL WHERE `name` = 'hy3' AND `description` = 'Tencent Hy3';--> statement-breakpoint
UPDATE `community_endpoint` SET `title` = 'Mercury 2', `description` = '~300 tok/s.' WHERE `name` = 'mercury2' AND `description` = 'Mercury 2 (~300tps)';--> statement-breakpoint
UPDATE `community_endpoint` SET `title` = 'MiniMax M3', `description` = 'Cheap.' WHERE `name` = 'minimax-m3' AND `description` = 'Minimax M3 (Cheap)';--> statement-breakpoint
UPDATE `community_endpoint` SET `title` = 'Gemini 3.1 Flash Lite', `description` = NULL WHERE `name` = 'ezra' AND `description` = 'Gemini 3.1 flash lite';--> statement-breakpoint
UPDATE `community_endpoint` SET `title` = 'Ultra-Fast Gemma 4 31B', `description` = NULL WHERE `name` = 'gemma-4-31b-fast' AND `description` = 'Ultra fast gemma 4 31b';--> statement-breakpoint
UPDATE `community_endpoint` SET `title` = 'Krea 2 Medium Turbo', `description` = 'A distilled, speed-focused variant of Krea 2 Medium from Krea.' WHERE `name` = 'krea-2-medium-turbo' AND `description` = 'Krea 2 Medium Turbo is a distilled, speed-focused variant of Krea 2 Medium from Krea.';--> statement-breakpoint
UPDATE `community_endpoint` SET `title` = 'MAI-Image-2.5', `description` = 'High-quality image generation from Microsoft.' WHERE `name` = 'mai-image-2.5' AND `description` = 'Microsoft''s MAI-Image-2.5 is a high-quality image generation model.';--> statement-breakpoint
UPDATE `community_endpoint` SET `title` = 'Nano Banana', `description` = NULL WHERE `name` = 'nano-banana' AND `description` = 'Nano banana';--> statement-breakpoint
UPDATE `community_endpoint` SET `title` = 'Nano Banana 2', `description` = NULL WHERE `name` = 'nano-banana-2' AND `description` = 'Nano banana 2';--> statement-breakpoint
UPDATE `community_endpoint` SET `title` = 'Nano Banana 2 Lite', `description` = NULL WHERE `name` = 'nano-banana-2-lite' AND `description` = 'Nano banana 2 lite';--> statement-breakpoint
UPDATE `community_endpoint` SET `title` = 'Nano Banana Pro', `description` = NULL WHERE `name` = 'nano-banana-pro' AND `description` = 'Nano banana pro';--> statement-breakpoint
UPDATE `community_endpoint` SET `title` = 'Seedream 5 Pro', `description` = NULL WHERE `name` = 'seedream-5-pro' AND `description` = 'Seedream 5 pro.';--> statement-breakpoint
UPDATE `community_endpoint` SET `title` = 'Claude Opus 4.8', `description` = NULL WHERE `name` = 'claude-opus-4-8' AND `description` = 'Claude Opus 4.8';--> statement-breakpoint
UPDATE `community_endpoint` SET `title` = 'DeepSeek V3.2', `description` = NULL WHERE `name` = 'deepseek-v3.2' AND `description` = 'Deepseek v3.2';--> statement-breakpoint
UPDATE `community_endpoint` SET `title` = 'DeepSeek V4 Flash', `description` = NULL WHERE `name` = 'deepseek-v4-flash' AND `description` = 'Deepseek V4 Flash';--> statement-breakpoint
UPDATE `community_endpoint` SET `title` = 'DeepSeek V4 Pro', `description` = NULL WHERE `name` = 'deepseek-v4-pro' AND `description` = 'Deepseek v4 Pro';--> statement-breakpoint
UPDATE `community_endpoint` SET `title` = 'Gemma 4 31B', `description` = NULL WHERE `name` = 'gemma-4-31B' AND `description` = 'Gemma 4 31B';--> statement-breakpoint
UPDATE `community_endpoint` SET `title` = 'Kimi K2.6', `description` = 'Per-day limit.' WHERE `name` = 'kimi-k2.6' AND `description` = 'Kimi K2.6 (Per Day Limit)';--> statement-breakpoint
UPDATE `community_endpoint` SET `title` = 'Nemotron 3 Ultra', `description` = 'Free*.' WHERE `name` = 'nemotron-3-ultra' AND `description` = 'Nemotron 3 Ultra (Free*)';--> statement-breakpoint
UPDATE `community_endpoint` SET `title` = 'Qwen 3.8 Max Preview', `description` = NULL WHERE `name` = 'qwen3.8-max-preview' AND `description` = 'Qwen 3.8 Max Preview';--> statement-breakpoint
UPDATE `community_endpoint` SET `title` = 'Unlocked DeepSeek', `description` = 'Per-day limit with a 20K context window.' WHERE `name` = 'unlocked-deepseek' AND `description` = 'Unlocked Deepseek (Per Day Limit, 20K Context)';--> statement-breakpoint
UPDATE `community_endpoint` SET `title` = 'ByteDance Doubao Seed 2.0 Pro', `description` = 'Available through Airforce.' WHERE `name` = 'airforce-doubao-pro' AND `description` = 'ByteDance Doubao Seed 2.0 Pro via Airforce';--> statement-breakpoint
UPDATE `community_endpoint` SET `title` = 'Grok 4 Fast', `description` = 'xAI model available through Airforce.' WHERE `name` = 'airforce-grok-4-fast' AND `description` = 'Grok 4 Fast (xAI) via Airforce';--> statement-breakpoint
UPDATE `community_endpoint` SET `title` = 'Qwen3 Max', `description` = 'Alibaba model available through Airforce.' WHERE `name` = 'airforce-qwen3-max' AND `description` = 'Qwen3 Max (Alibaba) via Airforce';--> statement-breakpoint
UPDATE `community_endpoint` SET `title` = 'DeepSeek Chat', `description` = 'Available through AnyVM.' WHERE `name` = 'anyvm-deepseek-chat' AND `description` = 'DeepSeek Chat via AnyVM';
