-- Promote the same 159 reviewed model IDs in stored API-key allowlists.
-- Scan the key table once, not once per model: migrations apply submits the
-- whole file as one D1 query batch with a shared CPU budget.
-- Update rows directly so large permission arrays are not all materialized
-- in memory. Only the small rename lookup is shared across rows.
-- Unknown/community IDs, unrelated fields, array order and first occurrences
-- are preserved. Already-canonical rows are untouched, including on retry.

WITH renames(old_id, new_id) AS (
    VALUES
        ('claude', 'anthropic/claude-sonnet-4.6'),
        ('flux-2-pro', 'black-forest-labs/flux.2-pro'),
        ('flux-2-flex', 'black-forest-labs/flux.2-flex'),
        ('gpt-live-transcribe', 'openai/gpt-live-transcribe'),
        ('wan-3.0', 'alibaba/wan-3.0'),
        ('claude-fable-5', 'anthropic/claude-fable-5'),
        ('claude-fast', 'anthropic/claude-haiku-4.5'),
        ('claude-large', 'anthropic/claude-opus-5'),
        ('claude-opus-4.6', 'anthropic/claude-opus-4.6'),
        ('claude-opus-4.7', 'anthropic/claude-opus-4.7'),
        ('claude-sonnet-5', 'anthropic/claude-sonnet-5'),
        ('cohere-embed-v4', 'cohere/embed-v4.0'),
        ('command-a-plus', 'cohere/command-a-plus'),
        ('csm-1b', 'sesame/csm-1b'),
        ('deepseek', 'deepseek/deepseek-v4-flash'),
        ('deepseek-pro', 'deepseek/deepseek-v4-pro'),
        ('dreamshaper', 'lykon/dreamshaper-8-lcm'),
        ('eleven-dialogue', 'elevenlabs/eleven-v3:dialogue'),
        ('eleven-multilingual-v2', 'elevenlabs/eleven-multilingual-v2'),
        ('eleven-sfx', 'elevenlabs/eleven-text-to-sound-v2'),
        ('eleven-voice-changer', 'elevenlabs/eleven-multilingual-sts-v2'),
        ('eleven-voice-isolator', 'elevenlabs/voice-isolator'),
        ('elevenflash', 'elevenlabs/eleven-flash-v2.5'),
        ('elevenlabs', 'elevenlabs/eleven-v3'),
        ('elevenmusic', 'elevenlabs/music-v2'),
        ('flux', 'black-forest-labs/flux.1-schnell'),
        ('gemini', 'google/gemini-3.7-flash'),
        ('gemini-2', 'google/gemini-embedding-2'),
        ('gemini-3-flash', 'google/gemini-3-flash-preview'),
        ('gemini-fast', 'google/gemini-2.5-flash-lite'),
        ('gemini-flash-lite-3.5', 'google/gemini-3.5-flash-lite'),
        ('gemini-large', 'google/gemini-3.1-pro-preview'),
        ('gemini-search', 'google/gemini-2.5-flash-lite:search'),
        ('gemma', 'google/gemma-4-26b-a4b-it'),
        ('gemma-4-31b', 'google/gemma-4-31b-it'),
        ('glm', 'z-ai/glm-5.2'),
        ('gpt-5.4', 'openai/gpt-5.4'),
        ('gpt-5.4-mini', 'openai/gpt-5.4-mini'),
        ('gpt-5.6-luna', 'openai/gpt-5.6-luna'),
        ('gpt-5.6-sol', 'openai/gpt-5.6-sol'),
        ('gpt-5.6-terra', 'openai/gpt-5.6-terra'),
        ('gpt-image-2', 'openai/gpt-image-2'),
        ('gpt-oss', 'openai/gpt-oss-20b'),
        ('gpt-realtime-2.1', 'openai/gpt-realtime-2.1'),
        ('gpt-realtime-2.1-mini', 'openai/gpt-realtime-2.1-mini'),
        ('gpt-transcribe', 'openai/gpt-transcribe'),
        ('gptimage', 'openai/gpt-image-1-mini'),
        ('gptimage-large', 'openai/gpt-image-1.5'),
        ('grok', 'x-ai/grok-4.20'),
        ('grok-4.6', 'x-ai/grok-4.6'),
        ('grok-imagine', 'x-ai/grok-imagine-image'),
        ('grok-imagine-image-2.0', 'x-ai/grok-imagine-image-2.0'),
        ('grok-imagine-pro', 'x-ai/grok-imagine-image-quality'),
        ('grok-imagine-video-1.5', 'x-ai/grok-imagine-video-1.5'),
        ('grok-large', 'x-ai/grok-4.3'),
        ('grok-transcribe', 'x-ai/grok-transcribe'),
        ('grok-video-pro', 'x-ai/grok-imagine-video'),
        ('happyhorse-1.1', 'alibaba/happyhorse-1.1'),
        ('hyper3d-rodin', 'hyper3d/rodin-2.5'),
        ('ideogram-v4-balanced', 'ideogram-ai/ideogram-v4-balanced'),
        ('ideogram-v4-quality', 'ideogram-ai/ideogram-v4-quality'),
        ('ideogram-v4-turbo', 'ideogram-ai/ideogram-v4-turbo'),
        ('inkling', 'thinkingmachines/inkling-small'),
        ('kimi', 'moonshotai/kimi-k2.6'),
        ('kimi-code', 'moonshotai/kimi-k2.7-code'),
        ('kimi-k3', 'moonshotai/kimi-k3'),
        ('klein', 'black-forest-labs/flux.2-klein-4b'),
        ('kokoro', 'hexgrad/kokoro-82m'),
        ('kontext', 'black-forest-labs/flux.1-kontext-pro'),
        ('krea', 'krea/krea-2-medium'),
        ('laguna', 'poolside/laguna-s-2.1'),
        ('llama', 'meta/llama-3.3-70b-instruct'),
        ('llama-maverick', 'meta/llama-4-maverick'),
        ('llama-scout', 'meta/llama-4-scout'),
        ('longcat', 'meituan/longcat-2.0'),
        ('lyria-3-clip', 'google/lyria-3-clip-preview'),
        ('mercury', 'inception/mercury-2'),
        ('midijourney', 'pollinations/midijourney'),
        ('midijourney-large', 'pollinations/midijourney-large'),
        ('mimo-v2.5', 'xiaomi/mimo-v2.5'),
        ('mimo-v2.5-pro', 'xiaomi/mimo-v2.5-pro'),
        ('minimax', 'minimax/minimax-m3'),
        ('minimax-h3', 'minimax/minimax-h3'),
        ('minimax-m2.7', 'minimax/minimax-m2.7'),
        ('mistral', 'mistralai/mistral-small-4'),
        ('mistral-large', 'mistralai/mistral-large-3'),
        ('mistral-small-3.2', 'mistralai/mistral-small-3.2'),
        ('muse-glimmer', 'meta/muse-glimmer-30b'),
        ('muse-spark-1.2', 'meta/muse-spark-1.2'),
        ('nanobanana', 'google/gemini-2.5-flash-image'),
        ('nanobanana-2', 'google/gemini-3.1-flash-image'),
        ('nanobanana-2-lite', 'google/gemini-3.1-flash-lite-image'),
        ('nanobanana-pro', 'google/gemini-3-pro-image'),
        ('nemotron', 'nvidia/nemotron-3-ultra'),
        ('nova', 'amazon/nova-2-lite-v1'),
        ('nova-canvas', 'amazon/nova-canvas-v1'),
        ('nova-fast', 'amazon/nova-micro-v1'),
        ('nova-reel', 'amazon/nova-reel-v1'),
        ('openai', 'openai/gpt-5.4-nano'),
        ('openai-3-large', 'openai/text-embedding-3-large'),
        ('openai-3-small', 'openai/text-embedding-3-small'),
        ('openai-audio', 'openai/gpt-audio-mini'),
        ('openai-audio-large', 'openai/gpt-audio-1.5'),
        ('openai-fast', 'openai/gpt-5-nano'),
        ('openai-large', 'openai/gpt-5.5'),
        ('p-image', 'prunaai/p-image'),
        ('p-image-edit', 'prunaai/p-image-edit'),
        ('p-video', 'prunaai/p-video'),
        ('perplexity', 'perplexity/sonar-pro'),
        ('perplexity-fast', 'perplexity/sonar'),
        ('perplexity-reasoning', 'perplexity/sonar-reasoning-pro'),
        ('qwen-coder', 'qwen/qwen3-coder-30b-a3b-instruct'),
        ('qwen-coder-large', 'qwen/qwen3-coder-next'),
        ('qwen-image', 'qwen/qwen-image'),
        ('qwen-image-3', 'qwen/qwen-image-3'),
        ('qwen-large', 'qwen/qwen3.7-plus'),
        ('qwen-safety', 'qwen/qwen3guard-gen-8b'),
        ('qwen-tts', 'qwen/qwen3-tts-flash'),
        ('qwen-tts-instruct', 'qwen/qwen3-tts-instruct-flash'),
        ('qwen-vision', 'qwen/qwen3-vl-30b-a3b-instruct'),
        ('qwen-vision-pro', 'qwen/qwen3-vl-235b-a22b-thinking'),
        ('qwen3-embedding-8b', 'qwen/qwen3-embedding-8b'),
        ('qwen3.7-flash', 'qwen/qwen3.7-flash'),
        ('qwen3.7-max', 'qwen/qwen3.7-max'),
        ('qwen3.8-2.4t-a95b', 'qwen/qwen3.8-2.4t-a95b'),
        ('qwen3.8-max', 'qwen/qwen3.8-max'),
        ('recraft-v4.1-vector', 'recraft/recraft-v4.1-vector'),
        ('scribe', 'elevenlabs/scribe-v2'),
        ('scribe-realtime', 'elevenlabs/scribe-v2-realtime'),
        ('seedance-2.0', 'bytedance/seedance-2.0'),
        ('seedance-2.0-fast', 'bytedance/seedance-2.0-fast'),
        ('seedance-2.0-mini', 'bytedance/seedance-2.0-mini'),
        ('seedance-2.5', 'bytedance/seedance-2.5'),
        ('seedance-pro', 'bytedance/seedance-1-pro-fast'),
        ('seedream', 'bytedance/seedream-4.0'),
        ('seedream-pro', 'bytedance/seedream-4.5'),
        ('seedream5', 'bytedance/seedream-5.0-lite'),
        ('seedream5-pro', 'bytedance/seedream-5.0-pro'),
        ('stable-audio-3-large', 'stability-ai/stable-audio-3'),
        ('stable-audio-3-medium', 'stability-ai/stable-audio-3-medium'),
        ('step-3.5-flash', 'stepfun/step-3.5-flash'),
        ('step-flash', 'stepfun/step-3.7-flash'),
        ('trellis-2', 'microsoft/trellis-2'),
        ('universal-2', 'assemblyai/universal-2'),
        ('universal-3.5-pro', 'assemblyai/universal-3.5-pro'),
        ('veo', 'google/veo-3.1-fast'),
        ('wan', 'alibaba/wan-2.6'),
        ('wan-fast', 'alibaba/wan-2.2-fast'),
        ('wan-image', 'alibaba/wan-2.7-image'),
        ('wan-image-pro', 'alibaba/wan-2.7-image-pro'),
        ('wan-pro', 'alibaba/wan-2.7'),
        ('whisper', 'openai/whisper-large-v3'),
        ('zimage', 'tongyi-mai/z-image-turbo'),
        ('zimage-fal', 'tongyi-mai/z-image-turbo'),
        ('fish-audio-s2.1-pro', 'fish-audio/s2.1-pro'),
        ('glm-5.3', 'z-ai/glm-5.3'),
        ('grok-tts', 'x-ai/grok-tts'),
        ('nemotron-3.5-lightning', 'nvidia/nemotron-3.5-lightning'),
        ('qwen3.8-27b', 'qwen/qwen3.8-27b')
)
UPDATE apikey
SET permissions = json_set(
    permissions,
    '$.models',
    (
        SELECT json_group_array(model_id ORDER BY position)
        FROM (
            SELECT
                COALESCE(renames.new_id, model.value) AS model_id,
                MIN(CAST(model.key AS integer)) AS position
            FROM json_each(apikey.permissions, '$.models') AS model
            LEFT JOIN renames
                ON model.type = 'text' AND model.value = renames.old_id
            GROUP BY COALESCE(renames.new_id, model.value)
        )
    )
)
WHERE CASE
    WHEN NOT json_valid(permissions) THEN 0
    WHEN json_type(permissions, '$.models') != 'array' THEN 0
    ELSE EXISTS (
        SELECT 1
        FROM json_each(permissions, '$.models') AS model
        JOIN renames ON model.type = 'text' AND model.value = renames.old_id
    )
END;
