name: App Submission
description: Submit your app to be featured on pollinations.ai
title: "[App Submission]: "
labels: ["app:review"]
body:
  - type: markdown
    attributes:
      value: |
        <div style="display: flex; align-items: center; gap: 12px; margin-bottom: 24px;">
          <img src="https://raw.githubusercontent.com/pollinations/pollinations/main/shared/assets/logo-text.svg" alt="pollinations.ai Logo" width="120" style="display: inline-block;">
          <h1 style="margin: 0; font-size: 24px; display: inline-block;">Feature my app on pollinations.ai</h1>
        </div>
        <div style="font-size: 1.25em; font-style: italic; margin-bottom: 12px;">
          Thanks for taking the time to submit your app! Please fill out the information below to help us understand and showcase your app.
        </div>

  - type: input
    id: project-name
    attributes:
      label: Project Name
      description: What is the name of your project?
      placeholder: "e.g., AI Art Gallery"
    validations:
      required: true

  - type: textarea
    id: project-description
    attributes:
      label: Project Description
      description: Please provide a brief description of your project and how it uses pollinations.ai
      placeholder: "Describe what your project does and how it integrates with pollinations.ai..."
    validations:
      required: true

  - type: input
    id: project-url
    attributes:
      label: Project URL
      description: Link to your project (if public)
      placeholder: "https://example.com"
    validations:
      required: true

  - type: input
    id: contact-info
    attributes:
      label: Contact Information
      description: How can we reach you? (Discord username, GitHub username, email, or social profile link)
      placeholder: "e.g., @username or https://profile.example.com"
    validations:
      required: true

  - type: input
    id: github-repo
    attributes:
      label: GitHub Repository URL
      description: Provide a link to your project's GitHub repository (if available)
      placeholder: "https://github.com/your-repo"

  - type: dropdown
    id: project-category
    attributes:
      label: Project Category
      description: Select the category under which your project should be posted
      options:
        - Chat Projects 💬
        - Creative Projects 🎨
        - Games 🎲
        - Hack & Build 🛠️
        - Learn 📚
        - Social Bots 🤖
        - Vibe Coding ✨
    validations:
      required: true

  - type: input
    id: project-language
    attributes:
      label: Project Language
      description: If your project is not in English, specify the language code (e.g., zh-CN, es-ES, pt-BR)
      placeholder: "e.g., zh-CN for Chinese, es-ES for Spanish"

  - type: textarea
    id: additional-info
    attributes:
      label: Additional Information
      description: Any other details you'd like to share about your project?
      placeholder: "Screenshots, features, future plans..."