name: Project Submission
description: Submit your project to be featured on Pollinations
title: "[Project Submission]: "
labels: ["project-submission"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to submit your project! Please fill out the information below to help us understand and showcase your project.
        
  - type: input
    id: project-name
    attributes:
      label: Project Name
      description: What is the name of your project?
      placeholder: "e.g., AI Art Gallery"
    validations:
      required: true

  - type: textarea
    id: project-description
    attributes:
      label: Project Description
      description: Please provide a brief description of your project and how it uses Pollinations
      placeholder: "Describe what your project does and how it integrates with Pollinations..."
    validations:
      required: true

  - type: input
    id: project-url
    attributes:
      label: Project URL
      description: Link to your project (if public)
      placeholder: "https://example.com"

  - type: input
    id: discord-username
    attributes:
      label: Discord Username or Social Profile Link
      description: Provide your Discord username or a link to another social profile online
      placeholder: "e.g., @username or https://profile.example.com"
    validations:
      required: true

  - type: input
    id: github-repo
    attributes:
      label: GitHub Repository URL
      description: (Optional) Provide a link to your project's GitHub repository
      placeholder: "https://github.com/your-repo"

  - type: dropdown
    id: project-category
    attributes:
      label: Project Category
      description: Select the category under which your project should be posted
      options:
        - LLM Integrations
        - Creative & Interactive Applications
        - Tools & Interfaces
        - Social Bots
        - SDK & Libraries
        - Tutorials
    validations:
      required: true

  - type: textarea
    id: additional-info
    attributes:
      label: Additional Information
      description: Any other details you'd like to share about your project?
      placeholder: "Screenshots, features, future plans..."

  - type: input
    id: contact
    attributes:
      label: Contact Information
      description: How can we reach you if we have questions? (GitHub username, email, or Discord handle)
      placeholder: "@username or email"
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ### Implementation Instructions

        For the person implementing this issue:
        - Add the new project to the top of the appropriate section in README.md and pollinations.ai/src/config/projectList.js
        - Add a new UTF-8 icon to the title or where appropriate