name: Balance Question
description: Questions about your balance
title: "Balance:"
labels: ["ACCOUNT", ".QUESTION"]
body:
  - type: textarea
    id: description
    attributes:
      label: Question
      placeholder: "e.g., Why is my balance showing 0? How do I earn more pollen?"
    validations:
      required: true
