name: SubmitApp
description: Get your app featured on pollinations.ai
title: "[App Submission] ${{ inputs.app-name }}"
labels: ["TIER-APP"]
body:
  - type: markdown
    attributes:
      value: |
        # Submit Your App to pollinations.ai
        
        Thanks for submitting your app! Fill out the form below and we'll review it for the [Official Showcase](https://pollinations.ai/apps).

        ---

        **✅ Requirements**
        - Have an account at [enter.pollinations.ai](https://enter.pollinations.ai) (sign up with GitHub)
        - Your app must use the pollinations.ai API

        **💡 Credit pollinations.ai** *(optional but appreciated)*
        - Link to [pollinations.ai](https://pollinations.ai) in your frontend/README
        - Official logos: [`Pollinations Logo White`](https://raw.githubusercontent.com/pollinations/pollinations/main/assets/logo.svg) / [`Pollinations Logo Text White`](https://raw.githubusercontent.com/pollinations/pollinations/main/assets/logo-text.svg)
        - Official Badge: [`Built With Pollinations`](https://img.shields.io/badge/Built%20with-Pollinations-8a2be2?style=for-the-badge&logo=data:image/svg+xml,%3Csvg%20xmlns%3D%22http://www.w3.org/2000/svg%22%20viewBox%3D%220%200%20124%20124%22%3E%3Ccircle%20cx%3D%2262%22%20cy%3D%2262%22%20r%3D%2262%22%20fill%3D%22%23ffffff%22/%3E%3C/svg%3E&logoColor=white&labelColor=6a0dad)
        ---
        *Your GitHub username will be credited as the app author.*

  - type: input
    id: app-name
    attributes:
      label: App Name
      description: What is the name of your app?
      placeholder: "e.g., AI Art Gallery"
    validations:
      required: true

  - type: textarea
    id: app-description
    attributes:
      label: App Description
      description: Please provide a brief description of your app and how it uses pollinations.ai
      placeholder: "Describe what your app does and how it integrates with pollinations.ai..."
    validations:
      required: false

  - type: input
    id: app-url
    attributes:
      label: App URL
      description: Link to your app (if public)
      placeholder: "https://example.com"
    validations:
      required: true

  - type: input
    id: github-repo
    attributes:
      label: GitHub Open Source Repository URL
      description: Provide a link to your app's GitHub repository (if available)
      placeholder: "https://github.com/your-repo"

  - type: input
    id: discord-contact
    attributes:
      label: Discord Username
      description: Your Discord username so we can reach you (optional)
      placeholder: "e.g., username or username#1234"

  - type: dropdown
    id: app-category
    attributes:
      label: App Category
      description: Select the category under which your app should be listed
      options:
        - Creative
        - Chat
        - Games
        - Dev Tools
        - Vibes
        - Social Bots
        - Learn
    validations:
      required: true

  - type: input
    id: app-language
    attributes:
      label: App Language
      description: If your app is not in English, specify the language code (e.g., zh-CN, es, pt-BR, ja)
      placeholder: "e.g., zh-CN for Chinese, es for Spanish, ja for Japanese"

  - type: input
    id: other-contact
    attributes:
      label: Other Contact (optional)
      description: Any other way to reach you (Twitter/X, Instagram, website, etc.)
      placeholder: "e.g., https://twitter.com/yourhandle"
