name: SubmitApp
description: Get your app featured on pollinations.ai
title: "[App Submission] "
labels: ["tier:review"]
body:
  - type: markdown
    attributes:
      value: |
        # pollinations.ai - Feature App
        
        Thanks for submitting your app! Fill out the form below and we'll review it for the [pollinations.ai showcase](https://pollinations.ai).

  - type: input
    id: app-name
    attributes:
      label: App Name
      description: What is the name of your app?
      placeholder: "e.g., AI Art Gallery"
    validations:
      required: true

  - type: textarea
    id: app-description
    attributes:
      label: App Description
      description: Please provide a brief description of your app and how it uses pollinations.ai
      placeholder: "Describe what your app does and how it integrates with pollinations.ai..."
    validations:
      required: true

  - type: input
    id: app-url
    attributes:
      label: App URL
      description: Link to your app (if public)
      placeholder: "https://example.com"
    validations:
      required: true

  - type: input
    id: github-repo
    attributes:
      label: GitHub Repository URL
      description: Provide a link to your app's GitHub repository (if available)
      placeholder: "https://github.com/your-repo"

  - type: input
    id: discord-contact
    attributes:
      label: Discord Username
      description: Your Discord username so we can reach you (optional)
      placeholder: "e.g., username or username#1234"

  - type: dropdown
    id: app-category
    attributes:
      label: App Category
      description: Select the category under which your app should be listed
      default: 0
      options:
        - Chat 💬
        - Creative 🎨
        - Games 🎲
        - Hack & Build 🛠️
        - Learn 📚
        - Social Bots 🤖
        - Vibe Coding ✨
    validations:
      required: true

  - type: input
    id: app-language
    attributes:
      label: App Language
      description: If your app is not in English, specify the language code (e.g., zh-CN, es-ES, pt-BR)
      placeholder: "e.g., zh-CN for Chinese, es-ES for Spanish"
