[tool.poetry]
name = "docs"
version = "0.1.0"
description = ""
authors = ["Anirban Kar <thecodacus@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
mkdocs-material = "^9.5.45"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
