import type {
    BalanceRow,
    CashMonthlyRow,
    CoverageRow,
    GapRow,
    GrantRow,
    InvoiceRow,
    ProviderMonthRow,
    RunRow,
} from "./types";

const coverage: CoverageRow[] = [
    {
        month: "2026-01",
        provider: "vast.ai",
        billing: "prepaid",
        status: "missing_invoice",
        invoice_usd: 0,
        payment_usd: 480.19,
    },
    {
        month: "2026-02",
        provider: "vast.ai",
        billing: "prepaid",
        status: "missing_invoice",
        invoice_usd: 0,
        payment_usd: 2518.4,
    },
    {
        month: "2026-03",
        provider: "vast.ai",
        billing: "prepaid",
        status: "amount_mismatch",
        invoice_usd: 3481,
        payment_usd: 3466.55,
    },
    {
        month: "2026-01",
        provider: "openai",
        billing: "monthly",
        status: "ok",
        invoice_usd: 226.4,
        payment_usd: 226.4,
    },
    {
        month: "2026-02",
        provider: "openai",
        billing: "monthly",
        status: "ok",
        invoice_usd: 254.1,
        payment_usd: 254.1,
    },
    {
        month: "2026-01",
        provider: "aws",
        billing: "sponsored",
        status: "ok_credit",
        invoice_usd: 0,
        payment_usd: 0,
    },
    {
        month: "2026-02",
        provider: "aws",
        billing: "sponsored",
        status: "ok_credit",
        invoice_usd: 0,
        payment_usd: 0,
    },
    {
        month: "2026-01",
        provider: "anthropic",
        billing: "monthly",
        status: "needs_review",
        invoice_usd: 616.1,
        payment_usd: 616.1,
    },
    {
        month: "2026-02",
        provider: "azure",
        billing: "sponsored",
        status: "accepted",
        invoice_usd: 0,
        payment_usd: 0,
    },
    {
        month: "2026-03",
        provider: "scaleway",
        billing: "monthly",
        status: "missing_payment",
        invoice_usd: 289.6,
        payment_usd: 0,
    },
    {
        month: "2026-03",
        provider: "gcp",
        billing: "sponsored",
        status: "needs_data",
        invoice_usd: 0,
        payment_usd: 0,
    },
];

const gaps: GapRow[] = [
    {
        month: "2026-01",
        provider: "vast.ai",
        billing: "prepaid",
        status: "missing_invoice",
        invoice_usd: 0,
        payment_usd: 480.19,
        delta_usd: -480.19,
        invoice_refs: "",
        payment_refs: "wise-tx-8812",
        note: "card-FX drift: $500 top-up charged as $480.19",
    },
    {
        month: "2026-03",
        provider: "vast.ai",
        billing: "prepaid",
        status: "amount_mismatch",
        invoice_usd: 3481,
        payment_usd: 3466.55,
        delta_usd: 14.45,
        invoice_refs: "inv-vast-7x",
        payment_refs: "wise-tx-9931,wise-tx-9940",
        note: "7/8 payments matched; Mar-1 $484.55 unmatched",
    },
    {
        month: "2026-01",
        provider: "anthropic",
        billing: "monthly",
        status: "needs_review",
        invoice_usd: 616.1,
        payment_usd: 616.1,
        delta_usd: 0,
        invoice_refs: "10ECF632-0011",
        payment_refs: "wise-tx-7719",
        note: "4 Claude Max seat invoices need labels",
    },
];

const invoices: InvoiceRow[] = [
    {
        sha256: "aa11bb22cc33dd44ee55ff6600112233445566778899aabbccddeeff00112233",
        provider: "other",
        category: "",
        kind: "",
        period_month: "2026-03",
        amount: 500,
        currency: "USD",
        amount_usd: 500,
        credit_usd: 0,
        invoice_number: "",
        issued_at: "2026-03-04",
        source: "email",
        file_ref: "2026-03/other_2026-03_aa11bb22_inv.pdf",
        status: "parsed",
        ingested_at: "2026-07-03",
    },
    {
        sha256: "aa11bb22cc33dd44ee55ff6600112233445566778899aabbccddeeff00112233",
        provider: "vast.ai",
        category: "",
        kind: "prepaid_topup",
        period_month: "2026-03",
        amount: 500,
        currency: "USD",
        amount_usd: 500,
        credit_usd: 0,
        invoice_number: "vast-88213",
        issued_at: "2026-03-04",
        source: "label",
        file_ref: "",
        status: "parsed",
        ingested_at: "2026-07-03",
    },
    {
        sha256: "bb22cc33dd44ee55ff660011223344556677889900aabbccddeeff0011223344",
        provider: "openai",
        category: "compute",
        kind: "monthly_bill",
        period_month: "2026-01",
        amount: 226.4,
        currency: "USD",
        amount_usd: 226.4,
        credit_usd: 0,
        invoice_number: "OAI-2026-01",
        issued_at: "2026-02-01",
        source: "email",
        file_ref: "2026-01/openai_2026-01_bb22cc33_inv.pdf",
        status: "parsed",
        ingested_at: "2026-07-01",
    },
    {
        sha256: "dd44ee55ff660011223344556677889900aabbccddeeff0011223344556677aa",
        provider: "aws",
        category: "compute",
        kind: "monthly_bill",
        period_month: "2026-06",
        amount: 0,
        currency: "USD",
        amount_usd: 0,
        credit_usd: 1922.4,
        invoice_number: "AWS-2026-06",
        issued_at: "2026-07-01",
        source: "email",
        file_ref: "2026-06/aws_2026-06_dd44ee55_inv.pdf",
        status: "parsed",
        ingested_at: "2026-07-03",
    },
    {
        sha256: "cc33dd44ee55ff660011223344556677889900aabbccddeeff001122334455ff",
        provider: "other",
        category: "",
        kind: "",
        period_month: "",
        amount: 154.02,
        currency: "EUR",
        amount_usd: 0,
        credit_usd: 0,
        invoice_number: "",
        issued_at: "",
        source: "inbox",
        file_ref: "2026-07/other_2026-07_cc33dd44_notion.pdf",
        status: "needs_review",
        ingested_at: "2026-07-03",
    },
];

const grants: GrantRow[] = [
    {
        pool: "aws-activate",
        providers: "aws",
        kind: "credit",
        category: "compute",
        currency: "USD",
        granted_usd: 30000,
        granted_src: "api",
        left_usd: 4200.5,
        left_src: "api",
        prepaid_left_usd: null,
        prepaid_left_src: "",
        expires: "2026-12",
        note: "",
        run_at: "2026-07-03",
    },
    {
        pool: "azure-startup",
        providers: "azure",
        kind: "credit",
        category: "compute",
        currency: "USD",
        granted_usd: 250000,
        granted_src: "api",
        left_usd: 244600,
        left_src: "api",
        prepaid_left_usd: null,
        prepaid_left_src: "",
        expires: "2028-04",
        note: "Claude on Foundry bills outside credits",
        run_at: "2026-07-03",
    },
    {
        pool: "lambda-credit",
        providers: "lambda",
        kind: "credit",
        category: "compute",
        currency: "USD",
        granted_usd: 5000,
        granted_src: "hc",
        left_usd: 1200,
        left_src: "hc",
        prepaid_left_usd: null,
        prepaid_left_src: "",
        expires: "2026-12",
        note: "fixture editable grant",
        run_at: "2026-07-03",
    },
];

const cashMonthly: CashMonthlyRow[] = [
    {
        month: "2026-01",
        provider: "vast.ai",
        category: "compute",
        paid_usd: 480.19,
        paid_eur: 442.16,
    },
    {
        month: "2026-01",
        provider: "openai",
        category: "compute",
        paid_usd: 226.4,
        paid_eur: 208.37,
    },
    {
        month: "2026-03",
        provider: "scaleway",
        category: "compute",
        paid_usd: 0,
        paid_eur: 0,
    },
    {
        month: "2026-03",
        provider: "(unmatched)",
        category: "other",
        paid_usd: 81.18,
        paid_eur: 71.21,
    },
];

const providerMonths: ProviderMonthRow[] = [
    {
        month: "2026-06",
        provider: "aws",
        category: "compute",
        invoice_usd: 0,
        meter_cash_usd: 0,
        meter_prepaid_usd: 0,
        meter_src: "",
        usage_cost_usd: 1922.4,
        credit_burn_usd: 1922.4,
        credit_src: "invoice",
        status: "ok_credit",
    },
    {
        month: "2026-03",
        provider: "vast.ai",
        category: "compute",
        invoice_usd: 3481,
        meter_cash_usd: 0,
        meter_prepaid_usd: 0,
        meter_src: "",
        usage_cost_usd: 0,
        credit_burn_usd: 0,
        credit_src: "",
        status: "amount_mismatch",
    },
    {
        month: "2026-02",
        provider: "openai",
        category: "compute",
        invoice_usd: 254.1,
        meter_cash_usd: 254.1,
        meter_prepaid_usd: 0,
        meter_src: "api",
        usage_cost_usd: 254.1,
        credit_burn_usd: 0,
        credit_src: "",
        status: "ok",
    },
    {
        month: "2026-03",
        provider: "gcp",
        category: "compute",
        invoice_usd: 0,
        meter_cash_usd: 0,
        meter_prepaid_usd: 0,
        meter_src: "",
        usage_cost_usd: 1280.5,
        credit_burn_usd: 0,
        credit_src: "",
        status: "needs_data",
    },
];

const balances: BalanceRow[] = [
    {
        provider: "vast.ai",
        granted_usd: null,
        spent_usd: null,
        left_usd: null,
        prepaid_left_usd: 118.4,
        source: "api",
        note: "",
        last_run_at: "2026-07-03 06:37:02",
    },
    {
        provider: "openrouter",
        granted_usd: null,
        spent_usd: null,
        left_usd: 512.33,
        prepaid_left_usd: null,
        source: "api",
        note: "",
        last_run_at: "2026-07-03 06:37:02",
    },
    {
        provider: "ovhcloud",
        granted_usd: null,
        spent_usd: null,
        left_usd: 201.11,
        prepaid_left_usd: null,
        source: "api",
        note: "last run err: connection reset - showing previous value",
        last_run_at: "2026-07-02 06:31:44",
    },
];

const runs: RunRow[] = [
    {
        run_at: "2026-07-03 06:37:02",
        ok: 0,
        statuses:
            '{"wise":"ok","gmail":"ok","inbox":"ok","vast.ai":"ok","runpod":"ok","ovhcloud":"err: connection reset by peer","digitalocean":"err: 403 role-gated"}',
        notes: "ovhcloud balance: kept last good value",
    },
    {
        run_at: "2026-07-02 06:31:44",
        ok: 1,
        statuses:
            '{"wise":"ok","gmail":"ok","inbox":"ok","vast.ai":"ok","runpod":"ok","ovhcloud":"ok","digitalocean":"err: 403 role-gated"}',
        notes: "",
    },
];

export const FIXTURES: Record<string, unknown[]> = {
    coverage_ep: coverage,
    gaps_ep: gaps,
    invoices_ep: invoices,
    cash_monthly_ep: cashMonthly,
    grants_ep: grants,
    balances_ep: balances,
    provider_month_ep: providerMonths,
    runs_ep: runs,
};
