import type { OpCloudRow, OpPollenRow, OpTransactionRow } from "./types";

const opTransactions: OpTransactionRow[] = [
    {
        source: "wise",
        date: "2026-06-30",
        vendor: "stripe",
        category: "revenue",
        amount: 1128,
        currency: "EUR",
        description: "Stripe net cash settlement",
        evidence: "",
        recorded_at: "2026-07-09 00:00:00",
    },
    {
        source: "wise",
        date: "2026-06-01",
        vendor: "alibaba",
        category: "cloud",
        amount: -139.31,
        currency: "EUR",
        description: "Alibaba Cloud",
        evidence: "",
        recorded_at: "2026-07-09 00:00:00",
    },
    {
        source: "wise",
        date: "2026-06-13",
        vendor: "elevenlabs",
        category: "cloud",
        amount: -275.06,
        currency: "EUR",
        description: "ElevenLabs",
        evidence: "",
        recorded_at: "2026-07-09 00:00:00",
    },
    {
        source: "wise",
        date: "2026-06-20",
        vendor: "tinybird",
        category: "cloud",
        amount: -34.74,
        currency: "EUR",
        description: "Tinybird",
        evidence: "",
        recorded_at: "2026-07-09 00:00:00",
    },
    {
        source: "wise",
        date: "2026-06-27",
        vendor: "",
        category: "admin",
        amount: -45.2,
        currency: "EUR",
        description: "Unmatched admin charge",
        evidence: "",
        recorded_at: "2026-07-09 00:00:00",
    },
    {
        source: "wise",
        date: "2026-05-31",
        vendor: "stripe",
        category: "revenue",
        amount: 9451.35,
        currency: "EUR",
        description: "Stripe net cash settlement",
        evidence: "",
        recorded_at: "2026-07-09 00:00:00",
    },
    {
        source: "wise",
        date: "2026-05-25",
        vendor: "deel",
        category: "payroll",
        amount: -8015.44,
        currency: "EUR",
        description: "Deel payroll",
        evidence: "",
        recorded_at: "2026-07-09 00:00:00",
    },
    {
        source: "wise",
        date: "2026-05-12",
        vendor: "google",
        category: "cloud",
        amount: -3399.05,
        currency: "EUR",
        description: "Google Cloud",
        evidence: "",
        recorded_at: "2026-07-09 00:00:00",
    },
];
const opCloud: OpCloudRow[] = [];
const opPollen: OpPollenRow[] = [];

export const FIXTURES: Record<string, unknown[]> = {
    op_transactions_api: opTransactions,
    op_cloud_api: opCloud,
    op_pollen_api: opPollen,
};
