import type {
    OpCloudRow,
    OpPollenRow,
    OpRunwayRow,
    OpTransactionRow,
} from "./types";

// Demo-only rows. Every amount is a deliberately round, invented value —
// never copy real ledger figures in here: fixtures ship in the public bundle
// before authentication.
const opTransactions: OpTransactionRow[] = [
    {
        entry_id: "wise-example-stripe-2026-06-30",
        source: "wise",
        date: "2026-06-30",
        vendor: "stripe",
        category: "revenue",
        amount: 1_000,
        currency: "EUR",
        description: "Example Stripe settlement",
        evidence: "",
        recorded_at: "2026-07-09 00:00:00.000",
    },
    {
        entry_id: "wise-example-alibaba-2026-06-01",
        source: "wise",
        date: "2026-06-01",
        vendor: "alibaba",
        category: "cloud",
        amount: -150,
        currency: "EUR",
        description: "Example Alibaba Cloud charge",
        evidence: "",
        recorded_at: "2026-07-09 00:00:00.000",
    },
    {
        entry_id: "wise-example-elevenlabs-2026-06-13",
        source: "wise",
        date: "2026-06-13",
        vendor: "elevenlabs",
        category: "cloud",
        amount: -250,
        currency: "EUR",
        description: "Example ElevenLabs charge",
        evidence: "",
        recorded_at: "2026-07-09 00:00:00.000",
    },
    {
        entry_id: "wise-example-tinybird-2026-06-20",
        source: "wise",
        date: "2026-06-20",
        vendor: "tinybird",
        category: "cloud",
        amount: -50,
        currency: "EUR",
        description: "Example Tinybird charge",
        evidence: "",
        recorded_at: "2026-07-09 00:00:00.000",
    },
    {
        entry_id: "wise-example-unmatched-2026-06-27",
        source: "wise",
        date: "2026-06-27",
        vendor: "",
        category: "admin",
        amount: -40,
        currency: "EUR",
        description: "Example unmatched admin charge",
        evidence: "",
        recorded_at: "2026-07-09 00:00:00.000",
    },
    {
        entry_id: "wise-example-stripe-2026-05-31",
        source: "wise",
        date: "2026-05-31",
        vendor: "stripe",
        category: "revenue",
        amount: 9_000,
        currency: "EUR",
        description: "Example Stripe settlement",
        evidence: "",
        recorded_at: "2026-07-09 00:00:00.000",
    },
    {
        entry_id: "wise-example-deel-2026-05-25",
        source: "wise",
        date: "2026-05-25",
        vendor: "deel",
        category: "payroll",
        amount: -8_000,
        currency: "EUR",
        description: "Example Deel payroll",
        evidence: "",
        recorded_at: "2026-07-09 00:00:00.000",
    },
    {
        entry_id: "wise-example-google-2026-05-12",
        source: "wise",
        date: "2026-05-12",
        vendor: "google",
        category: "cloud",
        amount: -3_000,
        currency: "EUR",
        description: "Example Google Cloud charge",
        evidence: "",
        recorded_at: "2026-07-09 00:00:00.000",
    },
];
const opCloud: OpCloudRow[] = [];
const opPollen: OpPollenRow[] = [];
const runwayMonths = [
    "2026-07",
    "2026-08",
    "2026-09",
    "2026-10",
    "2026-11",
    "2026-12",
];
const opRunway: OpRunwayRow[] = [
    {
        entry_id: "opening-balance-2026-07",
        kind: "opening_balance",
        date: "2026-07-01",
        vendor: "",
        category: "",
        amount: 30_000,
        currency: "USD",
        source: "manual",
        evidence: "Example opening balance",
        recorded_at: "2026-07-10 09:00:00.000",
    },
    ...runwayMonths.flatMap((month) => [
        {
            entry_id: `forecast-${month}-stripe`,
            kind: "forecast",
            date: `${month}-01`,
            vendor: "stripe",
            category: "revenue",
            amount: 9_000,
            currency: "USD",
            source: "agent",
            evidence: "Base revenue plan",
            recorded_at: "2026-07-10 09:00:00.000",
        },
        {
            entry_id: `forecast-${month}-deel`,
            kind: "forecast",
            date: `${month}-01`,
            vendor: "deel",
            category: "payroll",
            amount: -8_000,
            currency: "USD",
            source: "manual",
            evidence: "Approved payroll plan",
            recorded_at: "2026-07-10 09:00:00.000",
        },
        {
            entry_id: `forecast-${month}-google`,
            kind: "forecast",
            date: `${month}-01`,
            vendor: "google",
            category: "cloud",
            amount: -3_000,
            currency: "USD",
            source: "agent",
            evidence: "Approved cloud plan",
            recorded_at: "2026-07-10 09:00:00.000",
        },
        {
            entry_id: `forecast-${month}-tools`,
            kind: "forecast",
            date: `${month}-01`,
            vendor: "tools",
            category: "saas",
            amount: -1_000,
            currency: "USD",
            source: "agent",
            evidence: "Recurring software plan",
            recorded_at: "2026-07-10 09:00:00.000",
        },
    ]),
    {
        entry_id: "forecast-2026-09-tax",
        kind: "forecast",
        date: "2026-09-01",
        vendor: "tax office",
        category: "admin",
        amount: -6_000,
        currency: "USD",
        source: "manual",
        evidence: "One-time tax payment",
        recorded_at: "2026-07-10 09:00:00.000",
    },
];

export const FIXTURES: Record<string, unknown[]> = {
    op_transactions_api: opTransactions,
    op_cloud_api: opCloud,
    op_pollen_api: opPollen,
    op_runway_api: opRunway,
};
