import type {
    EconomicsPrivateConfig,
    EconomicsPrivateConfigRow,
    OpCloudRow,
    OpPollenRow,
    OpTransactionRow,
} from "./types";

export const PRIVATE_CONFIG_FIXTURE: EconomicsPrivateConfig = {
    forecastRules: {
        "openai|development": {
            fixedAmounts: [{ amount: -90, currency: "USD" }],
        },
    },
    reconciliation: {
        providerCheckExplanations: [
            {
                month: "2026-03",
                provider: "pruna",
                reason: "unverifiable_history",
                explanation: "Example reviewed limitation.",
                evidence: [
                    "https://drive.google.com/file/d/example-check/view",
                ],
            },
        ],
        meterDriftExplanations: [
            {
                month: "2026-03",
                provider: "anthropic",
                reason: "historical_tracking_gap",
                explanation: "Example reviewed meter gap.",
                evidence: [
                    "https://drive.google.com/file/d/example-drift/view",
                ],
            },
        ],
        pollenWitnessExplanations: [
            {
                month: "2026-02",
                provider: "vast.ai",
                reason: "provider_attribution_transition",
                explanation: "Example reviewed transition.",
                evidence: [
                    "https://drive.google.com/file/d/example-witness/view",
                ],
            },
            {
                month: "2026-02",
                provider: "pruna",
                reason: "unverifiable_history",
                explanation: "Example reviewed residual.",
                evidence: [
                    "https://drive.google.com/file/d/example-residual/view",
                ],
            },
        ],
    },
};

// Demo-only rows. Every amount is a deliberately round, invented value —
// never copy real ledger figures in here: fixtures ship in the public bundle
// before authentication.
const opTransactions: OpTransactionRow[] = [
    {
        entry_id: "wise-example-opening-2026-01-eur",
        kind: "opening_balance",
        source: "wise",
        date: "2026-01-01",
        vendor: "wise",
        category: "balance_sheet",
        amount: 30_000,
        currency: "EUR",
        description: "Example statement opening balance",
        evidence: "Example Wise statement",
        recorded_at: "2026-07-09 00:00:00.000",
    },
    {
        entry_id: "wise-example-stripe-2026-08-22",
        kind: "transaction",
        source: "wise",
        date: "2026-08-22",
        vendor: "stripe",
        category: "revenue",
        amount: 2_000,
        currency: "EUR",
        description: "Example partial-month Stripe settlement",
        evidence: "",
        recorded_at: "2026-08-22 00:00:00.000",
    },
    {
        entry_id: "wise-example-stripe-2026-07-31",
        kind: "transaction",
        source: "wise",
        date: "2026-07-31",
        vendor: "stripe",
        category: "revenue",
        amount: 9_000,
        currency: "EUR",
        description: "Example Stripe settlement",
        evidence: "",
        recorded_at: "2026-08-01 00:00:00.000",
    },
    {
        entry_id: "wise-example-stripe-2026-06-30",
        kind: "transaction",
        source: "wise",
        date: "2026-06-30",
        vendor: "stripe",
        category: "revenue",
        amount: 1_000,
        currency: "EUR",
        description: "Example Stripe settlement",
        evidence:
            "https://drive.google.com/drive/folders/example-stripe-folder",
        recorded_at: "2026-07-09 00:00:00.000",
    },
    {
        entry_id: "wise-example-alibaba-2026-06-01",
        kind: "transaction",
        source: "wise",
        date: "2026-06-01",
        vendor: "alibaba",
        category: "cloud",
        amount: -150,
        currency: "EUR",
        description: "Example Alibaba Cloud charge",
        evidence: "https://drive.google.com/file/d/example-invoice/view",
        recorded_at: "2026-07-09 00:00:00.000",
    },
    {
        entry_id: "wise-example-elevenlabs-2026-06-13",
        kind: "transaction",
        source: "wise",
        date: "2026-06-13",
        vendor: "elevenlabs",
        category: "cloud",
        amount: -250,
        currency: "EUR",
        description: "Example ElevenLabs charge",
        evidence: "",
        recorded_at: "2026-07-09 00:00:00.000",
    },
    {
        entry_id: "wise-example-tinybird-2026-06-20",
        kind: "transaction",
        source: "wise",
        date: "2026-06-20",
        vendor: "tinybird",
        category: "cloud",
        amount: -50,
        currency: "EUR",
        description: "Example Tinybird charge",
        evidence: "",
        recorded_at: "2026-07-09 00:00:00.000",
    },
    {
        entry_id: "wise-example-unmatched-2026-06-27",
        kind: "transaction",
        source: "wise",
        date: "2026-06-27",
        vendor: "",
        category: "admin",
        amount: -40,
        currency: "EUR",
        description: "Example unmatched admin charge",
        evidence: "",
        recorded_at: "2026-07-09 00:00:00.000",
    },
    {
        entry_id: "wise-example-stripe-2026-05-31",
        kind: "transaction",
        source: "wise",
        date: "2026-05-31",
        vendor: "stripe",
        category: "revenue",
        amount: 9_000,
        currency: "EUR",
        description: "Example Stripe settlement",
        evidence: "",
        recorded_at: "2026-07-09 00:00:00.000",
    },
    {
        entry_id: "wise-example-deel-2026-05-25",
        kind: "transaction",
        source: "wise",
        date: "2026-05-25",
        vendor: "deel",
        category: "payroll",
        amount: -8_000,
        currency: "EUR",
        description: "Example Deel payroll",
        evidence: "",
        recorded_at: "2026-07-09 00:00:00.000",
    },
    {
        entry_id: "wise-example-google-2026-05-12",
        kind: "transaction",
        source: "wise",
        date: "2026-05-12",
        vendor: "google",
        category: "cloud",
        amount: -3_000,
        currency: "EUR",
        description: "Example Google Cloud charge",
        evidence: "",
        recorded_at: "2026-07-09 00:00:00.000",
    },
    {
        entry_id: "wise-example-stripe-2026-04-30",
        kind: "transaction",
        source: "wise",
        date: "2026-04-30",
        vendor: "stripe",
        category: "revenue",
        amount: 8_000,
        currency: "EUR",
        description: "Example Stripe settlement",
        evidence: "",
        recorded_at: "2026-05-01 00:00:00.000",
    },
    {
        entry_id: "wise-example-stripe-2026-03-31",
        kind: "transaction",
        source: "wise",
        date: "2026-03-31",
        vendor: "stripe",
        category: "revenue",
        amount: 7_000,
        currency: "EUR",
        description: "Example Stripe settlement",
        evidence: "",
        recorded_at: "2026-04-01 00:00:00.000",
    },
    {
        entry_id: "wise-example-stripe-2026-02-28",
        kind: "transaction",
        source: "wise",
        date: "2026-02-28",
        vendor: "stripe",
        category: "revenue",
        amount: 6_000,
        currency: "EUR",
        description: "Example Stripe settlement",
        evidence: "",
        recorded_at: "2026-03-01 00:00:00.000",
    },
];
const opCloud: OpCloudRow[] = [
    {
        entry_id: "cloud-example-openai-inference-2026-07",
        source: "dashboard",
        vendor: "openai",
        type: "inference",
        start: "2026-07-01",
        end: "2026-07-31",
        credit: -50,
        paid: -50,
        currency: "USD",
        resource_id: "example-openai",
        resource_name: "Example managed inference",
        resource_sku: "",
        resource_count: 0,
        model: "Example model",
        evidence: "Example dashboard record",
        recorded_at: "2026-08-01 00:00:00.000",
    },
    {
        entry_id: "cloud-example-vast-gpu-2026-07",
        source: "dashboard",
        vendor: "vast.ai",
        type: "gpu",
        start: "2026-07-01",
        end: "2026-07-31",
        credit: -50,
        paid: -50,
        currency: "USD",
        resource_id: "example-gpu",
        resource_name: "Example GPU capacity",
        resource_sku: "RTX example",
        resource_count: 1,
        model: "zimage",
        evidence: "Example dashboard record",
        recorded_at: "2026-08-01 00:00:00.000",
    },
    {
        entry_id: "cloud-example-modal-inference-2026-07",
        source: "dashboard",
        vendor: "modal",
        type: "inference",
        start: "2026-07-01",
        end: "2026-07-31",
        credit: 0,
        paid: -20,
        currency: "USD",
        resource_id: "example-modal-api",
        resource_name: "Example mixed inference",
        resource_sku: "",
        resource_count: 0,
        model: "Example mixed model",
        evidence: "Example dashboard record",
        recorded_at: "2026-08-01 00:00:00.000",
    },
    {
        entry_id: "cloud-example-modal-gpu-2026-07",
        source: "dashboard",
        vendor: "modal",
        type: "gpu",
        start: "2026-07-01",
        end: "2026-07-31",
        credit: -10,
        paid: -10,
        currency: "USD",
        resource_id: "example-modal-gpu",
        resource_name: "Example mixed GPU",
        resource_sku: "GPU example",
        resource_count: 1,
        model: "Example mixed model",
        evidence: "Example dashboard record",
        recorded_at: "2026-08-01 00:00:00.000",
    },
    {
        entry_id: "cloud-example-openai-inference-2026-06",
        source: "dashboard",
        vendor: "openai",
        type: "inference",
        start: "2026-06-01",
        end: "2026-06-30",
        credit: -40,
        paid: -60,
        currency: "USD",
        resource_id: "example-openai",
        resource_name: "Example managed inference",
        resource_sku: "",
        resource_count: 0,
        model: "Example model",
        evidence: "Example dashboard record",
        recorded_at: "2026-07-01 00:00:00.000",
    },
    {
        entry_id: "cloud-example-vast-gpu-2026-06",
        source: "dashboard",
        vendor: "vast.ai",
        type: "gpu",
        start: "2026-06-01",
        end: "2026-06-30",
        credit: -50,
        paid: -50,
        currency: "USD",
        resource_id: "example-gpu",
        resource_name: "Example GPU capacity",
        resource_sku: "RTX example",
        resource_count: 1,
        model: "zimage",
        evidence: "Example dashboard record",
        recorded_at: "2026-07-01 00:00:00.000",
    },
    {
        entry_id: "cloud-example-modal-inference-2026-06",
        source: "dashboard",
        vendor: "modal",
        type: "inference",
        start: "2026-06-01",
        end: "2026-06-30",
        credit: 0,
        paid: -20,
        currency: "USD",
        resource_id: "example-modal-api",
        resource_name: "Example mixed inference",
        resource_sku: "",
        resource_count: 0,
        model: "Example mixed model",
        evidence: "Example dashboard record",
        recorded_at: "2026-07-01 00:00:00.000",
    },
    {
        entry_id: "cloud-example-modal-gpu-2026-06",
        source: "dashboard",
        vendor: "modal",
        type: "gpu",
        start: "2026-06-01",
        end: "2026-06-30",
        credit: -10,
        paid: -10,
        currency: "USD",
        resource_id: "example-modal-gpu",
        resource_name: "Example mixed GPU",
        resource_sku: "GPU example",
        resource_count: 1,
        model: "Example mixed model",
        evidence: "Example dashboard record",
        recorded_at: "2026-07-01 00:00:00.000",
    },
];
const opPollen: OpPollenRow[] = [
    {
        month: "2026-07",
        vendor: "openai",
        model: "example-inference-model",
        currency: "USD",
        cost_paid: 75,
        cost_quests: 25,
        price_paid: 150,
        price_quests: 50,
        byop_paid: 0,
        byop_quests: 0,
        model_paid: 0,
        model_quests: 0,
        requests_paid: 750,
        requests_quests: 250,
    },
    {
        month: "2026-07",
        vendor: "vast.ai",
        model: "zimage",
        currency: "USD",
        cost_paid: 80,
        cost_quests: 20,
        price_paid: 120,
        price_quests: 30,
        byop_paid: 0,
        byop_quests: 0,
        model_paid: 0,
        model_quests: 0,
        requests_paid: 800,
        requests_quests: 200,
    },
    {
        month: "2026-07",
        vendor: "modal",
        model: "example-mixed-model",
        currency: "USD",
        cost_paid: 20,
        cost_quests: 10,
        price_paid: 30,
        price_quests: 10,
        byop_paid: 0,
        byop_quests: 0,
        model_paid: 0,
        model_quests: 0,
        requests_paid: 200,
        requests_quests: 100,
    },
    {
        month: "2026-07",
        vendor: "community",
        model: "example-community-model",
        currency: "USD",
        cost_paid: 0,
        cost_quests: 0,
        price_paid: 100,
        price_quests: 50,
        byop_paid: 0,
        byop_quests: 0,
        model_paid: 80,
        model_quests: 40,
        requests_paid: 500,
        requests_quests: 250,
    },
    {
        month: "2026-06",
        vendor: "openai",
        model: "example-inference-model",
        currency: "USD",
        cost_paid: 75,
        cost_quests: 25,
        price_paid: 150,
        price_quests: 50,
        byop_paid: 0,
        byop_quests: 0,
        model_paid: 0,
        model_quests: 0,
        requests_paid: 750,
        requests_quests: 250,
    },
    {
        month: "2026-06",
        vendor: "vast.ai",
        model: "zimage",
        currency: "USD",
        cost_paid: 80,
        cost_quests: 20,
        price_paid: 120,
        price_quests: 30,
        byop_paid: 0,
        byop_quests: 0,
        model_paid: 0,
        model_quests: 0,
        requests_paid: 800,
        requests_quests: 200,
    },
    {
        month: "2026-06",
        vendor: "modal",
        model: "example-mixed-model",
        currency: "USD",
        cost_paid: 20,
        cost_quests: 10,
        price_paid: 30,
        price_quests: 10,
        byop_paid: 0,
        byop_quests: 0,
        model_paid: 0,
        model_quests: 0,
        requests_paid: 200,
        requests_quests: 100,
    },
    {
        month: "2026-06",
        vendor: "community",
        model: "example-community-model",
        currency: "USD",
        cost_paid: 0,
        cost_quests: 0,
        price_paid: 100,
        price_quests: 50,
        byop_paid: 0,
        byop_quests: 0,
        model_paid: 80,
        model_quests: 40,
        requests_paid: 500,
        requests_quests: 250,
    },
];
const privateConfig: EconomicsPrivateConfigRow[] = [
    {
        config: JSON.stringify(PRIVATE_CONFIG_FIXTURE),
        recorded_at: "2026-01-01 00:00:00.000",
    },
];
export const FIXTURES: Record<string, unknown[]> = {
    economics_bank_ledger_api: opTransactions,
    economics_compute_ledger_api: opCloud,
    economics_pollen_usage_api: opPollen,
    economics_private_config_api: privateConfig,
};
