/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --env-interface CloudflareBindings worker-bindings.d.ts --env production` (hash: ca2417ddc00c9652d0e6e7261fcd7f6f)
declare namespace Cloudflare {
    interface GlobalProps {
        mainModule: typeof import("./src/index");
    }
    interface Env {
        KV: KVNamespace;
        ENVIRONMENT: "local" | "production" | "staging";
        LOG_LEVEL: "trace" | "debug";
        LOG_FORMAT: "text" | "json";
        IMAGE_SERVICE_URL:
            | "http://localhost:16384"
            | "http://ec2-54-147-14-220.compute-1.amazonaws.com:16384";
        TEXT_SERVICE_URL:
            | "http://localhost:16385"
            | "http://ec2-54-147-14-220.compute-1.amazonaws.com:16385";
        MUSIC_SERVICE_URL: "";
        TINYBIRD_INGEST_URL: "https://api.europe-west2.gcp.tinybird.co/v0/events?name=generation_event";
        TINYBIRD_TIER_INGEST_URL: "https://api.europe-west2.gcp.tinybird.co/v0/events?name=tier_event";
        POLLEN_REFILL_PER_HOUR: 1;
        BETTER_AUTH_SECRET: "";
        GITHUB_CLIENT_ID: "";
        GITHUB_CLIENT_SECRET: "";
        TINYBIRD_INGEST_TOKEN: "";
        PLN_GPU_TOKEN: "";
        PLN_ENTER_TOKEN: "";
        DASHSCOPE_API_KEY: "";
        OVHCLOUD_API_KEY: "";
        POLLEN_RATE_LIMITER: DurableObjectNamespace /* PollenRateLimiter from pollinations-enter-production */;
        IMAGE_BUCKET: R2Bucket;
        TEXT_BUCKET: R2Bucket;
        DB: D1Database;
        EDGE_RATE_LIMITER: RateLimit;
        ENTER: Fetcher /* pollinations-enter-production */;
    }
}
interface CloudflareBindings extends Cloudflare.Env {}
