/* eslint-disable */
// Generated by Wrangler by running `wrangler types --env-file /var/folders/nk/48zb93yj5kj0rwrdg4t3qsj40000gn/T/.sops3005382351/tmp-file1395836728 --include-runtime=false --env-interface CloudflareBindings worker-bindings.d.ts --env staging` (hash: 90229b4033050c37714f2993624c558b)
declare namespace Cloudflare {
    interface GlobalProps {
        mainModule: typeof import("./src/index");
    }
    interface Env {
        KV: KVNamespace;
        ENVIRONMENT: "local" | "production" | "staging";
        LOG_LEVEL: "trace" | "debug";
        LOG_FORMAT: "text" | "json";
        IMAGE_SERVICE_URL:
            | "http://localhost:16384"
            | "http://ec2-54-147-14-220.compute-1.amazonaws.com:16384";
        TEXT_SERVICE_URL:
            | "http://localhost:16385"
            | "http://ec2-54-147-14-220.compute-1.amazonaws.com:16385";
        TINYBIRD_INGEST_URL: "https://api.europe-west2.gcp.tinybird.co/v0/events?name=generation_event";
        TINYBIRD_TIER_INGEST_URL: "https://api.europe-west2.gcp.tinybird.co/v0/events?name=tier_event";
        POLLEN_REFILL_PER_HOUR: 1;
        BETTER_AUTH_SECRET: string;
        GITHUB_CLIENT_ID: string;
        GITHUB_CLIENT_SECRET: string;
        PLN_ENTER_TOKEN: string;
        POLAR_ACCESS_TOKEN: string;
        STRIPE_SECRET_KEY: string;
        STRIPE_WEBHOOK_SECRET: string;
        TINYBIRD_READ_TOKEN: string;
        POLAR_WEBHOOK_SECRET: string;
        ELEVENLABS_API_KEY: string;
        OVHCLOUD_API_KEY: string;
        PLN_GPU_TOKEN: string;
        MUSIC_SERVICE_URL: string;
        SSH_RUNPOD_KLEIN: string;
        SSH_RUNPOD_FLUX_ZIMAGE: string;
        SSH_LAMBDA_SANA_LTX2_ACESTEP: string;
        TINYBIRD_INGEST_TOKEN: string;
        TINYBIRD_SYNC_TOKEN: string;
        DASHSCOPE_API_KEY: string;
        POLLEN_RATE_LIMITER: DurableObjectNamespace /* PollenRateLimiter from pollinations-enter-staging */;
        IMAGE_BUCKET: R2Bucket;
        TEXT_BUCKET: R2Bucket;
        DB: D1Database;
        EDGE_RATE_LIMITER: RateLimit;
        ENTER: Fetcher /* pollinations-enter-staging */;
    }
}
interface CloudflareBindings extends Cloudflare.Env {}
