export const GIFT_PAGE = {
    pageTitle: "gift pollen",
    pageDescription:
        "Buy a Pollen gift code for someone to redeem into their Pollinations wallet.",
    title: "Gift Pollen",
    intro: "Choose a value and buy a single-use code for someone else. No account is needed to purchase. Find your gift code on the invoice emailed after payment.",
    amountLabel: "Select gift amount",
    pollenNote: "1 Pollen is approximately $1 USD.",
    buyButton: "Buy gift",
    openingButton: "Opening...",
    feePrefix: "incl.",
    feeSuffix: "fee",
    secureCheckout: "Secure checkout powered by Stripe",
    taxNote: "Prices exclude tax — VAT or sales tax is added at checkout.",
    refundNote: "Redeemed gift codes are non-refundable.",
    termsLabel: "Terms",
    refundsLabel: "Refund",
    redeemPrompt: "Already have a code?",
    redeemLink: "Redeem it",
    checkoutError: "We couldn't start checkout. Please try again.",
};
