/**
 * List of NSFW keywords for first-pass detection
 * Organized by language for better maintainability
 */
const nsfwKeywordsDating = [
  // English
  'girlfriend', 'boyfriend', 'partner', 'significant other', 'companion', 'bae', 'boo', 'hubby', 'wifey', 'lover', 'crush', 'situationship', 'exclusive', 'taken', 'commitment', 'couple goals', 'love', 'romantic', 'romance', 'lovey-dovey', 'butterflies', 'infatuated', 'puppy love', 'smitten', 'head over heels', 'falling for', 'heart eyes', 'lovestruck', 'sweetheart', 'flirt', 'flirting', 'kiss', 'kissing', 'smooch', 'cuddle', 'cuddling', 'snuggle', 'PDA', 'hold hands', 'spooning', 'hugging', 'sweet talk', 'whisper sweet nothings', 'courtship', 'date', 'dating', 'date night', 'Netflix and chill', 'swipe right', 'match', 'ghosting', 'DM slide', 'talking stage', 'first base', 'second base', 'beautiful', 'handsome', 'sexy', 'cutie', 'babe', 'baby', 'hun', 'honey', 'darling', 'gorgeous', 'stunning', 'foxy', 'snack', 'hot stuff', 'dreamboat', 'hottie', 'intimate', 'NSFW', 'erotic', 'adult', 'naughty', 'spicy', 'seduce', 'seduction', 'steamy', 'risqué', 'sensual', 'passionate', 'turn-on', 'foreplay', 'hook up', 'FWB', 'ship', 'shipping', 'OTP', 'simp', 'simping', 'thirsty', 'goals', 'stan', 'relationship', 'roleplay', '❤️', '🧡', '💛', '💚', '💙', '💜', '🖤', '🤍', '🤎', '💔', '❣️', '💕', '💞', '💓', '💗', '💖', '💘', '💝', '💟', '😍', '🥰', '😘', '😚', '🔥', '🌹', '😏', '🍆', '🍑',

  // Russian
  'подруга', 'знакомства', 'отношения', 'романтика', 'интим',
  'любовь', 'спутник', 'ролевая игра', 'для взрослых', 'эротика',
  'свидание', 'поцелуй', 'флирт',

  // German
  'freundin', 'dating', 'beziehung', 'romantik', 'intim',
  'liebe', 'begleiter', 'rollenspiel', 'erotisch', 'erwachsene',
  'kuss', 'flirt', 'date',

  // French
  'petite amie', 'rencontre', 'relation', 'romance', 'intime',
  'amour', 'compagnon', 'jeu de rôle', 'érotique', 'adulte',
  'baiser', 'flirt', 'rendez-vous',

  // Hindi
  'गर्लफ्रेंड', 'डेटिंग', 'रिश्ता', 'रोमांस', 'प्रेम',
  'प्यार', 'साथी', 'रोल प्ले', 'वयस्क', 'कामुक',
  'चुंबन', 'फ्लर्ट',

  // Portuguese
  'namorada', 'namoro', 'relacionamento', 'romance', 'íntimo',
  'amor', 'companheiro', 'roleplay', 'erótico', 'adulto',
  'beijo', 'paquera', 'encontro',

  // Indonesian
  'pacar', 'kencan', 'hubungan', 'romansa', 'intim',
  'cinta', 'teman', 'roleplay', 'dewasa', 'erotis',
  'ciuman', 'goda', 'date',

  // Italian
  'fidanzata', 'incontri', 'relazione', 'romantico', 'intimo',
  'amore', 'compagno', 'gioco di ruolo', 'erotico', 'adulto',
  'bacio', 'flirt', 'appuntamento'
]; 


const words = [
  "anal",
  "analprobe",
  "anilingus",
  "anus",
  "areola",
  "areole",
  "ass",
  "assbang",
  "assbanged",
  "assbangs",
  "asses",
  "assfuck",
  "assfucker",
  "assh0le",
  "asshat",
  "assho1e",
  "ass hole",
  "assholes",
  "assmaster",
  "assmunch",
  "asswipe",
  "asswipes",
  "azz",
  "b1tch",
  "ballsack",
  "bang",
  "banger",
  "beardedclam",
  "beastiality",
  "beatch",
  "beater",
  "beaver",
  "biatch",
  "bigtits",
  "big tits",
  "bimbo",
  "bitch",
  "bitched",
  "bitches",
  "bitchy",
  "blow job",
  "blow",
  "blowjob",
  "blowjobs",
  "boink",
  "bollock",
  "bollocks",
  "bollok",
  "bone",
  "boned",
  "boner",
  "boners",
  "boob",
  "boobies",
  "boobs",
  "booby",
  "booty",
  "bosom",
  "bosomy",
  "bra",
  "brassiere",
  "breast",
  "breasts",
  "bukkake",
  "bung",
  "busty",
  "butt",
  "butt fuck",
  "buttfuck",
  "buttfucker",
  "buttplug",
  "c.0.c.k",
  "c.o.c.k.",
  "c.u.n.t",
  "c0ck",
  "c-0-c-k",
  "cameltoe",
  "carpetmuncher",
  "cawk",
  "cervix",
  "chinc",
  "chincs",
  "chode",
  "chodes",
  "cl1t",
  "climax",
  "clit",
  "clitoris",
  "clitorus",
  "clits",
  "clitty",
  "cock",
  "c-o-c-k",
  "cockblock",
  "cockholster",
  "cockknocker",
  "cocks",
  "cocksmoker",
  "cocksucker",
  "cock sucker",
  "coital",
  "condom",
  "coon",
  "coons",
  "corksucker",
  "crabs",
  "cum",
  "cummin",
  "cumming",
  "cumshot",
  "cumshots",
  "cumslut",
  "cumstain",
  "cunilingus",
  "cunnilingus",
  "cunny",
  "cunt",
  "c-u-n-t",
  "cuntface",
  "cunthunter",
  "cuntlick",
  "cuntlicker",
  "cunts",
  "d0ng",
  "d0uch3",
  "d0uche",
  "d1ck",
  "d1ld0",
  "d1ldo",
  "dick",
  "dickbag",
  "dickdipper",
  "dickface",
  "dickflipper",
  "dickhead",
  "dickheads",
  "dickish",
  "dick-ish",
  "dickripper",
  "dicksipper",
  "dickweed",
  "dickwhipper",
  "dickzipper",
  "diddle",
  "dike",
  "dildo",
  "dildos",
  "doggie-style",
  "doggy-style",
  "dong",
  "ejaculate",
  "enlargement",
  "erect",
  "erection",
  "erotic",
  "extacy",
  "extasy",
  "f.u.c.k",
  "fag",
  "fagg",
  "fagged",
  "faggit",
  "faggot",
  "fagot",
  "fags",
  "faig",
  "faigt",
  "fannybandit",
  "felch",
  "felcher",
  "felching",
  "fellate",
  "fellatio",
  "feltch",
  "feltcher",
  "fisted",
  "fisting",
  "fisty",
  "floozy",
  "fondle",
  "foreskin",
  "fuck",
  "f-u-c-k",
  "fuckass",
  "fucked",
  "fucker",
  "fuckface",
  "fuckin",
  "fucking",
  "fucknugget",
  "fucknut",
  "fuckoff",
  "fucks",
  "fucktard",
  "fuck-tard",
  "fuckup",
  "fuckwad",
  "fuckwit",
  "fudgepacker",
  "fuk",
  "fvck",
  "fxck",
  "g-spot",
  "gay",
  "gays",
  "gigolo",
  "glans",
  "goatse",
  "goldenshower",
  "gonad",
  "gonads",
  "gspot",
  "handjob",
  "hard on",
  "homo",
  "homoey",
  "honky",
  "hooker",
  "hooter",
  "hooters",
  "horny",
  "hump",
  "humped",
  "humping",
  "hussy",
  "hymen",
  "inbred",
  "incest",
  "j3rk0ff",
  "jackoff",
  "jerk",
  "jerk0ff",
  "jerked",
  "jerkoff",
  "jism",
  "jiz",
  "jizm",
  "jizz",
  "jizzed",
  "kooch",
  "kooches",
  "kootch",
  "labia",
  "lesbians",
  "lesbo",
  "lesbos",
  "lez",
  "lezbian",
  "lezbians",
  "lezbo",
  "lezbos",
  "lezzie",
  "lezzies",
  "lezzy",
  "loin",
  "loins",
  "lube",
  "lusty",
  "mams",
  "masterbate",
  "masterbating",
  "masterbation",
  "masturbate",
  "masturbating",
  "masturbation",
  "maxi",
  "menses",
  "menstruate",
  "menstruation",
  "m-fucking",
  "mofo",
  "molest",
  "motherfucka",
  "motherfucker",
  "motherfucking",
  "mtherfucker",
  "mthrfucker",
  "mthrfucking",
  "muff",
  "muffdiver",
  "muthafuckaz",
  "muthafucker",
  "mutherfucker",
  "mutherfucking",
  "muthrfucking",
  "nad",
  "nads",
  "naked",
  "nappy",
  "nipple",
  "nooky",
  "nympho",
  "opiate",
  "opium",
  "oral",
  "orally",
  "organ",
  "orgasm",
  "orgasmic",
  "orgies",
  "orgy",
  "ovary",
  "ovum",
  "ovums",
  "p.u.s.s.y.",
  "pantie",
  "panties",
  "panty",
  "pastie",
  "pasty",
  "pecker",
  "pedo",
  "pedophile",
  "pedophilia",
  "pedophiliac",
  "pee",
  "peepee",
  "penetrate",
  "penetration",
  "penial",
  "penile",
  "penis",
  "perversion",
  "phalli",
  "phallic",
  "phuck",
  "pillowbiter",
  "pimp",
  "piss",
  "pissed",
  "pissoff",
  "piss-off",
  "pms",
  "poon",
  "poontang",
  "porn",
  "porno",
  "pornography",
  "prick",
  "prostitute",
  "pube",
  "pubic",
  "pubis",
  "puss",
  "pussies",
  "pussy",
  "pussypounder",
  "queaf",
  "queef",
  "queer",
  "queero",
  "queers",
  "quicky",
  "quim",
  "racy",
  "rape",
  "raped",
  "raper",
  "rapist",
  "raunch",
  "rectal",
  "rectum",
  "rectus",
  "rimjob",
  "semen",
  "sex",
  "sexual",
  "sh1t",
  "s-h-1-t",
  "shamedame",
  "shit",
  "s-h-i-t",
  "shite",
  "shiteater",
  "shitface",
  "shithead",
  "shithole",
  "shithouse",
  "shits",
  "shitt",
  "shitted",
  "shitter",
  "shitty",
  "shiz",
  "sissy",
  "skag",
  "skank",
  "slave",
  "sleaze",
  "sleazy",
  "slut",
  "slutdumper",
  "slutkiss",
  "sluts",
  "smegma",
  "smut",
  "smutty",
  "snatch",
  "sniper",
  "snuff",
  "sodom",
  "souse",
  "soused",
  "sperm",
  "spooge",
  "spunk",
  "steamy",
  "stiffy",
  "strip",
  "stroke",
  "suck",
  "sucked",
  "sucking",
  "sumofabiatch",
  "t1t",
  "tampon",
  "teabagging",
  "teat",
  "terd",
  "teste",
  "testee",
  "testes",
  "testicle",
  "testis",
  "thrust",
  "tinkle",
  "tit",
]


export const nsfwKeywords = [...nsfwKeywordsDating, ...words];