name = "pollinations-image"
main = "src/container.ts"
compatibility_date = "2025-09-01"

[observability]
enabled = true

[[containers]]
max_instances = 1
class_name = "ImageServiceContainer"
image = "./Dockerfile"
image_build_context = ".."
instance_type = "standard-4"

[[durable_objects.bindings]]
class_name = "ImageServiceContainer"
name = "CONTAINER"

[[migrations]]
new_sqlite_classes = [ "ImageServiceContainer" ]
tag = "v1"
