/**
 * Social Bots Projects 🤖
 * Discord / Telegram / WhatsApp / Roblox bots & NPCs
 */

export const socialBotsProjects = [
  {
    name: "Anyai",
    url: "https://discord.gg/anyai",
    description: "A Discord bot and community for AI-driven content.",
    author: "@meow_18838",
    submissionDate: "2025-05-05",
    order: 5
  },
  {
    name: "Aura Chat Bot",
    description: "A chat bot integrating Pollinations API for text and image generation.",
    author: "@Py-Phoenix-PJS",
    submissionDate: "2025-05-12",
    order: 1
  },
  {
    name: "🤖 ImageEditer",
    url: "https://t.me/ImageEditer_bot",
    description: "AI Art Studio - A feature-rich Telegram bot that creates art from text prompts, remixes images, merges multiple artworks, and offers one-tap regeneration with real-time control. Supports multiple AI models (GPT Image, Flux, Turbo) with NSFW detection and smart layout features.",
    author: "@_dr_misterio_",
    submissionDate: "2025-06-02",
    order: 1
  },
  {
    name: "PolliBot",
    url: "https://t.me/pollinations_bot",
    description: "Telegram bot that generates images, text, and audio using Pollinations APIs.",
    author: "@pollibot_dev",
    submissionDate: "2025-02-10"
  },
  {
    name: "One Word",
    url: "https://oneword.pollinations.ai",
    description: "A Discord bot that generates images from single-word prompts, designed for simplicity and quick creative inspiration.",
    author: "@oneword_team",
    submissionDate: "2025-04-05",
    order: 1
  },
  {
    name: "Titan-GPT",
    url: "https://titan-gpt.vercel.app",
    description: "A Discord bot that combines text and image generation capabilities from Pollinations to create rich, interactive experiences for server members.",
    author: "@titan_dev",
    repo: "https://github.com/titan-dev/titan-gpt",
    stars: 87,
    submissionDate: "2025-04-12",
    order: 1
  },
  {
    name: "Pollinations Discord Bot",
    url: "https://github.com/pollinations/discord-bot",
    description: "Official Discord bot for Pollinations.ai that allows server members to generate images, text, and audio directly within Discord channels.",
    author: "@pollinations",
    repo: "https://github.com/pollinations/discord-bot",
    stars: 156,
    submissionDate: "2025-03-20",
    order: 1
  },
  {
    name: "Pollinations Telegram Assistant",
    url: "https://t.me/pollinations_assistant_bot",
    description: "An advanced Telegram bot that provides access to Pollinations AI services through a conversational interface with support for multiple languages.",
    author: "@pollen_labs",
    submissionDate: "2025-04-08",
    order: 1
  },
  {
    name: "Pollinations WhatsApp Group",
    url: "https://chat.whatsapp.com/pollinations-ai",
    description: "A WhatsApp group bot that allows members to generate AI content through simple commands, making Pollinations accessible on mobile messaging.",
    author: "@whatsapp_ai_dev",
    submissionDate: "2025-05-01",
    order: 2
  },
  {
    name: "OpenHive",
    url: "https://openhive.network",
    description: "A decentralized platform for AI bots powered by Pollinations that can be deployed across multiple social media platforms simultaneously.",
    author: "@openhive_network",
    repo: "https://github.com/openhive/network",
    stars: 124,
    submissionDate: "2025-04-15",
    order: 1
  },
  {
    name: "pollinations-tg-bot 🇨🇳",
    url: "https://t.me/pollinations_cn_bot",
    description: "Chinese language Telegram bot for Pollinations AI with specialized prompts for Eastern art styles and cultural references.",
    author: "@cn_ai_dev",
    language: "zh",
    submissionDate: "2025-05-10",
    order: 2
  },
  {
    name: "AlphaLLM - AI Discord Bot",
    url: "https://alphallm.ai/discord",
    description: "A feature-rich Discord bot that combines multiple AI models from Pollinations to provide text generation, image creation, and voice synthesis.",
    author: "@alphallm_team",
    repo: "https://github.com/alphallm/discord-bot",
    stars: 213,
    submissionDate: "2025-05-05",
    order: 1
  },
  {
    name: "Quick AI & Jolbak",
    url: "https://quickai.jolbak.com",
    description: "A multi-platform bot suite that integrates with Discord, Slack, and Microsoft Teams to provide Pollinations AI services in professional environments.",
    author: "@jolbak_dev",
    submissionDate: "2025-05-18",
    order: 2
  },
  {
    name: "AI Image Generator [ROBLOX]",
    url: "https://www.roblox.com/games/ai-image-generator",
    description: "A Roblox experience that allows players to generate images using Pollinations AI directly within the game environment.",
    author: "@roblox_ai_studio",
    submissionDate: "2025-05-22",
    order: 2
  },
  {
    name: "SingodiyaTech bot",
    url: "https://t.me/singodiyatech_bot",
    description: "A Telegram bot focused on technical illustrations and diagrams generated by Pollinations AI, aimed at developers and engineers.",
    author: "@singodiya_tech",
    submissionDate: "2025-05-15",
    order: 2
  },
  {
    name: "Raftar.xyz",
    url: "https://raftar.xyz/app",
    description: "Raftar.xyz is an innovative social bot platform that uses Pollinations AI to create engaging and interactive experiences on Discord and Twitter, focusing on community building and automated content curation.",
    author: "@raftar_official",
    repo: "https://github.com/raftarxyz/raftar-bot",
    stars: 42,
    submissionDate: "2025-05-20",
    order: 3
  },
  {
    name: "PolliBot",
    url: "https://pollibot.example.com",
    description: "A versatile Telegram bot integrated with Pollinations. Offers image generation, text summarization, and quick answers directly within Telegram chats. Supports multiple languages.",
    author: "BotBuilders Inc.",
    repo: "https://github.com/botbuilders/pollibot-telegram",
    stars: 75,
    submissionDate: "2025-03-20",
    order: 2
  }
];
