name = "pollinations-uptime-monitor"
main = "worker.js"
compatibility_date = "2024-01-01"

# KV Namespace for storing uptime data
[[kv_namespaces]]
binding = "UPTIME_DATA"
id = "your-kv-namespace-id"  # Replace with your actual KV namespace ID

# Scheduled event - runs every 5 minutes
[triggers]
crons = ["*/5 * * * *"]
