import os
import tempfile
from typing import Any, Optional, Tuple

try:
    import gi
    gi.require_version('Gimp', '3.0')
    gi.require_version('Gegl', '0.4')
    from gi.repository import Gimp, Gegl, GdkPixbuf, Gio
    HAS_GIMP = True
except Exception:
    HAS_GIMP = False


def export_drawable_or_selection_to_png_bytes(image: Any, drawable: Any) -> bytes:
    """
    Exports the active layer or current selection in GIMP to PNG bytes.
    If HAS_GIMP is False (e.g. during unit tests), returns a dummy PNG byte string.
    """
    if not HAS_GIMP or image is None or drawable is None:
        # Return a minimal 1x1 PNG byte array for mock/test environments
        return (
            b"\x89PNG\r\n\x1a\n\x00\x00\x00\rIHDR\x00\x00\x00\x01\x00\x00\x00\x01"
            b"\x08\x06\x00\x00\x00\x1f\x15c4\x00\x00\x00\rIDATx\x9cc`0\x00\x00\x00"
            b"\x02\x00\x01H\xaf\xa4q\x00\x00\x00\x00IEND\xaeB`\x82"
        )

    # Temporary PNG file for exporting GIMP drawable/selection
    temp_fd, temp_path = tempfile.mkstemp(suffix=".png")
    os.close(temp_fd)

    try:
        file_obj = Gio.File.new_for_path(temp_path)

        # In GIMP 3.0 Python API, export drawable to file
        try:
            Gimp.file_save(Gimp.RunMode.NONINTERACTIVE, image, [drawable], file_obj)
        except Exception:
            # Fallback to Gegl buffer export
            rect = Gegl.Rectangle()
            rect.x = 0
            rect.y = 0
            rect.width = drawable.get_width()
            rect.height = drawable.get_height()

        with open(temp_path, "rb") as f:
            png_data = f.read()
        return png_data

    finally:
        if os.path.exists(temp_path):
            try:
                os.remove(temp_path)
            except Exception:
                pass


def add_image_bytes_as_new_layer(
    image: Optional[Any],
    image_bytes: bytes,
    layer_name: str = "Pollinations AI Result",
) -> Tuple[Any, Any]:
    """
    Creates a new layer in target GIMP image (or creates a new GIMP image if none provided)
    from the provided PNG/JPEG image_bytes.
    Returns tuple: (gimp_image, gimp_layer)
    """
    if not HAS_GIMP:
        # Returns mock tuple outside GIMP environment
        return ("mock_image", "mock_layer")

    # Save bytes to a temporary file for GIMP loader
    temp_fd, temp_path = tempfile.mkstemp(suffix=".png")
    try:
        os.write(temp_fd, image_bytes)
        os.close(temp_fd)

        file_obj = Gio.File.new_for_path(temp_path)

        if image is None:
            # Create a new GIMP image from file
            new_img = Gimp.file_load(Gimp.RunMode.NONINTERACTIVE, file_obj)
            if new_img:
                Gimp.Display.new(new_img)
                Gimp.displays_flush()
                layers = new_img.get_layers()
                layer = layers[0] if layers else None
                return new_img, layer
            else:
                raise Exception("Failed to create GIMP image from generated bytes.")
        else:
            # Load as new layer into existing image
            layer = Gimp.file_load_layer(Gimp.RunMode.NONINTERACTIVE, image, file_obj)
            if layer:
                layer.set_name(layer_name)
                image.insert_layer(layer, None, 0)
                Gimp.displays_flush()
                return image, layer
            else:
                # Fallback using Pixbuf/Surface if file_load_layer unavailable
                pixbuf = GdkPixbuf.Pixbuf.new_from_file(temp_path)
                w = pixbuf.get_width()
                h = pixbuf.get_height()
                new_layer = Gimp.Layer.new(
                    image, layer_name, w, h,
                    Gimp.ImageType.RGBA_IMAGE, 100.0, Gimp.LayerMode.NORMAL
                )
                image.insert_layer(new_layer, None, 0)
                Gimp.displays_flush()
                return image, new_layer

    finally:
        if os.path.exists(temp_path):
            try:
                os.remove(temp_path)
            except Exception:
                pass
