// NOTE: This file was originally autogenerated by better-auth, but
// we needed to add some indexes manually. In the latest version, 
// better-auth generates them automatically, but we are blocked from updating
// by a bug in the `drizzle-kit generate` cli tool. When drizzle 1.0 is
// released, we should consider updating to the latest version of better-auth
// and re-generating the schema including the indexes.

import { relations, sql } from "drizzle-orm";
import {
  sqliteTable,
  text,
  integer,
  real,
  index,
  uniqueIndex,
} from "drizzle-orm/sqlite-core";

export const user = sqliteTable("user", {
  id: text("id").primaryKey(),
  name: text("name").notNull(),
  email: text("email").notNull().unique(),
  emailVerified: integer("email_verified", { mode: "boolean" })
    .default(false)
    .notNull(),
  image: text("image"),
  createdAt: integer("created_at", { mode: "timestamp" })
    .defaultNow()
    .notNull(),
  updatedAt: integer("updated_at", { mode: "timestamp" })
    .defaultNow()
    .$onUpdate(() => /* @__PURE__ */ new Date())
    .notNull(),
  role: text("role"),
  banned: integer("banned", { mode: "boolean" }).default(false),
  banReason: text("ban_reason"),
  banExpires: integer("ban_expires", { mode: "timestamp" }),
  githubId: integer("github_id"),
  githubUsername: text("github_username"),
  tier: text("tier").default("spore").notNull(),
  tierBalance: real("tier_balance"),
  packBalance: real("pack_balance"),
  lastTierGrant: integer("last_tier_grant"),
  stripeCustomerId: text("stripe_customer_id").unique(),
  autoTopUpEnabled: integer("auto_top_up_enabled", { mode: "boolean" })
    .default(sql`0`)
    .notNull(),
  autoTopUpAmountUsd: integer("auto_top_up_amount_usd"),
}, (table) => [
  index("idx_user_email").on(table.email),
  index("idx_user_auto_top_up_enabled").on(table.autoTopUpEnabled),
  // GitHub profile lookup for quest checks and account display.
  index("idx_user_github_id").on(table.githubId),
]);

export const session = sqliteTable("session", {
  id: text("id").primaryKey(),
  expiresAt: integer("expires_at", { mode: "timestamp" }).notNull(),
  token: text("token").notNull().unique(),
  createdAt: integer("created_at", { mode: "timestamp" })
    .defaultNow()
    .notNull(),
  updatedAt: integer("updated_at", { mode: "timestamp" })
    .$onUpdate(() => /* @__PURE__ */ new Date())
    .notNull(),
  ipAddress: text("ip_address"),
  userAgent: text("user_agent"),
  userId: text("user_id")
    .notNull()
    .references(() => user.id, { onDelete: "cascade" }),
  impersonatedBy: text("impersonated_by"),
}, (table) => [
  index("idx_session_user_id").on(table.userId),
]);

export const account = sqliteTable("account", {
  id: text("id").primaryKey(),
  accountId: text("account_id").notNull(),
  providerId: text("provider_id").notNull(),
  userId: text("user_id")
    .notNull()
    .references(() => user.id, { onDelete: "cascade" }),
  accessToken: text("access_token"),
  refreshToken: text("refresh_token"),
  idToken: text("id_token"),
  accessTokenExpiresAt: integer("access_token_expires_at", {
    mode: "timestamp",
  }),
  refreshTokenExpiresAt: integer("refresh_token_expires_at", {
    mode: "timestamp",
  }),
  scope: text("scope"),
  password: text("password"),
  createdAt: integer("created_at", { mode: "timestamp" })
    .defaultNow()
    .notNull(),
  updatedAt: integer("updated_at", { mode: "timestamp" })
    .$onUpdate(() => /* @__PURE__ */ new Date())
    .notNull(),
}, (table) => [
  index("idx_account_user_id").on(table.userId),
]);

export const verification = sqliteTable("verification", {
  id: text("id").primaryKey(),
  identifier: text("identifier").notNull(),
  value: text("value").notNull(),
  expiresAt: integer("expires_at", { mode: "timestamp" }).notNull(),
  createdAt: integer("created_at", { mode: "timestamp" })
    .defaultNow()
    .notNull(),
  updatedAt: integer("updated_at", { mode: "timestamp" })
    .defaultNow()
    .$onUpdate(() => /* @__PURE__ */ new Date())
    .notNull(),
}, (table) => [
  index("idx_verification_identifier").on(table.identifier),
]);

export const apikey = sqliteTable("apikey", {
  id: text("id").primaryKey(),
  name: text("name"),
  start: text("start"),
  prefix: text("prefix"),
  key: text("key").notNull(),
  userId: text("user_id")
    .notNull()
    .references(() => user.id, { onDelete: "cascade" }),
  refillInterval: integer("refill_interval"),
  refillAmount: integer("refill_amount"),
  lastRefillAt: integer("last_refill_at", { mode: "timestamp" }),
  enabled: integer("enabled", { mode: "boolean" }).default(true),
  rateLimitEnabled: integer("rate_limit_enabled", { mode: "boolean" }).default(
    true,
  ),
  rateLimitTimeWindow: integer("rate_limit_time_window").default(1000),
  rateLimitMax: integer("rate_limit_max").default(5),
  requestCount: integer("request_count").default(0),
  remaining: integer("remaining"),
  lastRequest: integer("last_request", { mode: "timestamp" }),
  expiresAt: integer("expires_at", { mode: "timestamp" }),
  createdAt: integer("created_at", { mode: "timestamp" }).notNull(),
  updatedAt: integer("updated_at", { mode: "timestamp" }).notNull(),
  permissions: text("permissions"),
  metadata: text("metadata"),
  pollenBalance: real("pollen_balance"),
  byopClientKeyId: text("byop_client_key_id"),
}, (table) => [
  index("idx_apikey_key").on(table.key),
  index('idx_apikey_expires_at').on(table.expiresAt),
  index("idx_apikey_user_id").on(table.userId),
  index("idx_apikey_byop_client_key_id").on(table.byopClientKeyId),
]);

export const stripeAutoTopUpAttempt = sqliteTable("stripe_auto_top_up_attempt", {
  id: text("id").primaryKey(),
  userId: text("user_id")
    .notNull()
    .references(() => user.id, { onDelete: "cascade" }),
  stripeInvoiceId: text("stripe_invoice_id").unique(),
  amountUsd: integer("amount_usd").notNull(),
  status: text("status").notNull(),
  failureReason: text("failure_reason"),
  createdAt: integer("created_at", { mode: "timestamp" })
    .defaultNow()
    .notNull(),
  updatedAt: integer("updated_at", { mode: "timestamp" })
    .defaultNow()
    .$onUpdate(() => /* @__PURE__ */ new Date())
    .notNull(),
  completedAt: integer("completed_at", { mode: "timestamp" }),
}, (table) => [
  index("idx_stripe_auto_top_up_attempt_user_id").on(table.userId),
  index("idx_stripe_auto_top_up_attempt_status").on(table.status),
]);

export const stripeCardFingerprintAttempt = sqliteTable("stripe_card_fingerprint_attempt", {
  eventId: text("event_id").primaryKey(),
  userId: text("user_id")
    .notNull()
    .references(() => user.id, { onDelete: "cascade" }),
  cardFingerprint: text("card_fingerprint").notNull(),
  createdAt: integer("created_at", { mode: "timestamp_ms" })
    .defaultNow()
    .notNull(),
}, (table) => [
  index("idx_stripe_card_fingerprint_attempt_user_created").on(
    table.userId,
    table.createdAt,
  ),
  index("idx_stripe_card_fingerprint_attempt_user_fingerprint").on(
    table.userId,
    table.cardFingerprint,
  ),
]);

export const communityEndpoint = sqliteTable("community_endpoint", {
  id: text("id").primaryKey(),
  ownerUserId: text("owner_user_id")
    .notNull()
    .references(() => user.id, { onDelete: "cascade" }),
  name: text("name").notNull(),
  description: text("description"),
  baseUrl: text("base_url").notNull(),
  upstreamModel: text("upstream_model").notNull(),
  bearerTokenCiphertext: text("bearer_token_ciphertext").notNull(),
  kind: text("kind", { enum: ["model", "agent"] })
    .default("model")
    .notNull(),
  tools: integer("tools", { mode: "boolean" }).default(false).notNull(),
  search: integer("search", { mode: "boolean" }).default(false).notNull(),
  reasoning: integer("reasoning", { mode: "boolean" }).default(false).notNull(),
  maxRequestPrice: real("max_request_price").default(1).notNull(),
  promptTextPrice: real("prompt_text_price").notNull(),
  promptCachedPrice: real("prompt_cached_price").default(0).notNull(),
  promptCacheWritePrice: real("prompt_cache_write_price").default(0).notNull(),
  promptAudioPrice: real("prompt_audio_price").default(0).notNull(),
  promptImagePrice: real("prompt_image_price").default(0).notNull(),
  completionTextPrice: real("completion_text_price").notNull(),
  completionReasoningPrice: real("completion_reasoning_price").default(0).notNull(),
  completionAudioPrice: real("completion_audio_price").default(0).notNull(),
  disabledAt: integer("disabled_at", { mode: "timestamp" }),
  disabledReason: text("disabled_reason"),
  disabledBy: text("disabled_by"),
  createdAt: integer("created_at", { mode: "timestamp" })
    .defaultNow()
    .notNull(),
  updatedAt: integer("updated_at", { mode: "timestamp" })
    .defaultNow()
    .$onUpdate(() => /* @__PURE__ */ new Date())
    .notNull(),
}, (table) => [
  index("idx_community_endpoint_owner_user_id").on(table.ownerUserId),
  uniqueIndex("idx_community_endpoint_owner_name").on(
    table.ownerUserId,
    table.name,
  ),
]);

// Drizzle relations for query builder joins
export const userRelations = relations(user, ({ many }) => ({
  apikeys: many(apikey),
  sessions: many(session),
  accounts: many(account),
  stripeAutoTopUpAttempts: many(stripeAutoTopUpAttempt),
  stripeCardFingerprintAttempts: many(stripeCardFingerprintAttempt),
  communityEndpoints: many(communityEndpoint),
}));

export const apikeyRelations = relations(apikey, ({ one }) => ({
  user: one(user, {
    fields: [apikey.userId],
    references: [user.id],
  }),
}));

export const sessionRelations = relations(session, ({ one }) => ({
  user: one(user, {
    fields: [session.userId],
    references: [user.id],
  }),
}));

export const accountRelations = relations(account, ({ one }) => ({
  user: one(user, {
    fields: [account.userId],
    references: [user.id],
  }),
}));

export const stripeAutoTopUpAttemptRelations = relations(
  stripeAutoTopUpAttempt,
  ({ one }) => ({
    user: one(user, {
      fields: [stripeAutoTopUpAttempt.userId],
      references: [user.id],
    }),
  }),
);

export const stripeCardFingerprintAttemptRelations = relations(
  stripeCardFingerprintAttempt,
  ({ one }) => ({
    user: one(user, {
      fields: [stripeCardFingerprintAttempt.userId],
      references: [user.id],
    }),
  }),
);

export const communityEndpointRelations = relations(communityEndpoint, ({ one }) => ({
  owner: one(user, {
    fields: [communityEndpoint.ownerUserId],
    references: [user.id],
  }),
}));

// Device Authorization Grant (RFC 8628) table
export const deviceCode = sqliteTable("device_code", {
  id: text("id").primaryKey(),
  deviceCode: text("device_code").notNull(),
  userCode: text("user_code").notNull(),
  userId: text("user_id").references(() => user.id, { onDelete: "cascade" }),
  expiresAt: integer("expires_at", { mode: "timestamp" }).notNull(),
  status: text("status").notNull(),
  clientId: text("client_id"),
  scope: text("scope"),
}, (table) => [
  index("idx_device_code_device_code").on(table.deviceCode),
  index("idx_device_code_user_code").on(table.userCode),
]);

export const stripeCheckoutCredits = sqliteTable("stripe_checkout_credits", {
  sessionId: text("session_id").primaryKey(),
  eventId: text("event_id").notNull(),
  eventType: text("event_type").notNull(),
  userId: text("user_id")
    .notNull()
    .references(() => user.id, { onDelete: "cascade" }),
  pollenCredited: real("pollen_credited").notNull(),
  createdAt: integer("created_at", { mode: "timestamp" })
    .defaultNow()
    .notNull(),
}, (table) => [
  index("idx_stripe_checkout_credits_user_id").on(table.userId),
]);

export const polarCheckoutCredits = sqliteTable("polar_checkout_credits", {
  orderId: text("order_id").primaryKey(),
  eventId: text("event_id").notNull(),
  eventType: text("event_type").notNull(),
  userId: text("user_id")
    .notNull()
    .references(() => user.id, { onDelete: "cascade" }),
  pollenCredited: real("pollen_credited").notNull(),
  polarCreatedAt: integer("polar_created_at").notNull(),
  amount: integer("amount"),
  totalAmount: integer("total_amount"),
  currency: text("currency"),
  customerId: text("customer_id"),
  productId: text("product_id"),
  productName: text("product_name"),
  productSlug: text("product_slug"),
  metadataJson: text("metadata_json"),
  createdAt: integer("created_at", { mode: "timestamp" })
    .defaultNow()
    .notNull(),
}, (table) => [
  index("idx_polar_checkout_credits_user_id").on(table.userId),
]);

// Reward ledger: one row == one earned reward. `claimedAt` is null until the
// user claims it, and only claiming credits the user's balance. Everything that
// can earn pollen is modelled as a reward, so there is no reward-kind
// discriminator — `questId` already names what was earned. The old
// GitHub-shaped quest_payout_credits table is backfilled into here and dropped
// by the rewards migration.
export const rewards = sqliteTable("rewards", {
  id: text("id").primaryKey(),
  // Idempotency guard. Encodes the quest's completion scope, e.g.
  // "quest:{issue}" or "quest:{questId}:user:{userId}".
  idempotencyKey: text("idempotency_key").notNull().unique(),
  userId: text("user_id")
    .notNull()
    .references(() => user.id, { onDelete: "cascade" }),
  // Catalog id of the quest that was earned; null for one-off rewards.
  questId: text("quest_id"),
  // Quest title snapshotted when earned, so history renders it directly.
  title: text("title").notNull(),
  // Optional quest link snapshotted when earned.
  url: text("url"),
  pollenAmount: real("pollen_amount").notNull(),
  // Which balance bucket will be credited when claimed: "tier" or "pack".
  balanceBucket: text("balance_bucket").notNull(),
  earnedAt: integer("earned_at", { mode: "timestamp" })
    .defaultNow()
    .notNull(),
  claimedAt: integer("claimed_at", { mode: "timestamp" }),
}, (table) => [
  index("idx_rewards_user_id").on(table.userId),
]);
