// NOTE: This file was originally autogenerated by better-auth, but
// we needed to add some indexes manually. In the latest version, 
// better-auth generates them automatically, but we are blocked from updating
// by a bug in the `drizzle-kit generate` cli tool. When drizzle 1.0 is
// released, we should consider updating to the latest version of better-auth
// and re-generating the schema including the indexes.

import { relations, sql } from "drizzle-orm";
import { sqliteTable, text, integer, real, index } from "drizzle-orm/sqlite-core";

export const user = sqliteTable("user", {
  id: text("id").primaryKey(),
  name: text("name").notNull(),
  email: text("email").notNull().unique(),
  emailVerified: integer("email_verified", { mode: "boolean" })
    .default(false)
    .notNull(),
  image: text("image"),
  createdAt: integer("created_at", { mode: "timestamp" })
    .defaultNow()
    .notNull(),
  updatedAt: integer("updated_at", { mode: "timestamp" })
    .defaultNow()
    .$onUpdate(() => /* @__PURE__ */ new Date())
    .notNull(),
  role: text("role"),
  banned: integer("banned", { mode: "boolean" }).default(false),
  banReason: text("ban_reason"),
  banExpires: integer("ban_expires", { mode: "timestamp" }),
  githubId: integer("github_id"),
  githubUsername: text("github_username"),
  tier: text("tier").default("spore").notNull(),
  tierBalance: real("tier_balance"),
  packBalance: real("pack_balance"),
  lastTierGrant: integer("last_tier_grant"),
  stripeCustomerId: text("stripe_customer_id").unique(),
  autoTopUpEnabled: integer("auto_top_up_enabled", { mode: "boolean" })
    .default(sql`0`)
    .notNull(),
  autoTopUpAmountUsd: integer("auto_top_up_amount_usd"),
}, (table) => [
  index("idx_user_email").on(table.email),
  index("idx_user_auto_top_up_enabled").on(table.autoTopUpEnabled),
  // GitHub author/assignee joins (gh_pull_requests, gh_issues -> user).
  index("idx_user_github_id").on(table.githubId),
]);

export const session = sqliteTable("session", {
  id: text("id").primaryKey(),
  expiresAt: integer("expires_at", { mode: "timestamp" }).notNull(),
  token: text("token").notNull().unique(),
  createdAt: integer("created_at", { mode: "timestamp" })
    .defaultNow()
    .notNull(),
  updatedAt: integer("updated_at", { mode: "timestamp" })
    .$onUpdate(() => /* @__PURE__ */ new Date())
    .notNull(),
  ipAddress: text("ip_address"),
  userAgent: text("user_agent"),
  userId: text("user_id")
    .notNull()
    .references(() => user.id, { onDelete: "cascade" }),
  impersonatedBy: text("impersonated_by"),
}, (table) => [
  index("idx_session_user_id").on(table.userId),
]);

export const account = sqliteTable("account", {
  id: text("id").primaryKey(),
  accountId: text("account_id").notNull(),
  providerId: text("provider_id").notNull(),
  userId: text("user_id")
    .notNull()
    .references(() => user.id, { onDelete: "cascade" }),
  accessToken: text("access_token"),
  refreshToken: text("refresh_token"),
  idToken: text("id_token"),
  accessTokenExpiresAt: integer("access_token_expires_at", {
    mode: "timestamp",
  }),
  refreshTokenExpiresAt: integer("refresh_token_expires_at", {
    mode: "timestamp",
  }),
  scope: text("scope"),
  password: text("password"),
  createdAt: integer("created_at", { mode: "timestamp" })
    .defaultNow()
    .notNull(),
  updatedAt: integer("updated_at", { mode: "timestamp" })
    .$onUpdate(() => /* @__PURE__ */ new Date())
    .notNull(),
}, (table) => [
  index("idx_account_user_id").on(table.userId),
]);

export const verification = sqliteTable("verification", {
  id: text("id").primaryKey(),
  identifier: text("identifier").notNull(),
  value: text("value").notNull(),
  expiresAt: integer("expires_at", { mode: "timestamp" }).notNull(),
  createdAt: integer("created_at", { mode: "timestamp" })
    .defaultNow()
    .notNull(),
  updatedAt: integer("updated_at", { mode: "timestamp" })
    .defaultNow()
    .$onUpdate(() => /* @__PURE__ */ new Date())
    .notNull(),
}, (table) => [
  index("idx_verification_identifier").on(table.identifier),
]);

export const apikey = sqliteTable("apikey", {
  id: text("id").primaryKey(),
  name: text("name"),
  start: text("start"),
  prefix: text("prefix"),
  key: text("key").notNull(),
  userId: text("user_id")
    .notNull()
    .references(() => user.id, { onDelete: "cascade" }),
  refillInterval: integer("refill_interval"),
  refillAmount: integer("refill_amount"),
  lastRefillAt: integer("last_refill_at", { mode: "timestamp" }),
  enabled: integer("enabled", { mode: "boolean" }).default(true),
  rateLimitEnabled: integer("rate_limit_enabled", { mode: "boolean" }).default(
    true,
  ),
  rateLimitTimeWindow: integer("rate_limit_time_window").default(1000),
  rateLimitMax: integer("rate_limit_max").default(5),
  requestCount: integer("request_count").default(0),
  remaining: integer("remaining"),
  lastRequest: integer("last_request", { mode: "timestamp" }),
  expiresAt: integer("expires_at", { mode: "timestamp" }),
  createdAt: integer("created_at", { mode: "timestamp" }).notNull(),
  updatedAt: integer("updated_at", { mode: "timestamp" }).notNull(),
  permissions: text("permissions"),
  metadata: text("metadata"),
  pollenBalance: real("pollen_balance"),
  byopClientKeyId: text("byop_client_key_id"),
}, (table) => [
  index("idx_apikey_key").on(table.key),
  index('idx_apikey_expires_at').on(table.expiresAt),
  index("idx_apikey_user_id").on(table.userId),
  index("idx_apikey_byop_client_key_id").on(table.byopClientKeyId),
]);

export const stripeAutoTopUpAttempt = sqliteTable("stripe_auto_top_up_attempt", {
  id: text("id").primaryKey(),
  userId: text("user_id")
    .notNull()
    .references(() => user.id, { onDelete: "cascade" }),
  stripeInvoiceId: text("stripe_invoice_id").unique(),
  amountUsd: integer("amount_usd").notNull(),
  status: text("status").notNull(),
  failureReason: text("failure_reason"),
  createdAt: integer("created_at", { mode: "timestamp" })
    .defaultNow()
    .notNull(),
  updatedAt: integer("updated_at", { mode: "timestamp" })
    .defaultNow()
    .$onUpdate(() => /* @__PURE__ */ new Date())
    .notNull(),
  completedAt: integer("completed_at", { mode: "timestamp" }),
}, (table) => [
  index("idx_stripe_auto_top_up_attempt_user_id").on(table.userId),
  index("idx_stripe_auto_top_up_attempt_status").on(table.status),
]);

// Drizzle relations for query builder joins
export const userRelations = relations(user, ({ many }) => ({
  apikeys: many(apikey),
  sessions: many(session),
  accounts: many(account),
  stripeAutoTopUpAttempts: many(stripeAutoTopUpAttempt),
}));

export const apikeyRelations = relations(apikey, ({ one }) => ({
  user: one(user, {
    fields: [apikey.userId],
    references: [user.id],
  }),
}));

export const sessionRelations = relations(session, ({ one }) => ({
  user: one(user, {
    fields: [session.userId],
    references: [user.id],
  }),
}));

export const accountRelations = relations(account, ({ one }) => ({
  user: one(user, {
    fields: [account.userId],
    references: [user.id],
  }),
}));

export const stripeAutoTopUpAttemptRelations = relations(
  stripeAutoTopUpAttempt,
  ({ one }) => ({
    user: one(user, {
      fields: [stripeAutoTopUpAttempt.userId],
      references: [user.id],
    }),
  }),
);

// Device Authorization Grant (RFC 8628) table
export const deviceCode = sqliteTable("device_code", {
  id: text("id").primaryKey(),
  deviceCode: text("device_code").notNull(),
  userCode: text("user_code").notNull(),
  userId: text("user_id").references(() => user.id, { onDelete: "cascade" }),
  expiresAt: integer("expires_at", { mode: "timestamp" }).notNull(),
  status: text("status").notNull(),
  clientId: text("client_id"),
  scope: text("scope"),
}, (table) => [
  index("idx_device_code_device_code").on(table.deviceCode),
  index("idx_device_code_user_code").on(table.userCode),
]);

export const stripeCheckoutCredits = sqliteTable("stripe_checkout_credits", {
  sessionId: text("session_id").primaryKey(),
  eventId: text("event_id").notNull(),
  eventType: text("event_type").notNull(),
  userId: text("user_id")
    .notNull()
    .references(() => user.id, { onDelete: "cascade" }),
  pollenCredited: real("pollen_credited").notNull(),
  createdAt: integer("created_at", { mode: "timestamp" })
    .defaultNow()
    .notNull(),
}, (table) => [
  index("idx_stripe_checkout_credits_user_id").on(table.userId),
]);

// Reward ledger: one row == one earned reward. `claimedAt` is null until the
// user claims it, and only claiming credits the user's balance. Everything that
// can earn pollen is modelled as a reward, so there is no reward-kind
// discriminator — `questId` already names what was earned. The old
// GitHub-shaped quest_payout_credits table was backfilled into here and dropped
// by an earlier migration.
export const rewards = sqliteTable("rewards", {
  id: text("id").primaryKey(),
  // Idempotency guard. Encodes the quest's completion scope, e.g.
  // "quest:{issue}" or "quest:{questId}:user:{userId}".
  idempotencyKey: text("idempotency_key").notNull().unique(),
  userId: text("user_id")
    .notNull()
    .references(() => user.id, { onDelete: "cascade" }),
  // Catalog id of the quest that was earned; null for one-off rewards.
  questId: text("quest_id"),
  // Quest title snapshotted when earned, so history renders it directly.
  title: text("title").notNull(),
  // Optional quest link snapshotted when earned.
  url: text("url"),
  pollenAmount: real("pollen_amount").notNull(),
  // Which balance bucket will be credited when claimed: "tier" or "pack".
  balanceBucket: text("balance_bucket").notNull(),
  earnedAt: integer("earned_at", { mode: "timestamp" })
    .defaultNow()
    .notNull(),
  claimedAt: integer("claimed_at", { mode: "timestamp" }),
}, (table) => [
  index("idx_rewards_user_id").on(table.userId),
]);

// GitHub repo mirror — a thin, full snapshot of pollinations/pollinations PRs,
// issues, and the PR->issue "closes" edges. Refreshed wholesale by the
// scheduled syncGithubMirror() (INSERT OR REPLACE every row each run). These
// tables are deliberately generic: they mirror GitHub state and nothing else
// (no quest/reward logic) so any consumer can read them. The PR->issue close
// link is a GraphQL-only relation (closingIssuesReferences) that lives on
// neither the PR nor the issue payload, so it gets its own edge table.

export const ghPullRequests = sqliteTable("gh_pull_requests", {
  // GitHub PR number — stable, repo-unique, the natural primary key.
  number: integer("number").primaryKey(),
  // Author's GitHub user id (databaseId). Nullable: the author account may be
  // deleted, in which case GraphQL returns a null author. Join key to
  // user.github_id.
  authorGithubId: integer("author_github_id"),
  authorLogin: text("author_login"),
  // GitHub PR state: "open" | "closed" | "merged" (GraphQL surfaces MERGED as a
  // distinct state; we store it lower-cased).
  state: text("state").notNull(),
  // The merged signal: NULL = never merged. A closed-but-unmerged PR has a null
  // mergedAt. Authoritative for "did this PR land".
  mergedAt: integer("merged_at", { mode: "timestamp" }),
  title: text("title").notNull(),
  url: text("url").notNull(),
  // GitHub's own created_at / closed_at, so consumers can answer "when was this
  // opened / closed" without another GitHub round-trip.
  githubCreatedAt: integer("github_created_at", { mode: "timestamp" }),
  githubClosedAt: integer("github_closed_at", { mode: "timestamp" }),
  // GitHub's own updated_at, used for change detection / debugging.
  githubUpdatedAt: integer("github_updated_at", { mode: "timestamp" }),
  // When this mirror row was last written.
  syncedAt: integer("synced_at", { mode: "timestamp" })
    .defaultNow()
    .$onUpdate(() => /* @__PURE__ */ new Date())
    .notNull(),
}, (table) => [
  index("idx_gh_pull_requests_author_github_id").on(table.authorGithubId),
  index("idx_gh_pull_requests_merged_at").on(table.mergedAt),
]);

export const ghIssues = sqliteTable("gh_issues", {
  // GitHub issue number — primary key. NOTE: GitHub returns PRs in the /issues
  // feed too; the sync filters those out (only true issues land here).
  number: integer("number").primaryKey(),
  authorGithubId: integer("author_github_id"),
  authorLogin: text("author_login"),
  // "open" | "closed". An issue's state does NOT say *why* it closed; use the
  // gh_pr_closing_issues edge to know if a merged PR closed it.
  state: text("state").notNull(),
  title: text("title").notNull(),
  url: text("url").notNull(),
  // Full issue body, mirrored verbatim so consumers can parse it (e.g. a
  // "### Reward" amount) in-process without another GitHub round-trip.
  body: text("body"),
  // Label names as a JSON array string (e.g. ["POLLEN-QUEST","bug"]). Stored as
  // text to match this file's convention (no json column mode is used here).
  labelsJson: text("labels_json"),
  // First assignee's GitHub user id, if any. Join key to user.github_id — kept
  // as a dedicated indexed column for the common single-assignee lookup.
  assigneeGithubId: integer("assignee_github_id"),
  assigneeLogin: text("assignee_login"),
  // All assignees as a JSON array of {login, githubId} (GitHub allows up to 10).
  // assigneeGithubId/assigneeLogin above mirror the first entry for indexing.
  assigneesJson: text("assignees_json"),
  // GitHub's own created_at / closed_at, so consumers can answer "when was this
  // opened / closed" without another GitHub round-trip.
  githubCreatedAt: integer("github_created_at", { mode: "timestamp" }),
  githubClosedAt: integer("github_closed_at", { mode: "timestamp" }),
  githubUpdatedAt: integer("github_updated_at", { mode: "timestamp" }),
  syncedAt: integer("synced_at", { mode: "timestamp" })
    .defaultNow()
    .$onUpdate(() => /* @__PURE__ */ new Date())
    .notNull(),
}, (table) => [
  index("idx_gh_issues_author_github_id").on(table.authorGithubId),
  index("idx_gh_issues_assignee_github_id").on(table.assigneeGithubId),
  index("idx_gh_issues_state").on(table.state),
]);

export const ghPrClosingIssues = sqliteTable("gh_pr_closing_issues", {
  // Composite identity (pr_number, issue_number) flattened into a single text
  // key "<pr>:<issue>" so the wholesale re-sync can upsert deterministically
  // (this file uses only single-column primary keys).
  edgeKey: text("edge_key").primaryKey(),
  prNumber: integer("pr_number").notNull(),
  issueNumber: integer("issue_number").notNull(),
  syncedAt: integer("synced_at", { mode: "timestamp" })
    .defaultNow()
    .$onUpdate(() => /* @__PURE__ */ new Date())
    .notNull(),
}, (table) => [
  index("idx_gh_pr_closing_issues_pr_number").on(table.prNumber),
  index("idx_gh_pr_closing_issues_issue_number").on(table.issueNumber),
]);
