name = "minimal-cloudflare-agents-bee"
main = "src/index.ts"
compatibility_date = "2026-05-03"

[[durable_objects.bindings]]
name = "MinimalCloudflareBee"
class_name = "MinimalCloudflareBee"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["MinimalCloudflareBee"]
