[build]
  functions = "functions"

[[redirects]]
  from = "/redirect/*"
  to = "/.netlify/functions/redirect/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/redirect-nexad/*"
  to = "/.netlify/functions/redirect-nexad/:splat"
  status = 200
  force = true

# Ensure Netlify preserves the React router paths
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
