/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as RefundsRouteImport } from './routes/refunds'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ErrorRouteImport } from './routes/error'
import { Route as DeviceRouteImport } from './routes/device'
import { Route as AuthorizeRouteImport } from './routes/authorize'
import { Route as DashboardRouteImport } from './routes/_dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardQuestsRouteImport } from './routes/_dashboard.quests'
import { Route as DashboardPollenRouteImport } from './routes/_dashboard.pollen'
import { Route as DashboardNewsRouteImport } from './routes/_dashboard.news'
import { Route as DashboardModelsRouteImport } from './routes/_dashboard.models'
import { Route as DashboardMembersRouteImport } from './routes/_dashboard.members'
import { Route as DashboardKeysRouteImport } from './routes/_dashboard.keys'
import { Route as DashboardActivityRouteImport } from './routes/_dashboard.activity'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundsRoute = RefundsRouteImport.update({
  id: '/refunds',
  path: '/refunds',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ErrorRoute = ErrorRouteImport.update({
  id: '/error',
  path: '/error',
  getParentRoute: () => rootRouteImport,
} as any)
const DeviceRoute = DeviceRouteImport.update({
  id: '/device',
  path: '/device',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthorizeRoute = AuthorizeRouteImport.update({
  id: '/authorize',
  path: '/authorize',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardQuestsRoute = DashboardQuestsRouteImport.update({
  id: '/quests',
  path: '/quests',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPollenRoute = DashboardPollenRouteImport.update({
  id: '/pollen',
  path: '/pollen',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardNewsRoute = DashboardNewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardModelsRoute = DashboardModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMembersRoute = DashboardMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardKeysRoute = DashboardKeysRouteImport.update({
  id: '/keys',
  path: '/keys',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardActivityRoute = DashboardActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/authorize': typeof AuthorizeRoute
  '/device': typeof DeviceRoute
  '/error': typeof ErrorRoute
  '/privacy': typeof PrivacyRoute
  '/refunds': typeof RefundsRoute
  '/sign-in': typeof SignInRoute
  '/terms': typeof TermsRoute
  '/activity': typeof DashboardActivityRoute
  '/keys': typeof DashboardKeysRoute
  '/members': typeof DashboardMembersRoute
  '/models': typeof DashboardModelsRoute
  '/news': typeof DashboardNewsRoute
  '/pollen': typeof DashboardPollenRoute
  '/quests': typeof DashboardQuestsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/authorize': typeof AuthorizeRoute
  '/device': typeof DeviceRoute
  '/error': typeof ErrorRoute
  '/privacy': typeof PrivacyRoute
  '/refunds': typeof RefundsRoute
  '/sign-in': typeof SignInRoute
  '/terms': typeof TermsRoute
  '/activity': typeof DashboardActivityRoute
  '/keys': typeof DashboardKeysRoute
  '/members': typeof DashboardMembersRoute
  '/models': typeof DashboardModelsRoute
  '/news': typeof DashboardNewsRoute
  '/pollen': typeof DashboardPollenRoute
  '/quests': typeof DashboardQuestsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_dashboard': typeof DashboardRouteWithChildren
  '/authorize': typeof AuthorizeRoute
  '/device': typeof DeviceRoute
  '/error': typeof ErrorRoute
  '/privacy': typeof PrivacyRoute
  '/refunds': typeof RefundsRoute
  '/sign-in': typeof SignInRoute
  '/terms': typeof TermsRoute
  '/_dashboard/activity': typeof DashboardActivityRoute
  '/_dashboard/keys': typeof DashboardKeysRoute
  '/_dashboard/members': typeof DashboardMembersRoute
  '/_dashboard/models': typeof DashboardModelsRoute
  '/_dashboard/news': typeof DashboardNewsRoute
  '/_dashboard/pollen': typeof DashboardPollenRoute
  '/_dashboard/quests': typeof DashboardQuestsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/authorize'
    | '/device'
    | '/error'
    | '/privacy'
    | '/refunds'
    | '/sign-in'
    | '/terms'
    | '/activity'
    | '/keys'
    | '/members'
    | '/models'
    | '/news'
    | '/pollen'
    | '/quests'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/authorize'
    | '/device'
    | '/error'
    | '/privacy'
    | '/refunds'
    | '/sign-in'
    | '/terms'
    | '/activity'
    | '/keys'
    | '/members'
    | '/models'
    | '/news'
    | '/pollen'
    | '/quests'
  id:
    | '__root__'
    | '/'
    | '/_dashboard'
    | '/authorize'
    | '/device'
    | '/error'
    | '/privacy'
    | '/refunds'
    | '/sign-in'
    | '/terms'
    | '/_dashboard/activity'
    | '/_dashboard/keys'
    | '/_dashboard/members'
    | '/_dashboard/models'
    | '/_dashboard/news'
    | '/_dashboard/pollen'
    | '/_dashboard/quests'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  AuthorizeRoute: typeof AuthorizeRoute
  DeviceRoute: typeof DeviceRoute
  ErrorRoute: typeof ErrorRoute
  PrivacyRoute: typeof PrivacyRoute
  RefundsRoute: typeof RefundsRoute
  SignInRoute: typeof SignInRoute
  TermsRoute: typeof TermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refunds': {
      id: '/refunds'
      path: '/refunds'
      fullPath: '/refunds'
      preLoaderRoute: typeof RefundsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/error': {
      id: '/error'
      path: '/error'
      fullPath: '/error'
      preLoaderRoute: typeof ErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/device': {
      id: '/device'
      path: '/device'
      fullPath: '/device'
      preLoaderRoute: typeof DeviceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authorize': {
      id: '/authorize'
      path: '/authorize'
      fullPath: '/authorize'
      preLoaderRoute: typeof AuthorizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/quests': {
      id: '/_dashboard/quests'
      path: '/quests'
      fullPath: '/quests'
      preLoaderRoute: typeof DashboardQuestsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/pollen': {
      id: '/_dashboard/pollen'
      path: '/pollen'
      fullPath: '/pollen'
      preLoaderRoute: typeof DashboardPollenRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/news': {
      id: '/_dashboard/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof DashboardNewsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/models': {
      id: '/_dashboard/models'
      path: '/models'
      fullPath: '/models'
      preLoaderRoute: typeof DashboardModelsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/members': {
      id: '/_dashboard/members'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof DashboardMembersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/keys': {
      id: '/_dashboard/keys'
      path: '/keys'
      fullPath: '/keys'
      preLoaderRoute: typeof DashboardKeysRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/activity': {
      id: '/_dashboard/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof DashboardActivityRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardActivityRoute: typeof DashboardActivityRoute
  DashboardKeysRoute: typeof DashboardKeysRoute
  DashboardMembersRoute: typeof DashboardMembersRoute
  DashboardModelsRoute: typeof DashboardModelsRoute
  DashboardNewsRoute: typeof DashboardNewsRoute
  DashboardPollenRoute: typeof DashboardPollenRoute
  DashboardQuestsRoute: typeof DashboardQuestsRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardActivityRoute: DashboardActivityRoute,
  DashboardKeysRoute: DashboardKeysRoute,
  DashboardMembersRoute: DashboardMembersRoute,
  DashboardModelsRoute: DashboardModelsRoute,
  DashboardNewsRoute: DashboardNewsRoute,
  DashboardPollenRoute: DashboardPollenRoute,
  DashboardQuestsRoute: DashboardQuestsRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  AuthorizeRoute: AuthorizeRoute,
  DeviceRoute: DeviceRoute,
  ErrorRoute: ErrorRoute,
  PrivacyRoute: PrivacyRoute,
  RefundsRoute: RefundsRoute,
  SignInRoute: SignInRoute,
  TermsRoute: TermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
