name: PR Review to Discord

on:
  pull_request:
    types: [closed]
    branches:
      - master
jobs:
  review-merged-pr:
    # Only run if PR was merged
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: |
          pip install requests PyYAML Jinja2
      
      - name: Review PR and Post to Discord
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          POLLINATIONS_TOKEN: ${{ secrets.POLLINATIONS_TOKEN_DCPRS }}
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          REPO_FULL_NAME: ${{ github.repository }}
          PR_TITLE: ${{ github.event.pull_request.title }}
          PR_URL: ${{ github.event.pull_request.html_url }}
          PR_AUTHOR: ${{ github.event.pull_request.user.login }}
          PR_BRANCH: ${{ github.event.pull_request.head.ref }}
          PR_BASE_BRANCH: ${{ github.event.pull_request.base.ref }}
        run: python .github/scripts/pr_review_discord.py

