export const newsList = `- **2025-12-08** – **New Models** Google \`veo\` (video) and \`amazon-nova-micro\` (text) added. Search enabled for \`gemini-search\` and \`perplexity-fast\`.
- **2025-12-08** – **Platform Updates** Chat now supports Chart.js visualization. Daily pollen allowances updated (Spore: 1, Seed: 3, Flower: 10, Nectar: 20).
- **2025-12-03** – **Model Upgrades!** Seedream upgraded to 4.5 (4K, 14 reference images) and Seedance upgraded to Pro-Fast (higher quality video). Use with \`?model=seedream\` or \`?model=seedance\`.
- **2025-08-24** – **Sequa AI Integration** now available! [Sequa.AI](https://sequa.ai) is a contextual knowledge engine that provides AI assistants with deep, real-time understanding of codebases and documentation. Configure MCP for Pollinations: \`https://mcp.sequa.ai/v1/pollinations/contribute\` | [Learn more](https://sequa.ai).
- **2025-07-04** – **Flux Kontext Model** now available! General-purpose image-to-image generation model supporting transformations and variations. Use with \`?model=kontext&image=URL\`.
- **2025-05-28** – **New API Dashboard** Visit [enter.pollinations.ai](https://enter.pollinations.ai) to create publishable/secret keys and manage referrers. [Learn more](https://github.com/pollinations/pollinations/blob/main/APIDOCS.md#authentication).
- **2025-04-12** – **Text Feed** New section added to the website. View real-time text generations and test text API endpoints directly from the site.
- **2025-03-28** – **API Documentation** Improvements with better examples, clearer explanations, and interactive code snippets. [API Documentation](https://github.com/pollinations/pollinations/blob/main/APIDOCS.md).
- **2025-03-24** – **MCP Audio Support** AI assistants like Claude can now generate audio in addition to images using our Model Context Protocol server. Install with \`npx @pollinations/model-context-protocol\`.
- **2025-03-20** – **New MCP Server** AI assistants like Claude can now generate images directly using our Model Context Protocol server. Install with \`npx @pollinations/model-context-protocol\`.
- **2025-03-06** – **Tip Us** You can now support us with our new Tip Us button. Optionally connect your Discord account to **Ko-Fi** to get premium Discord roles!
- **2025-03-05** – **Audio Features** Text-to-speech and speech-to-text capabilities are now available with the \`openai-audio\` model. Check the [API Docs](https://github.com/pollinations/pollinations/blob/main/APIDOCS.md).
- **2025-02-05** – **Pollinations.DIY** A browser-based development environment for building AI-powered applications with Pollinations services, based on bolt.diy! [Pollinations.DIY](https://pollinations.diy).
- **2025-02-05** – **Gemini 2.0** New Gemini 2.0 Flash and Gemini 2.0 Flash Thinking models are now available on [text.pollinations.ai/models](https://text.pollinations.ai/models)!
- **2025-01-25** – **Flux.Schnell** New lightning fast Flux.Schnell backend thanks to Cloudflare.
- **2025-01-05** – **Feature Requests** Want a new feature? Create a [GitHub issue](https://github.com/pollinations/pollinations/issues/new) and our [AI assistant](https://mentat.ai/) will implement it!`;
