export const availableModels = [
    {
        name: 'openai',
        type: 'chat',
        censored: true,
        description: 'OpenAI GPT-4o',
        baseModel: true,
    },
    {
        name: 'qwen',
        type: 'chat',
        censored: false,
        description: 'Qwen 2.5 72B',
        baseModel: true,
    },
    {
        name: 'qwen-coder',
        type: 'chat',
        censored: false,
        description: 'Qwen 2.5 Coder 32B',
        baseModel: true,
    },
    {
        name: 'llama',
        type: 'chat',
        censored: false,
        description: 'Llama 3.3 70B',
        baseModel: true,
    },
    {
        name: 'mistral',
        type: 'chat',
        censored: false,
        description: 'Mistral Nemo',
        baseModel: true,
    },
    // {
    //     name: 'mistral-large',
    //     type: 'chat',
    //     censored: false,
    //     description: 'Mistral Large (v2)',
    //     baseModel: true,
    // },
    {
        name: 'llama',
        type: 'completion',
        censored: true,
        description: 'Llama 3.1',
        baseModel: true,
    },
    // {
    //     name: 'karma',
    //     type: 'completion',
    //     censored: true,
    //     description: 'Karma.yt Zeitgeist. Connected to realtime news and the web. (beta)',
    //     baseModel: false,
    // },
    // {
    //     name: 'command-r',
    //     type: 'chat',
    //     censored: false,
    //     description: 'Command-R',
    //     baseModel: false,
    // },
    {
        name: 'unity',
        type: 'chat',
        censored: false,
        description: 'Unity with Mistral Large by Unity AI Lab',
        baseModel: false,
    },
    {
        name: 'midijourney',
        type: 'chat',
        censored: true,
        description: 'Midijourney musical transformer',
        baseModel: false,
    },
    {
        name: 'rtist',
        type: 'chat',
        censored: true,
        description: 'Rtist image generator by @bqrio',
        baseModel: false,
    },
    {
        name: 'searchgpt',
        type: 'chat',
        censored: true,
        description: 'SearchGPT with realtime news and web search',
        baseModel: false,
    },
    // { name: 'claude', type: 'chat', censored: true }
    // { name: 'sur', type: 'chat', censored: true }
    {
        name: 'evil',
        type: 'chat',
        censored: false,
        description: 'Evil Mode - Experimental',
        baseModel: false,
    },
    {
        name: 'p1',
        type: 'chat',
        censored: false,
        description: 'Pollinations 1 (OptiLLM)',
        baseModel: false,
    },
    {
        name: 'deepseek',
        type: 'chat',
        censored: true,
        description: 'DeepSeek-V3',
        baseModel: true,
    },
    // {
    //     name: 'mistral-large',
    //     type: 'chat',
    //     censored: false,
    //     description: 'Mistral Large (v2)',
    //     baseModel: true,
    // },
];
