name = "pollinations-text"
main = "container.ts"
compatibility_date = "2025-10-23"

[observability]
enabled = true

[[containers]]
max_instances = 1
class_name = "TextServiceContainer"
image = "./Dockerfile"
image_build_context = ".."
instance_type = "standard-3"

[[durable_objects.bindings]]
class_name = "TextServiceContainer"
name = "CONTAINER"

[[migrations]]
new_sqlite_classes = [ "TextServiceContainer" ]
tag = "v1"
